In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
package_directory = r'/content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages'

### Installing libraries

In [ ]:
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_jnlpba_md-0.5.4.tar.gz --target=$package_directory

Collecting https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_jnlpba_md-0.5.4.tar.gz
  Downloading https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_jnlpba_md-0.5.4.tar.gz (119.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting spacy<3.8.0,>=3.7.4 (from en_ner_jnlpba_md==0.5.4)
  Downloading spacy-3.7.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading murmurhash-1.0.11-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading cymem-2.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.4 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting thinc<8.3.0,>=8.2.2 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading thinc-8.2.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading srsly-2.4.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading typer-0.14.0-py3-none-any.whl.metadata (15 kB)
Collecting tqdm<5.0.0,>=4.38.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.0 MB/s eta 0:00:00
Collecting requests<3.0.0,>=2.13.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading pydantic-2.10.2-py3-none-any.whl.metadata (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.8/170.8 kB 7.1 MB/s eta 0:00:00
Collecting jinja2 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting setuptools (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting packaging>=20.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Collecting numpy>=1.19.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.5 MB/s eta 0:00:00
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.27.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-extensions>=4.12.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading blis-0.7.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.19.0 (from spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.4 MB/s eta 0:00:00
Collecting click>=8.0.0 (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading cloudpathlib-0.20.0-py3-none-any.whl.metadata (14 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading smart_open-7.0.5-py3-none-any.whl.metadata (24 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading marisa_trie-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting wrapt (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading wrapt-1.17.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_jnlpba_md==0.5.4)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading spacy-3.7.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 45.5 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (204 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.7/204.7 kB 15.2 MB/s eta 0:00:00
Downloading langcodes-3.5.0-py3-none-any.whl (182 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 13.9 MB/s eta 0:00:00
Downloading murmurhash-1.0.11-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.3/124.3 kB 9.3 MB/s eta 0:00:00
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 4.5 MB/s eta 0:00:00
Downloading preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.9/156.9 kB 11.2 MB/s eta 0:00:00
Downloading pydantic-2.10.2-py3-none-any.whl (456 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 456.4/456.4 kB 25.9 MB/s eta 0:00:00
Downloading pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 67.5 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 4.4 MB/s eta 0:00:00
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.4.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (493 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 493.0/493.0 kB 25.9 MB/s eta 0:00:00
Downloading thinc-8.2.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (922 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 922.4/922.4 kB 38.3 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 57.8 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 5.4 MB/s eta 0:00:00
Downloading typer-0.14.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.7/44.7 kB 2.9 MB/s eta 0:00:00
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/50.3 kB 3.3 MB/s eta 0:00:00
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 8.8 MB/s eta 0:00:00
Downloading setuptools-75.6.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 42.9 MB/s eta 0:00:00
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading blis-0.7.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 66.2 MB/s eta 0:00:00
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 11.9 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.8/144.8 kB 9.8 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 6.9 MB/s eta 0:00:00
Downloading cloudpathlib-0.20.0-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 kB 3.3 MB/s eta 0:00:00
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 5.0 MB/s eta 0:00:00
Downloading language_data-1.3.0-py3-none-any.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 84.3 MB/s eta 0:00:00
Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)
Downloading rich-13.9.4-py3-none-any.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 14.3 MB/s eta 0:00:00
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading smart_open-7.0.5-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 3.0 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 8.8 MB/s eta 0:00:00
Downloading marisa_trie-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.9 MB/s eta 0:00:00
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 6.3 MB/s eta 0:00:00
Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 43.6 MB/s eta 0:00:00
Downloading wrapt-1.17.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (82 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 5.3 MB/s eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Building wheels for collected packages: en_ner_jnlpba_md
  Building wheel for en_ner_jnlpba_md (setup.py) ... done
  Created wheel for en_ner_jnlpba_md: filename=en_ner_jnlpba_md-0.5.4-py3-none-any.whl size=119812563 sha256=99a5e5c26aa25c1db477c762edd72d8e65c695b258a5169137aa5f14a047f630
  Stored in directory: /root/.cache/pip/wheels/df/cd/76/fa76c5c45f7cdc2e348979b978dfde1111822d51e0ad46aae5
Successfully built en_ner_jnlpba_md
Installing collected packages: cymem, wrapt, wasabi, urllib3, typing-extensions, tqdm, spacy-loggers, spacy-legacy, shellingham, setuptools, pygments, packaging, numpy, murmurhash, mdurl, MarkupSafe, idna, click, charset-normalizer, certifi, catalogue, annotated-types, srsly, smart-open, requests, pydantic-core, preshed, markdown-it-py, marisa-trie, jinja2, cloudpathlib, blis, rich, pydantic, language-data, typer, langcodes, confection, weasel, thinc, spacy, en_ner_jnlpba_md
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
Successfully installed MarkupSafe-3.0.2 annotated-types-0.7.0 blis-0.7.11 catalogue-2.0.10 certifi-2024.8.30 charset-normalizer-3.4.0 click-8.1.7 cloudpathlib-0.20.0 confection-0.1.5 cymem-2.0.10 en_ner_jnlpba_md-0.5.4 idna-3.10 jinja2-3.1.4 langcodes-3.5.0 language-data-1.3.0 marisa-trie-1.2.1 markdown-it-py-3.0.0 mdurl-0.1.2 murmurhash-1.0.11 numpy-1.26.4 packaging-24.2 preshed-3.0.9 pydantic-2.10.2 pydantic-core-2.27.1 pygments-2.18.0 requests-2.32.3 rich-13.9.4 setuptools-75.6.0 shellingham-1.5.4 smart-open-7.0.5 spacy-3.7.5 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.4.8 thinc-8.2.5 tqdm-4.67.1 typer-0.14.0 typing-extensions-4.12.2 urllib3-2.2.3 wasabi-1.1.3 weasel-0.4.1 wrapt-1.17.0
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/rich-13.9.4.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/spacy_loggers-1.0.5.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/click-8.1.7.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/_distutils_hack already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/annotated_types-0.7.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/smart_open-7.0.5.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/requests-2.32.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/rich already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/language_data already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/spacy already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/spacy_loggers already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/urllib3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/preshed already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/langcodes already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pygments-2.18.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/click already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/wasabi already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/catalogue-2.0.10.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/catalogue already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/charset_normalizer-3.4.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/srsly already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/cloudpathlib-0.20.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/jinja2 already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/setuptools already exists. Specify --upgrade to force replacement.

In [ ]:
!pip install spacy --target=$package_directory

Collecting spacy
  Using cached spacy-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Using cached murmurhash-1.0.11-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Using cached cymem-2.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.4 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Using cached preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting thinc<8.4.0,>=8.3.0 (from spacy)
  Using cached thinc-8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Using cached srsly-2.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy)
  Using cached weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy)
  Using cached typer-0.15.1-py3-none-any.whl.metadata (15 kB)
Collecting tqdm<5.0.0,>=4.38.0 (from spacy)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting numpy>=1.19.0 (from spacy)
  Using cached numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting requests<3.0.0,>=2.13.0 (from spacy)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Using cached pydantic-2.10.3-py3-none-any.whl.metadata (172 kB)
Collecting jinja2 (from spacy)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting setuptools (from spacy)
  Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting packaging>=20.0 (from spacy)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy)
  Using cached langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy)
  Using cached language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.27.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-extensions>=4.12.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting blis<1.1.0,>=1.0.0 (from thinc<8.4.0,>=8.3.0->spacy)
  Using cached blis-1.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.0->spacy)
  Using cached confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.19.0 (from spacy)
  Using cached numpy-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting click>=8.0.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy)
  Using cached cloudpathlib-0.20.0-py3-none-any.whl.metadata (14 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.1.0->spacy)
  Using cached smart_open-7.0.5-py3-none-any.whl.metadata (24 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy)
  Using cached MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy)
  Using cached marisa_trie-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting wrapt (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy)
  Using cached wrapt-1.17.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached spacy-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.1 MB)
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Using cached cymem-2.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (204 kB)
Using cached langcodes-3.5.0-py3-none-any.whl (182 kB)
Using cached murmurhash-1.0.11-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
Using cached pydantic-2.10.3-py3-none-any.whl (456 kB)
Using cached pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Using cached srsly-2.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Using cached thinc-8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
Using cached numpy-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached typer-0.15.1-py3-none-any.whl (44 kB)
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Using cached weasel-0.4.1-py3-none-any.whl (50 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached blis-1.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.2 MB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached cloudpathlib-0.20.0-py3-none-any.whl (52 kB)
Using cached confection-0.1.5-py3-none-any.whl (35 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached language_data-1.3.0-py3-none-any.whl (5.4 MB)
Using cached MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)
Using cached rich-13.9.4-py3-none-any.whl (242 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached smart_open-7.0.5-py3-none-any.whl (61 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached marisa_trie-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached wrapt-1.17.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (82 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: cymem, wrapt, wasabi, urllib3, typing-extensions, tqdm, spacy-loggers, spacy-legacy, shellingham, setuptools, pygments, packaging, numpy, murmurhash, mdurl, MarkupSafe, idna, click, charset-normalizer, certifi, catalogue, annotated-types, srsly, smart-open, requests, pydantic-core, preshed, markdown-it-py, marisa-trie, jinja2, cloudpathlib, blis, rich, pydantic, language-data, typer, langcodes, confection, weasel, thinc, spacy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
accelerate 1.1.1 requires huggingface-hub>=0.21.0, but you have huggingface-hub 0.10.1 which is incompatible.
cached-path 1.1.6 requires rich<13.0,>=12.1, but you have rich 13.9.4 which is incompatible.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.0.2 which is incompatible.
diffusers 0.31.0 requires huggingface-hub>=0.23.2, but you have huggingface-hub 0.10.1 which is incompatible.
en-core-web-sm 3.7.1 requires spacy<3.8.0,>=3.7.2, but you have spacy 3.8.3 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.0.2 which is incompatible.
langchain 0.3.10 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.0.2 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.0.2 which is incompatible.
pathy 0.11.0 requires smart-open<7.0.0,>=5.2.1, but you have smart-open 7.0.5 which is incompatible.
peft 0.13.2 requires huggingface-hub>=0.17.0, but you have huggingface-hub 0.10.1 which is incompatible.
peft 0.13.2 requires torch>=1.13.0, but you have torch 1.12.1 which is incompatible.
pytensor 2.26.4 requires filelock>=3.15, but you have filelock 3.7.1 which is incompatible.
pytensor 2.26.4 requires numpy<2,>=1.17.0, but you have numpy 2.0.2 which is incompatible.
sentence-transformers 3.2.1 requires huggingface-hub>=0.20.0, but you have huggingface-hub 0.10.1 which is incompatible.
sentence-transformers 3.2.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.20.1 which is incompatible.
tensorflow 2.17.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.0.2 which is incompatible.
torchaudio 2.5.1+cu121 requires torch==2.5.1, but you have torch 1.12.1 which is incompatible.
Successfully installed MarkupSafe-3.0.2 annotated-types-0.7.0 blis-1.0.2 catalogue-2.0.10 certifi-2024.8.30 charset-normalizer-3.4.0 click-8.1.7 cloudpathlib-0.20.0 confection-0.1.5 cymem-2.0.10 idna-3.10 jinja2-3.1.4 langcodes-3.5.0 language-data-1.3.0 marisa-trie-1.2.1 markdown-it-py-3.0.0 mdurl-0.1.2 murmurhash-1.0.11 numpy-2.0.2 packaging-24.2 preshed-3.0.9 pydantic-2.10.3 pydantic-core-2.27.1 pygments-2.18.0 requests-2.32.3 rich-13.9.4 setuptools-75.6.0 shellingham-1.5.4 smart-open-7.0.5 spacy-3.8.3 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.0 thinc-8.3.2 tqdm-4.67.1 typer-0.15.1 typing-extensions-4.12.2 urllib3-2.2.3 wasabi-1.1.3 weasel-0.4.1 wrapt-1.17.0
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/typer already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/requests already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pygments already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pydantic already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/blis already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/wrapt already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/weasel already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/catalogue-2.0.10.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/spacy already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/annotated_types-0.7.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/annotated_types already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/langcodes already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/confection already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/wrapt-1.17.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/preshed already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/rich already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/murmurhash-1.0.11.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/setuptools-75.6.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/_distutils_hack already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/markdown_it already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/marisa_trie-1.2.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/langcodes-3.5.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/catalogue already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/numpy already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/smart_open already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/marisa_trie.cpython-310-x86_64-linux-gnu.so already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/packaging already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tqdm already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/charset_normalizer already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/thinc-8.3.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/markupsafe already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/urllib3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/numpy-2.0.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/mdurl-0.1.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/shellingham already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/spacy-3.8.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/typing_extensions-4.12.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/wasabi-1.1.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/weasel-0.4.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/cymem already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pydantic_core-2.27.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/blis-1.0.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/preshed-3.0.9.dist-info already exists. Specify --upgrade to force replacement.

In [ ]:
!pip install stanford_openie

Collecting stanford_openie
  Downloading stanford_openie-1.3.2-py3-none-any.whl.metadata (4.3 kB)
Collecting wget (from stanford_openie)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting stanfordnlp (from stanford_openie)
  Downloading stanfordnlp-0.2.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from stanford_openie) (1.17.0)
Requirement already satisfied: pydot in /usr/local/lib/python3.11/dist-packages (from stanford_openie) (3.0.4)
Collecting protobuf<=3.20 (from stanford_openie)
  Downloading protobuf-3.20.0-py2.py3-none-any.whl.metadata (720 bytes)
Requirement already satisfied: pyparsing>=3.0.9 in /usr/local/lib/python3.11/dist-packages (from pydot->stanford_openie) (3.2.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from stanfordnlp->stanford_openie) (1.26.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from stanfordnlp->stanford_openie) (2.32.3)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from stanfordnlp->stanford_openie) (2.5.1+cu124)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from stanfordnlp->stanford_openie) (4.67.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (3.17.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (2024.9.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.0.0->stanfordnlp->stanford_openie)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.0.0->stanfordnlp->stanford_openie) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.0.0->stanfordnlp->stanford_openie) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->stanfordnlp->stanford_openie) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->stanfordnlp->stanford_openie) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->stanfordnlp->stanford_openie) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->stanfordnlp->stanford_openie) (2024.12.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.0.0->stanfordnlp->stanford_openie) (3.0.2)
Downloading stanford_openie-1.3.2-py3-none-any.whl (5.5 kB)
Downloading protobuf-3.20.0-py2.py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 8.0 MB/s eta 0:00:00
Downloading stanfordnlp-0.2.0-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 13.2 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 80.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 59.9 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 20.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.3 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.5 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 50.9 MB/s eta 0:00:00
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=1286a3181e92fa97adc32e4102e8889733c3b1eeab2d24e9af93940025b93695
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget
Installing collected packages: wget, protobuf, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, stanfordnlp, stanford_openie
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.6
    Uninstalling protobuf-4.25.6:
      Successfully uninstalled protobuf-4.25.6
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-aiplatform 1.74.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-spanner 3.51.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-translate 3.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery-connection 1.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
grpc-google-iam-v1 0.14.0 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
tensorflow 2.18.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigtable 2.28.1 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-api-core 2.19.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5, but you have protobuf 3.20.0 which is incompatible.
google-cloud-datastore 2.20.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
tensorflow-metadata 1.16.1 requires protobuf<6.0.0dev,>=4.25.2; python_version >= "3.11", but you have protobuf 3.20.0 which is incompatible.
google-cloud-language 2.16.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-resource-manager 1.14.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-iam 2.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery-storage 2.27.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-firestore 2.19.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-functions 1.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
grpcio-status 1.62.3 requires protobuf>=4.21.6, but you have protobuf 3.20.0 which is incompatible.
googleapis-common-protos 1.66.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-pubsub 2.25.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 protobuf-3.20.0 stanford_openie-1.3.2 stanfordnlp-0.2.0 wget-3.2

In [ ]:
%pip install datasets
#pip install -U datasets --target=$package_directory

Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.11)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.27.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 2.7 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 1.6 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 1.0 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 7.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 7.7 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.5.1+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.5.1+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.2.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 xxhash-3.5.0

In [ ]:
!pip install botocore --upgrade --target=$package_directory

In [ ]:
!pip install transformers -U --target=$package_directory

Collecting transformers
  Downloading transformers-4.47.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 3.3 MB/s eta 0:00:00
Collecting filelock (from transformers)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting huggingface-hub<1.0,>=0.24.0 (from transformers)
  Downloading huggingface_hub-0.27.0-py3-none-any.whl.metadata (13 kB)
Collecting numpy>=1.17 (from transformers)
  Downloading numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.9 MB/s eta 0:00:00
Collecting packaging>=20.0 (from transformers)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyyaml>=5.1 (from transformers)
  Downloading PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 2.8 MB/s eta 0:00:00
Collecting requests (from transformers)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers)
  Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.5 MB/s eta 0:00:00
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.24.0->transformers)
  Downloading fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub<1.0,>=0.24.0->transformers)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->transformers)
  Downloading charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->transformers)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->transformers)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->transformers)
  Downloading certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Downloading transformers-4.47.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 87.4 MB/s eta 0:00:00
Downloading huggingface_hub-0.27.0-py3-none-any.whl (450 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 450.5/450.5 kB 32.3 MB/s eta 0:00:00
Downloading numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 89.4 MB/s eta 0:00:00
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 5.3 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 751.2/751.2 kB 41.7 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 37.6 MB/s eta 0:00:00
Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 435.0/435.0 kB 33.4 MB/s eta 0:00:00
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 83.2 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 7.1 MB/s eta 0:00:00
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 5.8 MB/s eta 0:00:00
Downloading certifi-2024.12.14-py3-none-any.whl (164 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.9/164.9 kB 13.7 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.8/144.8 kB 10.7 MB/s eta 0:00:00
Downloading fsspec-2024.10.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.6/179.6 kB 14.6 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 5.9 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 11.7 MB/s eta 0:00:00
Installing collected packages: urllib3, typing-extensions, tqdm, safetensors, regex, pyyaml, packaging, numpy, idna, fsspec, filelock, charset-normalizer, certifi, requests, huggingface-hub, tokenizers, transformers
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.0 which is incompatible.
langchain 0.3.11 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.2.0 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.0 which is incompatible.
pytensor 2.26.4 requires numpy<2,>=1.17.0, but you have numpy 2.2.0 which is incompatible.
tensorflow 2.17.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.2.0 which is incompatible.
thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= "3.9", but you have numpy 2.2.0 which is incompatible.
Successfully installed certifi-2024.12.14 charset-normalizer-3.4.0 filelock-3.16.1 fsspec-2024.10.0 huggingface-hub-0.27.0 idna-3.10 numpy-2.2.0 packaging-24.2 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.4.5 tokenizers-0.21.0 tqdm-4.67.1 transformers-4.47.0 typing-extensions-4.12.2 urllib3-2.2.3

In [ ]:
!pip install fastcoref --target=$package_directory

Collecting fastcoref
  Downloading fastcoref-2.1.6.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting tqdm>=4.64.0 (from fastcoref)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 2.2 MB/s eta 0:00:00
Collecting numpy>=1.21.6 (from fastcoref)
  Downloading numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.3 MB/s eta 0:00:00
Collecting scipy>=1.7.3 (from fastcoref)
  Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 3.7 MB/s eta 0:00:00
Collecting spacy>=3.0.6 (from fastcoref)
  Downloading spacy-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting torch>=1.10.0 (from fastcoref)
  Downloading torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl.metadata (28 kB)
Collecting transformers>=4.11.3 (from fastcoref)
  Downloading transformers-4.47.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 2.0 MB/s eta 0:00:00
Collecting datasets>=2.5.2 (from fastcoref)
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Collecting filelock (from datasets>=2.5.2->fastcoref)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting pyarrow>=15.0.0 (from datasets>=2.5.2->fastcoref)
  Downloading pyarrow-18.1.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting dill<0.3.9,>=0.3.0 (from datasets>=2.5.2->fastcoref)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets>=2.5.2->fastcoref)
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 5.0 MB/s eta 0:00:00
Collecting requests>=2.32.2 (from datasets>=2.5.2->fastcoref)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting xxhash (from datasets>=2.5.2->fastcoref)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets>=2.5.2->fastcoref)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets>=2.5.2->fastcoref)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Collecting aiohttp (from datasets>=2.5.2->fastcoref)
  Downloading aiohttp-3.11.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting huggingface-hub>=0.23.0 (from datasets>=2.5.2->fastcoref)
  Downloading huggingface_hub-0.26.5-py3-none-any.whl.metadata (13 kB)
Collecting packaging (from datasets>=2.5.2->fastcoref)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyyaml>=5.1 (from datasets>=2.5.2->fastcoref)
  Downloading PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy>=3.0.6->fastcoref)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy>=3.0.6->fastcoref)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy>=3.0.6->fastcoref)
  Downloading murmurhash-1.0.11-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy>=3.0.6->fastcoref)
  Downloading cymem-2.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.4 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy>=3.0.6->fastcoref)
  Downloading preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting thinc<8.4.0,>=8.3.0 (from spacy>=3.0.6->fastcoref)
  Downloading thinc-8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy>=3.0.6->fastcoref)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy>=3.0.6->fastcoref)
  Downloading srsly-2.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy>=3.0.6->fastcoref)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy>=3.0.6->fastcoref)
  Downloading weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy>=3.0.6->fastcoref)
  Downloading typer-0.15.1-py3-none-any.whl.metadata (15 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy>=3.0.6->fastcoref)
  Downloading pydantic-2.10.3-py3-none-any.whl.metadata (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 9.3 MB/s eta 0:00:00
Collecting jinja2 (from spacy>=3.0.6->fastcoref)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting setuptools (from spacy>=3.0.6->fastcoref)
  Downloading setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy>=3.0.6->fastcoref)
  Downloading langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Collecting typing-extensions>=4.8.0 (from torch>=1.10.0->fastcoref)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting networkx (from torch>=1.10.0->fastcoref)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.10.0->fastcoref)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.1.0 (from torch>=1.10.0->fastcoref)
  Downloading triton-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting sympy==1.13.1 (from torch>=1.10.0->fastcoref)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch>=1.10.0->fastcoref)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting regex!=2019.12.17 (from transformers>=4.11.3->fastcoref)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 2.7 MB/s eta 0:00:00
Collecting tokenizers<0.22,>=0.21 (from transformers>=4.11.3->fastcoref)
  Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers>=4.11.3->fastcoref)
  Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl.metadata (6.1 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Collecting attrs>=17.3.0 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading frozenlist-1.5.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading multidict-6.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting propcache>=0.2.0 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading propcache-0.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets>=2.5.2->fastcoref)
  Downloading yarl-1.18.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 kB 4.5 MB/s eta 0:00:00
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy>=3.0.6->fastcoref)
  Downloading language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.6->fastcoref)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.27.1 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3.0.6->fastcoref)
  Downloading pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.32.2->datasets>=2.5.2->fastcoref)
  Downloading charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests>=2.32.2->datasets>=2.5.2->fastcoref)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.32.2->datasets>=2.5.2->fastcoref)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests>=2.32.2->datasets>=2.5.2->fastcoref)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting blis<1.1.0,>=1.0.0 (from thinc<8.4.0,>=8.3.0->spacy>=3.0.6->fastcoref)
  Downloading blis-1.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.0->spacy>=3.0.6->fastcoref)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.21.6 (from fastcoref)
  Downloading numpy-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 4.0 MB/s eta 0:00:00
Collecting click>=8.0.0 (from typer<1.0.0,>=0.3.0->spacy>=3.0.6->fastcoref)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy>=3.0.6->fastcoref)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer<1.0.0,>=0.3.0->spacy>=3.0.6->fastcoref)
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy>=3.0.6->fastcoref)
  Downloading cloudpathlib-0.20.0-py3-none-any.whl.metadata (14 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.1.0->spacy>=3.0.6->fastcoref)
  Downloading smart_open-7.0.5-py3-none-any.whl.metadata (24 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy>=3.0.6->fastcoref)
  Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets>=2.5.2->fastcoref)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->datasets>=2.5.2->fastcoref)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->datasets>=2.5.2->fastcoref)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy>=3.0.6->fastcoref)
  Downloading marisa_trie-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets>=2.5.2->fastcoref)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy>=3.0.6->fastcoref)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy>=3.0.6->fastcoref)
  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting wrapt (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy>=3.0.6->fastcoref)
  Downloading wrapt-1.17.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy>=3.0.6->fastcoref)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 16.1 MB/s eta 0:00:00
Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 MB 15.4 MB/s eta 0:00:00
Downloading spacy-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.1/29.1 MB 19.8 MB/s eta 0:00:00
Downloading torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl (906.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 906.4/906.4 MB 534.7 kB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.2 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 63.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 46.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 32.3 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 846.5 kB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.6 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 2.7 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 1.7 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 7.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 68.7 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 6.7 MB/s eta 0:00:00
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 89.9 MB/s eta 0:00:00
Downloading triton-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.5/209.5 MB 1.7 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 4.8 MB/s eta 0:00:00
Downloading transformers-4.47.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 80.1 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (204 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.7/204.7 kB 13.4 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.1 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 10.4 MB/s eta 0:00:00
Downloading aiohttp-3.11.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 15.7 MB/s eta 0:00:00
Downloading huggingface_hub-0.26.5-py3-none-any.whl (447 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.8/447.8 kB 24.4 MB/s eta 0:00:00
Downloading langcodes-3.5.0-py3-none-any.whl (182 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 kB 11.2 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.2 MB/s eta 0:00:00
Downloading murmurhash-1.0.11-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.3/124.3 kB 7.8 MB/s eta 0:00:00
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 3.8 MB/s eta 0:00:00
Downloading preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.9/156.9 kB 10.2 MB/s eta 0:00:00
Downloading pyarrow-18.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (40.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 MB 23.1 MB/s eta 0:00:00
Downloading pydantic-2.10.3-py3-none-any.whl (456 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.0/457.0 kB 24.8 MB/s eta 0:00:00
Downloading pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 66.0 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 751.2/751.2 kB 34.8 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 37.1 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)

In [ ]:
!pip install sentence-transformers --target=$package_directory

Collecting sentence-transformers
  Downloading sentence_transformers-3.3.1-py3-none-any.whl.metadata (10 kB)
Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-4.47.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 1.7 MB/s eta 0:00:00
Collecting tqdm (from sentence-transformers)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl.metadata (28 kB)
Collecting scikit-learn (from sentence-transformers)
  Using cached scikit_learn-1.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting scipy (from sentence-transformers)
  Using cached scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Using cached huggingface_hub-0.26.5-py3-none-any.whl.metadata (13 kB)
Collecting Pillow (from sentence-transformers)
  Using cached pillow-11.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting filelock (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting packaging>=20.9 (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyyaml>=5.1 (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting requests (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub>=0.20.0->sentence-transformers)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting networkx (from torch>=1.11.0->sentence-transformers)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch>=1.11.0->sentence-transformers)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.1.0 (from torch>=1.11.0->sentence-transformers)
  Downloading triton-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting sympy==1.13.1 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch>=1.11.0->sentence-transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting numpy>=1.17 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Using cached numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting regex!=2019.12.17 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Using cached regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
Collecting tokenizers<0.22,>=0.21 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting joblib>=1.2.0 (from scikit-learn->sentence-transformers)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn->sentence-transformers)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.11.0->sentence-transformers)
  Using cached MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->huggingface-hub>=0.20.0->sentence-transformers)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 7.1 MB/s eta 0:00:00
Downloading huggingface_hub-0.26.5-py3-none-any.whl (447 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.8/447.8 kB 19.8 MB/s eta 0:00:00
Downloading torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl (906.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 906.4/906.4 MB 790.2 kB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 22.7 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 55.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 42.9 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 7.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.8 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.7 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 5.0 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 17.5 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 2.3 MB/s eta 0:00:00
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 49.1 MB/s eta 0:00:00
Downloading triton-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.5/209.5 MB 7.5 MB/s eta 0:00:00
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading transformers-4.47.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 92.5 MB/s eta 0:00:00
Using cached pillow-11.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.4 MB)
Using cached scikit_learn-1.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
Using cached scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)
Using cached fsspec-2024.10.0-py3-none-any.whl (179 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
Using cached regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 435.0/435.0 kB 26.1 MB/s eta 0:00:00
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 75.7 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 54.3 MB/s eta 0:00:00
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 29.1 MB/s eta 0:00:00
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, tqdm, threadpoolctl, sympy, safetensors, regex, pyyaml, Pillow, packaging, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, joblib, idna, fsspec, filelock, charset-normalizer, certifi, triton, scipy, requests, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jinja2, scikit-learn, nvidia-cusolver-cu12, huggingface-hub, torch, tokenizers, transformers, sentence-transformers
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 1.4.20 requires pydantic>=2.7.0, but you have pydantic 1.8.2 which is incompatible.
cached-path 1.1.6 requires filelock<3.9,>=3.4, but you have filelock 3.16.1 which is incompatible.
cached-path 1.1.6 requires huggingface-hub<0.11.0,>=0.8.1, but you have huggingface-hub 0.26.5 which is incompatible.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.14.1 which is incompatible.
langchain 0.3.10 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.2.0 which is incompatible.
langchain 0.3.10 requires pydantic<3.0.0,>=2.7.4, but you have pydantic 1.8.2 which is incompatible.
langchain-core 0.3.22 requires pydantic<3.0.0,>=2.5.2; python_full_version < "3.12.4", but you have pydantic 1.8.2 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.0 which is incompatible.
openai 1.54.5 requires pydantic<3,>=1.9.0, but you have pydantic 1.8.2 which is incompatible.
pymc 5.18.2 requires rich>=13.7.1, but you have rich 12.6.0 which is incompatible.
pytensor 2.26.4 requires numpy<2,>=1.17.0, but you have numpy 2.2.0 which is incompatible.
spacy 3.3.3 requires typing-extensions<4.6.0,>=3.7.4.1, but you have typing-extensions 4.12.2 which is incompatible.
tensorflow 2.17.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.2.0 which is incompatible.
torchvision 0.13.1 requires torch==1.12.1, but you have torch 2.5.1 which is incompatible.
Successfully installed MarkupSafe-3.0.2 Pillow-11.0.0 certifi-2024.8.30 charset-normalizer-3.4.0 filelock-3.16.1 fsspec-2024.10.0 huggingface-hub-0.26.5 idna-3.10 jinja2-3.1.4 joblib-1.4.2 mpmath-1.3.0 networkx-3.4.2 numpy-2.2.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 packaging-24.2 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.4.5 scikit-learn-1.6.0 scipy-1.14.1 sentence-transformers-3.3.1 sympy-1.13.1 threadpoolctl-3.5.0 tokenizers-0.21.0 torch-2.5.1 tqdm-4.67.1 transformers-4.47.0 triton-3.1.0 typing-extensions-4.12.2 urllib3-2.2.3
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/nvidia_nvjitlink_cu12-12.4.127.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/requests already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tokenizers already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/triton-3.1.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/mpmath already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/sklearn already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/yaml already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/nvidia_nvtx_cu12-12.4.127.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/regex-2024.11.6.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/networkx already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/joblib already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/PIL already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/nvidia_cusparse_cu12-12.3.1.170.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/scikit_learn-1.6.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/scipy-1.14.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/nvidia_cuda_nvrtc_cu12-12.4.127.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/numpy already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/packaging already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/torchgen already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tqdm already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/charset_normalizer already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/markupsafe already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/urllib3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/mpmath-1.3.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/scikit_learn.libs already exists. Specify --upgrade to force replacement.

In [ ]:
!pip install bioc --target=$package_directory

Collecting bioc
  Downloading bioc-2.1-py3-none-any.whl.metadata (4.6 kB)
Collecting lxml>=4.6.3 (from bioc)
  Downloading lxml-5.3.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting jsonlines>=1.2.0 (from bioc)
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting intervaltree (from bioc)
  Downloading intervaltree-3.1.0.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting tqdm (from bioc)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 3.9 MB/s eta 0:00:00
Collecting docopt (from bioc)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting attrs>=19.2.0 (from jsonlines>=1.2.0->bioc)
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting sortedcontainers<3.0,>=2.0 (from intervaltree->bioc)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Downloading bioc-2.1-py3-none-any.whl (33 kB)
Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Downloading lxml-5.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 50.8 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 6.7 MB/s eta 0:00:00
Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 5.4 MB/s eta 0:00:00
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: docopt, intervaltree
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=506a14eea0af6975b1e8a5515189d900552bad1817634e07de8c59109180f9b1
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
  Building wheel for intervaltree (setup.py) ... done
  Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26097 sha256=7759ae17f1212273b2190f7d9c6aa3c603704cac318fa0194494d20021985205
  Stored in directory: /root/.cache/pip/wheels/fa/80/8c/43488a924a046b733b64de3fac99252674c892a4c3801c0a61
Successfully built docopt intervaltree
Installing collected packages: sortedcontainers, docopt, tqdm, lxml, intervaltree, attrs, jsonlines, bioc
Successfully installed attrs-24.2.0 bioc-2.1 docopt-0.6.2 intervaltree-3.1.0 jsonlines-4.0.0 lxml-5.3.0 sortedcontainers-2.4.0 tqdm-4.67.1
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tqdm already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/attrs already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/attr already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tqdm-4.67.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/attrs-24.2.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/bin already exists. Specify --upgrade to force replacement.

!pip install allennlp --target=$package_directory

!pip install allennlp-models --target=$package_directory

!pip install --upgrade allennlp allennlp-models --target=$package_directory

In [ ]:
!pip install neuralcoref --target=$package_directory

In [ ]:
!pip install keybert --target=$package_directory

Collecting keybert
  Downloading keybert-0.8.5-py3-none-any.whl.metadata (15 kB)
Collecting numpy>=1.18.5 (from keybert)
  Using cached numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting rich>=10.4.0 (from keybert)
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting scikit-learn>=0.22.2 (from keybert)
  Downloading scikit_learn-1.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting sentence-transformers>=0.3.8 (from keybert)
  Downloading sentence_transformers-3.3.1-py3-none-any.whl.metadata (10 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.4.0->keybert)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.4.0->keybert)
  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting typing-extensions<5.0,>=4.0.0 (from rich>=10.4.0->keybert)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting scipy>=1.6.0 (from scikit-learn>=0.22.2->keybert)
  Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 3.3 MB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn>=0.22.2->keybert)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn>=0.22.2->keybert)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers>=0.3.8->keybert)
  Downloading transformers-4.47.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 3.0 MB/s eta 0:00:00
Collecting tqdm (from sentence-transformers>=0.3.8->keybert)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting torch>=1.11.0 (from sentence-transformers>=0.3.8->keybert)
  Downloading torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl.metadata (28 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers>=0.3.8->keybert)
  Using cached huggingface_hub-0.26.5-py3-none-any.whl.metadata (13 kB)
Collecting Pillow (from sentence-transformers>=0.3.8->keybert)
  Downloading pillow-11.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting filelock (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Downloading fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting packaging>=20.9 (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyyaml>=5.1 (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting requests (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting networkx (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.1.0 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading triton-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting sympy==1.13.1 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting regex!=2019.12.17 (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert)
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 845.1 kB/s eta 0:00:00
Collecting tokenizers<0.22,>=0.21 (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert)
  Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert)
  Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading keybert-0.8.5-py3-none-any.whl (37 kB)
Using cached numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
Downloading rich-13.9.4-py3-none-any.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 8.9 MB/s eta 0:00:00
Downloading scikit_learn-1.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 54.1 MB/s eta 0:00:00
Downloading sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 17.4 MB/s eta 0:00:00
Using cached huggingface_hub-0.26.5-py3-none-any.whl (447 kB)
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 19.9 MB/s eta 0:00:00
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 6.5 MB/s eta 0:00:00
Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 43.1 MB/s eta 0:00:00
Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 MB 15.9 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Downloading torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl (906.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 906.4/906.4 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 85.9 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 29.1 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 46.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.9 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.1 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 6.6 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 66.4 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.6 MB/s eta 0:00:00
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 82.9 MB/s eta 0:00:00
Downloading triton-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.5/209.5 MB 5.6 MB/s eta 0:00:00
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading transformers-4.47.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 66.0 MB/s eta 0:00:00
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading pillow-11.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 61.3 MB/s eta 0:00:00
Downloading fsspec-2024.10.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.6/179.6 kB 12.4 MB/s eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.7/781.7 kB 29.1 MB/s eta 0:00:00
Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 435.0/435.0 kB 25.6 MB/s eta 0:00:00
Downloading tokenizers-0.21.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 57.2 MB/s eta 0:00:00
Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 9.3 MB/s eta 0:00:00
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 49.8 MB/s eta 0:00:00
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Downloading MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 24.3 MB/s eta 0:00:00
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, tqdm, threadpoolctl, sympy, safetensors, regex, pyyaml, pygments, Pillow, packaging, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, mdurl, MarkupSafe, joblib, idna, fsspec, filelock, charset-normalizer, certifi, triton, scipy, requests, nvidia-cusparse-cu12, nvidia-cudnn-cu12, markdown-it-py, jinja2, scikit-learn, rich, nvidia-cusolver-cu12, huggingface-hub, torch, tokenizers, transformers, sentence-transformers, keybert
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.14.1 which is incompatible.
langchain 0.3.10 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.2.0 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.0 which is incompatible.
pytensor 2.26.4 requires numpy<2,>=1.17.0, but you have numpy 2.2.0 which is incompatible.
tensorflow 2.17.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.2.0 which is incompatible.
thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= "3.9", but you have numpy 2.2.0 which is incompatible.
Successfully installed MarkupSafe-3.0.2 Pillow-11.0.0 certifi-2024.8.30 charset-normalizer-3.4.0 filelock-3.16.1 fsspec-2024.10.0 huggingface-hub-0.26.5 idna-3.10 jinja2-3.1.4 joblib-1.4.2 keybert-0.8.5 markdown-it-py-3.0.0 mdurl-0.1.2 mpmath-1.3.0 networkx-3.4.2 numpy-2.2.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 packaging-24.2 pygments-2.18.0 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 rich-13.9.4 safetensors-0.4.5 scikit-learn-1.6.0 scipy-1.14.1 sentence-transformers-3.3.1 sympy-1.13.1 threadpoolctl-3.5.0 tokenizers-0.21.0 torch-2.5.1 tqdm-4.67.1 transformers-4.47.0 triton-3.1.0 typing-extensions-4.12.2 urllib3-2.2.3
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/nvidia_nvjitlink_cu12-12.4.127.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/requests already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pygments already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tokenizers already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/triton-3.1.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/mpmath already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/sklearn already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/yaml already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/nvidia_nvtx_cu12-12.4.127.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/regex-2024.11.6.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/rich already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/networkx already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/joblib already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/markdown_it already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/PIL already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/nvidia_cusparse_cu12-12.3.1.170.dist-info already exists. Specify --upgrade to force replacement.

In [ ]:
!pip install datasets --target=$package_directory

Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Collecting filelock (from datasets)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting numpy>=1.17 (from datasets)
  Downloading numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.9 MB/s eta 0:00:00
Collecting pyarrow>=15.0.0 (from datasets)
  Downloading pyarrow-18.1.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 5.3 MB/s eta 0:00:00
Collecting requests>=2.32.2 (from datasets)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm>=4.66.3 (from datasets)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.5 MB/s eta 0:00:00
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Collecting aiohttp (from datasets)
  Downloading aiohttp-3.11.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting huggingface-hub>=0.23.0 (from datasets)
  Downloading huggingface_hub-0.26.5-py3-none-any.whl.metadata (13 kB)
Collecting packaging (from datasets)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyyaml>=5.1 (from datasets)
  Downloading PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)
  Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl.metadata (6.1 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets)
  Downloading aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp->datasets)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Collecting attrs>=17.3.0 (from aiohttp->datasets)
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->datasets)
  Downloading frozenlist-1.5.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)
  Downloading multidict-6.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting propcache>=0.2.0 (from aiohttp->datasets)
  Downloading propcache-0.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets)
  Downloading yarl-1.18.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 kB 5.5 MB/s eta 0:00:00
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub>=0.23.0->datasets)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Downloading charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests>=2.32.2->datasets)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.32.2->datasets)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests>=2.32.2->datasets)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->datasets)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->datasets)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 22.3 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.7 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 11.3 MB/s eta 0:00:00
Downloading aiohttp-3.11.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 51.4 MB/s eta 0:00:00
Downloading huggingface_hub-0.26.5-py3-none-any.whl (447 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.8/447.8 kB 29.2 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 11.9 MB/s eta 0:00:00
Downloading numpy-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 44.7 MB/s eta 0:00:00
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 5.4 MB/s eta 0:00:00
Downloading pyarrow-18.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (40.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 MB 15.6 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 751.2/751.2 kB 40.2 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 3.9 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 6.5 MB/s eta 0:00:00
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 38.2 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 14.8 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl (14 kB)
Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 5.1 MB/s eta 0:00:00
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 12.3 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.8/144.8 kB 11.3 MB/s eta 0:00:00
Downloading frozenlist-1.5.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (241 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.9/241.9 kB 15.9 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 5.1 MB/s eta 0:00:00
Downloading multidict-6.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 kB 9.2 MB/s eta 0:00:00
Downloading propcache-0.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (205 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 205.1/205.1 kB 15.1 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 17.2 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 21.6 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 22.8 MB/s eta 0:00:00
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 10.2 MB/s eta 0:00:00
Downloading yarl-1.18.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 kB 20.4 MB/s eta 0:00:00
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, xxhash, urllib3, tzdata, typing-extensions, tqdm, six, pyyaml, pyarrow, propcache, packaging, numpy, idna, fsspec, frozenlist, filelock, dill, charset-normalizer, certifi, attrs, async-timeout, aiohappyeyeballs, requests, python-dateutil, multiprocess, multidict, aiosignal, yarl, pandas, huggingface-hub, aiohttp, datasets
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.10.1 requires pandas<2.2.3dev0,>=2.0, but you have pandas 2.2.3 which is incompatible.
cudf-cu12 24.10.1 requires pyarrow<18.0.0a0,>=14.0.0, but you have pyarrow 18.1.0 which is incompatible.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.0 which is incompatible.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
langchain 0.3.10 requires async-timeout<5.0.0,>=4.0.0; python_version < "3.11", but you have async-timeout 5.0.1 which is incompatible.
langchain 0.3.10 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.2.0 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.0 which is incompatible.
pylibcudf-cu12 24.10.1 requires pyarrow<18.0.0a0,>=14.0.0, but you have pyarrow 18.1.0 which is incompatible.
pytensor 2.26.4 requires numpy<2,>=1.17.0, but you have numpy 2.2.0 which is incompatible.
tensorflow 2.17.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.2.0 which is incompatible.
thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= "3.9", but you have numpy 2.2.0 which is incompatible.
Successfully installed aiohappyeyeballs-2.4.4 aiohttp-3.11.10 aiosignal-1.3.1 async-timeout-5.0.1 attrs-24.2.0 certifi-2024.8.30 charset-normalizer-3.4.0 datasets-3.2.0 dill-0.3.8 filelock-3.16.1 frozenlist-1.5.0 fsspec-2024.9.0 huggingface-hub-0.26.5 idna-3.10 multidict-6.1.0 multiprocess-0.70.16 numpy-2.2.0 packaging-24.2 pandas-2.2.3 propcache-0.2.1 pyarrow-18.1.0 python-dateutil-2.9.0.post0 pytz-2024.2 pyyaml-6.0.2 requests-2.32.3 six-1.17.0 tqdm-4.67.1 typing-extensions-4.12.2 tzdata-2024.2 urllib3-2.2.3 xxhash-3.5.0 yarl-1.18.3
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/requests already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/async_timeout-5.0.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/aiohappyeyeballs already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/aiohttp-3.11.10.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/aiosignal already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/yaml already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pytz-2024.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/fsspec-2024.9.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/dateutil already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tzdata-2024.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/aiohttp already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pyarrow already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/yarl already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/datasets already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/numpy already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/packaging already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tqdm already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/charset_normalizer already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/multidict-6.1.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/frozenlist-1.5.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/attrs-24.2.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/urllib3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/typing_extensions-4.12.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/yarl-1.18.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/numpy-2.2.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pandas-2.2.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/async_timeout already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/six.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pyarrow-18.1.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/six-1.17.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tqdm-4.67.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/_yaml already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/urllib3-2.2.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/_multiprocess already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/huggingface_hub already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/certifi-2024.8.30.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/packaging-24.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/multiprocess already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/aiohappyeyeballs-2.4.4.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/tzdata already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/pandas already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/xxhash already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/filelock already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/propcache-0.2.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/python_dateutil-2.9.0.post0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/typing_extensions.py already exists. Specify --upgrade to force replacement.

### Loading the libraries

In [ ]:
import os

In [ ]:
import copy

os.chdir(package_directory)

os.getcwd()

In [ ]:
import sys

In [ ]:
sys.path.append(package_directory)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import spacy
#from spacy import displacy
#import en_core_sci_md
#import scispacy
#import en_ner_jnlpba_md
import re

In [ ]:
from keybert import KeyBERT

In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
#import datasets
from datasets import load_dataset, Dataset

In [ ]:
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline, Seq2SeqTrainingArguments, Seq2SeqTrainer, AutoModelForSeq2SeqLM, AutoModelForCausalLM, AutoModel, TrainingArguments, Trainer, IntervalStrategy, EarlyStoppingCallback

In [ ]:
import torch

In [ ]:
if torch.cuda.is_available():
    # Get the device name
    device = torch.device("cuda")
    print("GPU Name:", torch.cuda.get_device_name(device))
else:
    device = torch.device("cpu")
    print("No GPU available.")

No GPU available.

In [ ]:
!git clone https://github.com/nicpopovic/FREDo.git # FREDo dataset for finetuning REBEL model

Cloning into 'FREDo'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 62 (delta 30), reused 45 (delta 18), pack-reused 0 (from 0)
Receiving objects: 100% (62/62), 7.71 MiB | 12.41 MiB/s, done.
Resolving deltas: 100% (30/30), done.

#### AllenNLP modules

In [ ]:
!python --version

In [ ]:
import torch

In [ ]:
torch.__version__

'2.5.1+cu121'

In [ ]:
import transformers

In [ ]:
transformers.__version__

'4.46.3'

In [ ]:
import spacy
spacy.__version__

'3.7.5'

### Implementation

In [ ]:
df = pd.read_json('/content/research_text_pubmed_heart_failure.json')

In [ ]:
df.head()

,associated data,title,url,reference_links__associated data,reference__associated data,abstract,reference_links__abstract,reference__abstract,introduction,reference_links__introduction,...,reference__institutional review board statement,informed consent statement,reference_links__informed consent statement,reference__informed consent statement,data availability statement,reference_links__data availability statement,reference__data availability statement,conflicts of interest,reference_links__conflicts of interest,reference__conflicts of interest
0,associated data,"Functional mutation, splice, distribution, and...",https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,,,abstract Cardiovascular disease (CVD) is cau...,,,introduction Cardiovascular disease (CVD) is...,"1 /pmc/articles/PMC6366352/, 2 https://pubmed....",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,associated data,Common- and rare-variant genetic architecture ...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,,,abstract Heart failure (HF) is a complex tra...,,,introduction Heart failure (HF) is a heterog...,"1 /pmc/articles/PMC4868779/, 2 /pmc/articles/P...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,associated data,Single-cell RNA sequencing in donor and end-st...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,,,abstract BackgroundDilation may be the first...,,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,associated data,Overlap phenotypes of the left ventricular non...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8...,,,abstract BackgroundThe left ventricular nonc...,,,introduction The left ventricular noncompact...,"1 /pmc/articles/PMC7566488/, 2 https://pubmed....",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,associated data,Titin‐truncating variants are associated with ...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6...,,,abstract BackgroundTitin‐truncating variants...,,,introduction Left ventricular non‐compaction...,"1 https://pubmed.ncbi.nlm.nih.gov/25865865, 2 ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(9, 147)

#### Using sciSpacy Base

In [ ]:
nlp = spacy.load('en_core_sci_md')

In [ ]:
def convert_to_doc(text:str):
  doc = nlp(text)
  return doc

In [ ]:
def preprocess_text(text: str):
  '''
  The aim of this function is to preprocess text by converting it to lowercase, and punctuations.
  '''
  text = text.lower()
  text = re.sub(r",\s?",' ', text)
  text = re.sub(r'\.\s*', ' ', text)
  return text

In [ ]:
def filter_text(text:str):
    try:
        if type(text) != str:
            return ''
        else:
            if 'abstract' not in text:
                return text
            else:
                text = text.replace('abstract ', '')
                return text
    except:
        print(f'Error text: {text}...{type(text)}')

In [ ]:
df['abstract_updated'] = df['abstract'].apply(lambda row: filter_text(row))

In [ ]:
df['abstract_updated'] = df['abstract_updated'].apply(lambda row: preprocess_text(row))

In [ ]:
df['abstract_updated'] = df['abstract_updated'].apply(lambda row: convert_to_doc(row))

In [ ]:
extracted_entities_base = []

In [ ]:
def perform_ner(doc) -> list:
    #doc = nlp(text)
    #entities = [entity for entity in doc.ents]
    entities = [(ent.text, ent.start, ent.end, ent.label_) for ent in doc.ents]
    return entities

In [ ]:
def extract_relations(doc, entities):
    relations = []

    for token in doc:
        # Check for subject-object relationships
        if token.dep_ in ("nsubj", "nsubjpass") and token.head.pos_ == "VERB":
            # Find subject and object spans that match entities
            subject_entity = next((ent for ent in entities if ent[1] <= token.i < ent[2]), None)
            object_entity = next(
                (ent for ent in entities if any(right.i >= ent[1] and right.i < ent[2] for right in token.head.rights)),
                None
            )

            # Add relation if both subject and object entities are found
            if subject_entity and object_entity:
                relations.append((subject_entity[0], token.head.text, object_entity[0]))
    '''
    for token in doc:
        if token.dep_ in ("nsubj", "nsubjpass") and token.head.pos_ == "VERB":
            subject = [w.text for w in token.subtree if w.ent_type_]
            objects = [w.text for w in token.head.rights if w.ent_type_]
            if subject and objects:
                relations.append((subject[0], token.head.text, objects[0]))

        # Add relationships involving prepositional phrases
        if token.dep_ == "prep" and token.head.pos_ == "VERB":
            prep_object = [w.text for w in token.subtree if w.ent_type_]
            if prep_object:
                relations.append((token.head.text, token.dep_, prep_object[0]))
    '''

    return relations

In [ ]:
_ = df['abstract_updated'].apply(lambda row: extracted_entities.extend(perform_ner(row)))

In [ ]:
extracted_entities = list(set(extracted_entities_base))

In [ ]:
extracted_entities

[rbm20variants,
 results,
 comprehensive analysis,
 strength conclusionsthe,
 level,
 ttntv,
 systolic heart failure,
 divergence analysis,
 identified,
 heightened,
 mice,
 adipocyte,
 years,
 cst3,
 keywords,
 divergence analysis,
 high-throughput target capture sequencing,
 fibroblast pharmacological inhibition,
 rbm20variant,
 men,
 dsg2mut/mutmice,
 accelerates,
 diagnosed,
 cvd genes,
 patients,
 presence,
 dysfunction,
 nod-like receptor protein 3,
 detected,
 identification,
 consented,
 heart transplantation,
 clinical management,
 eshf,
 arvc model,
 arvc,
 expression,
 desmosomes,
 interact,
 genetics diagnosis,
 prognosis therapy,
 coding variants,
 allele-frequency spectrum,
 hf,
 mva,
 ttntv,
 common-variant background,
 left ventricular non‐compaction cardiomyopathy,
 rare,
 associated with,
 genetic variants,
 lvnc,
 review,
 targeted capture sequencing,
 genetic variants,
 proband,
 baseline,
 online,
 hf,
 gene burden studies,
 identification,
 rarer,
 genome,
 risk,
 myeloid subclusters,
 study participants,
 investigated,
 heart failure,
 intron,
 clinical,
 risk,
 effects,
 families,
 interactions,
 mutation splice variant,
 k47rfs*2,
 independent,
 condition,
 carriers,
 eshf keywords,
 individual,
 heart failure,
 cvd genes,
 patients,
 no significant,
 titin,
 dcm,
 sex,
 rare,
 lvef,
 threatening,
 cardiovascular disease,
 million,
 blood,
 associated with,
 burden,
 overlap,
 regulators,
 heritable,
 ofccl3+proinflammatory macrophages,
 gene expression,
 mendelian cardiomyopathy,
 primary endpoint,
 detection,
 next-generation sequencing,
 systolic heart failure,
 secondary endpoint,
 etiologies,
 affected,
 carriers,
 retrospectively,
 left ventricular noncompaction cardiomyopathy,
 variants,
 therapeutic,
 fadd,
 progression,
 rare,
 overlap,
 outcomes methods,
 findings,
 associated with,
 proinflammatory macrophages,
 discovery,
 arrhythmogenic right ventricular cardiomyopathy,
 results,
 rate,
 idiopathic left ventricular systolic dysfunction,
 wgs,
 hypertrophic cardiomyopathy,
 susceptibility,
 dcm,
 genome-wide association studies,
 management,
 common-,
 effects,
 therapeutic,
 geneticists,
 genotype,
 left ventricular ejection fraction,
 protein,
 mva,
 cohorts,
 data,
 screened,
 multiple,
 left ventricular systolic dysfunction,
 peripheral blood,
 associated with,
 mva,
 hf,
 functional,
 eshf,
 genes,
 skin,
 years,
 mva,
 fibroblasts,
 adult,
 ttntv,
 events,
 phenotype,
 mva event,
 heart failure,
 spread,
 gwas,
 expressing,
 arvc desmoglein 2 (dsg2)mut/mutmice,
 relatives carryingrbm20variants,
 peripheral blood,
 plof,
 carriers,
 common-variant loci,
 lvnc,
 cardiovascular diseases,
 genetic variants,
 adverse events,
 truncating,
 hypertrophic cardiomyopathy,
 risk,
 genetics,
 macrophages,
 arvc,
 heterozygousdsc2p,
 lgals3,
 lvnc methodsttnwas,
 capability,
 challenges,
 biventricular myocardium,
 heart failure,
 ttntv,
 populations,
 diverse,
 perspective,
 genetic variants,
 sudden cardiac death,
 sudden cardiac death,
 people,
 variants,
 flank 3ʹ utr,
 characterization,
 end-stage heart failure,
 impact,
 multiple,
 nlrp3,
 risk,
 patients,
 detected,
 lineage-specific changes,
 fatal,
 modifies,
 transcriptional factor,
 pharmacological inhibition,
 phenotypes,
 genetic variants,
 evaluation,
 health burden,
 keywords,
 classes,
 heart transplantation,
 patients,
 prs,
 right ventricular dilation,
 lvef,
 interpretation,
 capacity,
 relationships,
 impact,
 hba1,
 keywords,
 men,
 proband,
 healthy,
 treatment,
 mutation,
 signals,
 stratification,
 gene ttn,
 median,
 cardiomyopathies,
 familial cases,
 nppc adrb2,
 genetic,
 participants,
 desmocollin2 protein,
 individuals,
 consecutive,
 therapeutics,
 women,
 variants,
 heart failure,
 presence,
 missense mutations,
 eshf,
 cardiologists,
 heart transplantation,
 exome-wide significant,
 arvc mouse model,
 rbm20variant,
 phenotype,
 diffuse,
 reduced,
 cardiovascular diseases,
 cvd,
 rare-variant association studies,
 dcm,
 improve,
 data,
 hf,
 indication,
 non‐carriers,
 heart failure,
 genetic data,
 genetic testing,
 novel,
 prevent,
 mortality,
 gwas,
 etiology,
 familial cardiomyopathies,
 heart failure desmocollin2 desmosome,
 hospitalization,
 results,
 desmocollin2,
 cell types,
 variants,
 phenotypes,
 mva,
 cardiac arrhythmia,
 human,
 sex age,
 risk,
 events,
 genome-wide association,
 mybpc3 flnc,
 sensitivity analysis,
 complex,
 variant,
 specializing,
 years,
 sequenced,
 cvd,
 cardiac magnetic resonance imaging,
 associated with,
 cald1,
 improving,
 study,
 risk loci,
 dysfunction,
 composite,
 cell-specific contributions,
 context,
 cohort,
 lgals3,
 genetic cause,
 affected,
 associated with,
 effect,
 male,
 composite,
 subtype,
 truncating,
 analyzed,
 heterozygous truncated mutation,
 loss-of-function,
 western blots,
 inrbm20variant,
 right ventricular dilation,
 multivariable analyses,
 proband,
 rapid sequencing,
 phenotypes,
 associations,
 carriers,
 volunteer,
 expression,
 desmocollin2,
 genetic modifier,
 early diagnosis,
 malignant ventricular arrhythmia,
 variants,
 idiopathic left ventricular systolic dysfunction,
 clinical practice keywords,
 decades,
 genetics,
 glucose metabolism,
 disease,
 cardiac arrhythmia,
 characterized,
 individuals,
 genetic research,
 baseline mva,
 longitudinal follow-up,
 relatives dna,
 goals,
 genetic factors,
 diffusely,
 polygenic risk score,
 myocardial lesion,
 targeted sequencing,
 left ventricular non‐compaction cardiomyopathy,
 proband,
 women,
 hf,
 heart failure,
 scrna-seq,
 risk,
 no significant,
 systolic heart failure,
 genes,
 heart failure,
 published,
 lvef,
 geneticists,
 primary end point,
 genetic variants,
 cellular cluster,
 complicates,
 patients,
 family health outcomes,
 single-cell resolution,
 non‐a‐band ttntv,
 conditions,
 dilated cardiomyopathy,
 arvc supplementary,
 arrhythmogenic right ventricular cardiomyopathy,
 adult,
 arvc,
 genes,
 quantify,
 lpl,
 ventricular tachyarrhythmias,
 functional,
 heart failure,
 composite,
 ttntv,
 gwas,
 healthy,
 genetic variant,
 diagnosed,
 serum-based samples,
 genome-wide significance,
 heritability,
 study,
 contemporary,
 relevance,
 men,
 accurate,
 dilated cardiomyopathy,
 phenotypes,
 hazard ratio,
 individuals,
 baseline,
 progression,
 cardiomyopathy,
 mva,
 therapeutic effects,
 targets,
 family lineage,
 carriers,
 carriage,
 environmental,
 mendelian cardiomyopathy genes,
 nlrp3,
 methods,
 genetic variation,
 titin,
 analyzed,
 eshf,
 findings,
 dilated cardiomyopathy,
 rare,
 increased,
 studies,
 cellular developmental trajectories,
 patients,
 expressed,
 global,
 genetic variants,
 genome-wide association studies,
 increase,
 electrocardiogram echocardiogram,
 patients,
 years,
 lvnc,
 hcm,
 associated with,
 associated with,
 arvc,
 cardiomyopathy,
 patients,
 relevant,
 ventricular arrhythmia,
 reduced,
 scrna-seq,
 data,
 cohort,
 idiopathic left ventricular systolic dysfunction,
 variants,
 pathways,
 etiological,
 characteristics,
 heart failure,
 risk,
 functional impact,
 0-fold,
 arvc,
 cardiac function,
 identified,
 cardiac muscle nerve,
 associated with,
 rare,
 single-cell data,
 sex,
 patients,
 cvd,
 integrative analysis,
 pharmacological intervention,
 prevalence analysis,
 scale,
 patients,
 baseline,
 mutation analysis,
 individuals,
 specific,
 atrial fibrillation,
 high risk,
 women,
 gipr,
 affecting,
 hf‐related death heart transplantation,
 patients,
 complex trait,
 polygenic component,
 induce,
 cluster annotation,
 comprehensive,
 male,
 cardiomyopathies,
 encoding,
 age,
 high risk,
 review,
 cardiologists,
 primary end point,
 genome,
 right ventricular dilation,
 expression,
 death,
 systolic heart failure,
 mybpc3 bag3,
 development,
 risk,
 blood,
 dcm,
 study,
 end-stage,
 patients,
 heritability,
 variants,
 death,
 femalerbm20variant carriers,
 lvnc,
 bag3,
 dcm,
 genetic cause,
 intended,
 heritability,
 variants,
 variant,
 groups,
 western blot,
 ttntv,
 lvnc baseline,
 heart failure,
 coding variants,
 pathogenic,
 genetic knowledge,
 genomics,
 proband,
 lvnc,
 mva,
 perturbations,
 normal controls,
 relevance,
 abnormally,
 data,
 probands,
 biobanks,
 men,
 confidence interval,
 variants,
 left ventricular noncompaction cardiomyopathy,
 potential,
 myocardium,
 dilated cardiomyopathy,
 vascular tissues,
 functional,
 proband,
 risk,
 cardiomyopathies,
 events,
 carriers,
 variants,
 ttntv,
 arvc,
 variants,
 backgrounddilation,
 progress,
 collaboration,
 distribution,
 personalized treatment,
 dcm,
 variant,
 unmet,
 sanger sequence,
 myocyte,
 patients,
 cvds,
 rare,
 mutations,
 dcm,
 phenotype,
 ttntv,
 hf,
 right ventricular change,
 myh6,
 patients,
 rbm20lvsd,
 overlap,
 systolic heart failure,
 data,
 mendelian cardiomyopathy,
 volunteer,
 thatdsc2p k47rfs*2,
 improved,
 poor outcomes,
 complicating,
 no significant,
 mendelian]

In [ ]:
entities_base = perform_ner(df['abstract_updated'][1])

In [ ]:
entities_base

[('complex trait', 8, 10, 'ENTITY'),
 ('environmental', 12, 13, 'ENTITY'),
 ('genetic factors', 14, 16, 'ENTITY'),
 ('individuals', 21, 22, 'ENTITY'),
 ('genetics', 25, 26, 'ENTITY'),
 ('mendelian', 32, 33, 'ENTITY'),
 ('disease', 35, 36, 'ENTITY'),
 ('genetic variants', 38, 40, 'ENTITY'),
 ('familial cardiomyopathies', 44, 46, 'ENTITY'),
 ('genome-wide association studies', 48, 51, 'ENTITY'),
 ('gwas', 52, 53, 'ENTITY'),
 ('genetic variants', 58, 60, 'ENTITY'),
 ('associated with', 60, 62, 'ENTITY'),
 ('risk', 62, 63, 'ENTITY'),
 ('genetic variants', 70, 72, 'ENTITY'),
 ('allele-frequency spectrum', 74, 76, 'ENTITY'),
 ('characterized', 78, 79, 'ENTITY'),
 ('results', 83, 84, 'ENTITY'),
 ('common-', 85, 86, 'ENTITY'),
 ('rare-variant association studies', 87, 90, 'ENTITY'),
 ('heart failure', 92, 94, 'ENTITY'),
 ('methods', 97, 98, 'ENTITY'),
 ('quantify', 99, 100, 'ENTITY'),
 ('heritability', 101, 102, 'ENTITY'),
 ('classes', 107, 108, 'ENTITY'),
 ('genetic variation', 109, 111, 'ENTITY'),
 ('gwas', 113, 114, 'ENTITY'),
 ('data', 114, 115, 'ENTITY'),
 ('multiple', 116, 117, 'ENTITY'),
 ('populations', 117, 118, 'ENTITY'),
 ('individuals', 121, 122, 'ENTITY'),
 ('risk loci', 131, 133, 'ENTITY'),
 ('genome-wide significance', 134, 136, 'ENTITY'),
 ('signals', 143, 144, 'ENTITY'),
 ('common-variant loci', 147, 149, 'ENTITY'),
 ('coding variants', 150, 152, 'ENTITY'),
 ('mendelian cardiomyopathy genes', 153, 156, 'ENTITY'),
 ('mybpc3 bag3', 157, 159, 'ENTITY'),
 ('regulators', 163, 164, 'ENTITY'),
 ('lpl', 167, 168, 'ENTITY'),
 ('glucose metabolism', 170, 172, 'ENTITY'),
 ('gipr', 173, 174, 'ENTITY'),
 ('cardiac muscle nerve', 180, 183, 'ENTITY'),
 ('vascular tissues', 184, 186, 'ENTITY'),
 ('myocyte', 189, 190, 'ENTITY'),
 ('adipocyte', 191, 192, 'ENTITY'),
 ('cell types', 192, 194, 'ENTITY'),
 ('gene burden studies', 194, 197, 'ENTITY'),
 ('biobanks', 199, 200, 'ENTITY'),
 ('individuals', 208, 209, 'ENTITY'),
 ('exome-wide significant', 216, 218, 'ENTITY'),
 ('associations', 226, 227, 'ENTITY'),
 ('hf', 228, 229, 'ENTITY'),
 ('rare', 230, 231, 'ENTITY'),
 ('loss-of-function', 232, 233, 'ENTITY'),
 ('plof', 234, 235, 'ENTITY'),
 ('variants', 236, 237, 'ENTITY'),
 ('mybpc3 flnc', 238, 240, 'ENTITY'),
 ('bag3', 241, 242, 'ENTITY'),
 ('burden', 243, 244, 'ENTITY'),
 ('heritability', 244, 245, 'ENTITY'),
 ('rare', 246, 247, 'ENTITY'),
 ('coding variants', 247, 249, 'ENTITY'),
 ('mendelian cardiomyopathy', 269, 271, 'ENTITY'),
 ('heritability', 276, 277, 'ENTITY'),
 ('variants', 280, 281, 'ENTITY'),
 ('diffusely', 296, 297, 'ENTITY'),
 ('spread', 297, 298, 'ENTITY'),
 ('genome', 300, 301, 'ENTITY'),
 ('common-variant background', 305, 307, 'ENTITY'),
 ('polygenic risk score', 312, 315, 'ENTITY'),
 ('prs', 316, 317, 'ENTITY'),
 ('modifies', 319, 320, 'ENTITY'),
 ('risk', 321, 322, 'ENTITY'),
 ('hf', 323, 324, 'ENTITY'),
 ('carriers', 325, 326, 'ENTITY'),
 ('pathogenic', 327, 328, 'ENTITY'),
 ('truncating', 328, 329, 'ENTITY'),
 ('variants', 329, 330, 'ENTITY'),
 ('mendelian cardiomyopathy', 332, 334, 'ENTITY'),
 ('gene ttn', 334, 336, 'ENTITY'),
 ('findings', 337, 338, 'ENTITY'),
 ('polygenic component', 341, 343, 'ENTITY'),
 ('clinical', 352, 353, 'ENTITY'),
 ('genetic testing', 353, 355, 'ENTITY')]

In [ ]:
relations = extract_relations(df['abstract_updated'][1], entities_base)

In [ ]:
print("Relations:", relations)

Relations: [('complex trait', 'studied', 'characterized'), ('genetics', 'studied', 'characterized'), ('genetic variants', 'linked', 'familial cardiomyopathies'), ('genome-wide association studies', 'identified', 'genetic variants'), ('signals', 'include', 'coding variants'), ('common-variant background', 'modifies', 'risk'), ('findings', 'suggest', 'polygenic component')]

In [ ]:
for subject, relation, object_ in relations:
    print(f"({subject}, {relation}, {object_})")

(complex trait, studied, characterized)
(genetics, studied, characterized)
(genetic variants, linked, familial cardiomyopathies)
(genome-wide association studies, identified, genetic variants)
(signals, include, coding variants)
(common-variant background, modifies, risk)
(findings, suggest, polygenic component)

##### Experimental section

In [ ]:
test_abstracts = df['abstract_updated'][:5]

In [ ]:
test_abstracts

0      cardiovascular disease (cvd) is caused by a ...
1      heart failure (hf) is a complex trait influe...
2      backgrounddilation may be the first right ve...
3      backgroundthe left ventricular noncompaction...
4      backgroundtitin‐truncating variants (ttntv) ...
Name: abstract_updated, dtype: object

In [ ]:
test_abstracts[0]

'  cardiovascular disease (cvd) is caused by a multitude of complex and largely heritable conditions identifying key genes and understanding their susceptibility to cvd in the human genome can assist in early diagnosis and personalized treatment of the relevant patients heart failure (hf) is among those cvd phenotypes that has a high rate of mortality in this study we investigated genes primarily associated with hf and other cvds achieving the goals of this study we built a cohort of thirty-five consented patients and sequenced their serum-based samples we have generated and processed whole genome sequence (wgs) data and performed functional mutation splice variant distribution and divergence analysis to understand the relationships between each mutation type and its impact our variant and prevalence analysis foundflna cst3 lgals3 andhba1linked to many enrichment pathways functional mutation analysis uncoveredace mme lgals3 nr3c2 pik3c2a cald1 tek andtrpv1to be notable and potentially significant genes we discovered intron 5ʹ flank 3ʹ utr and 3ʹ flank mutations to be the most common among hf and other cvd genes missense mutations were less common among hf and other cvd genes but had more of a functional impact we reported hba1 fadd nppc adrb2 adbr1 myh6 and pln to be consequential based on our divergence analysis subject terms: cardiovascular diseases genomics'

In [ ]:
doc = nlp(test_abstracts[1])

In [ ]:
NER_base_spacy = [entity for entity in doc.ents]

In [ ]:
NER_base_spacy

[Heart failure,
 HF,
 complex trait,
 environmental,
 genetic factors,
 individuals,
 genetics,
 HF,
 Mendelian,
 disease,
 genetic variants,
 familial cardiomyopathies,
 genome-wide association studies,
 GWAS,
 genetic variants,
 associated with,
 risk,
 HF,
 genetic variants,
 allele-frequency spectrum,
 characterized,
 results,
 common-,
 rare-variant association studies,
 heart failure,
 methods,
 quantify,
 heritability,
 HF,
 classes,
 genetic variation,
 GWAS,
 data,
 multiple,
 populations,
 individuals,
 HF,
 risk loci,
 genome-wide significance,
 Signals,
 common-variant loci,
 coding variants,
 Mendelian cardiomyopathy genes,
 MYBPC3,BAG3,
 regulators,
 LPL,
 glucose metabolism,
 GIPR,
 GLP1R,
 cardiac,
 muscle,
 nerve,
 vascular tissues,
 myocyte,
 adipocyte,
 cell types,
 Gene burden studies,
 biobanks,
 PMBB,
 UKB,
 AOU,
 individuals,
 HF,
 exome-wide significant,
 associations,
 HF,
 rare,
 loss-of-function,
 pLoF,
 variants,
 inTTN,
 MYBPC3,FLNC,
 BAG3.Total,
 burden,
 heritability,
 rare,
 coding variants,
 CI,
 Mendelian cardiomyopathy,
 heritability,
 variants,
 CI,
 diffusely,
 spread,
 genome,
 common-variant background,
 polygenic risk score,
 PRS,
 modifies,
 risk,
 HF,
 carriers,
 pathogenic,
 truncating,
 variants,
 Mendelian cardiomyopathy,
 TTN,
 findings,
 polygenic component,
 HF,
 clinical,
 genetic testing]

In [ ]:
displacy_image = displacy.render(doc, jupyter = True, style = 'ent')

In [ ]:
[(ent.text, ent.label_) for ent in doc.ents]

[('Heart failure', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('complex trait', 'ENTITY'),
 ('environmental', 'ENTITY'),
 ('genetic factors', 'ENTITY'),
 ('individuals', 'ENTITY'),
 ('genetics', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('Mendelian', 'ENTITY'),
 ('disease', 'ENTITY'),
 ('genetic variants', 'ENTITY'),
 ('familial cardiomyopathies', 'ENTITY'),
 ('genome-wide association studies', 'ENTITY'),
 ('GWAS', 'ENTITY'),
 ('genetic variants', 'ENTITY'),
 ('associated with', 'ENTITY'),
 ('risk', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('genetic variants', 'ENTITY'),
 ('allele-frequency spectrum', 'ENTITY'),
 ('characterized', 'ENTITY'),
 ('results', 'ENTITY'),
 ('common-', 'ENTITY'),
 ('rare-variant association studies', 'ENTITY'),
 ('heart failure', 'ENTITY'),
 ('methods', 'ENTITY'),
 ('quantify', 'ENTITY'),
 ('heritability', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('classes', 'ENTITY'),
 ('genetic variation', 'ENTITY'),
 ('GWAS', 'ENTITY'),
 ('data', 'ENTITY'),
 ('multiple', 'ENTITY'),
 ('populations', 'ENTITY'),
 ('individuals', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('risk loci', 'ENTITY'),
 ('genome-wide significance', 'ENTITY'),
 ('Signals', 'ENTITY'),
 ('common-variant loci', 'ENTITY'),
 ('coding variants', 'ENTITY'),
 ('Mendelian cardiomyopathy genes', 'ENTITY'),
 ('MYBPC3,BAG3', 'ENTITY'),
 ('regulators', 'ENTITY'),
 ('LPL', 'ENTITY'),
 ('glucose metabolism', 'ENTITY'),
 ('GIPR', 'ENTITY'),
 ('GLP1R', 'ENTITY'),
 ('cardiac', 'ENTITY'),
 ('muscle', 'ENTITY'),
 ('nerve', 'ENTITY'),
 ('vascular tissues', 'ENTITY'),
 ('myocyte', 'ENTITY'),
 ('adipocyte', 'ENTITY'),
 ('cell types', 'ENTITY'),
 ('Gene burden studies', 'ENTITY'),
 ('biobanks', 'ENTITY'),
 ('PMBB', 'ENTITY'),
 ('UKB', 'ENTITY'),
 ('AOU', 'ENTITY'),
 ('individuals', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('exome-wide significant', 'ENTITY'),
 ('associations', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('rare', 'ENTITY'),
 ('loss-of-function', 'ENTITY'),
 ('pLoF', 'ENTITY'),
 ('variants', 'ENTITY'),
 ('inTTN', 'ENTITY'),
 ('MYBPC3,FLNC', 'ENTITY'),
 ('BAG3.Total', 'ENTITY'),
 ('burden', 'ENTITY'),
 ('heritability', 'ENTITY'),
 ('rare', 'ENTITY'),
 ('coding variants', 'ENTITY'),
 ('CI', 'ENTITY'),
 ('Mendelian cardiomyopathy', 'ENTITY'),
 ('heritability', 'ENTITY'),
 ('variants', 'ENTITY'),
 ('CI', 'ENTITY'),
 ('diffusely', 'ENTITY'),
 ('spread', 'ENTITY'),
 ('genome', 'ENTITY'),
 ('common-variant background', 'ENTITY'),
 ('polygenic risk score', 'ENTITY'),
 ('PRS', 'ENTITY'),
 ('modifies', 'ENTITY'),
 ('risk', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('carriers', 'ENTITY'),
 ('pathogenic', 'ENTITY'),
 ('truncating', 'ENTITY'),
 ('variants', 'ENTITY'),
 ('Mendelian cardiomyopathy', 'ENTITY'),
 ('TTN', 'ENTITY'),
 ('findings', 'ENTITY'),
 ('polygenic component', 'ENTITY'),
 ('HF', 'ENTITY'),
 ('clinical', 'ENTITY'),
 ('genetic testing', 'ENTITY')]

In [ ]:
[ent.label_ for ent in doc.ents]

['ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY',
 'ENTITY']

#### Performing keyword extraction KeyBERT

<p> Model details <br>
sciBERT - allenai/scibert_scivocab_uncased <br>
BioDistilBERT - nlpie/bio-distilbert-uncased <br>
BioLinkBERT - https://huggingface.co/michiyasunaga/BioLinkBERT-large <br>
Polyglot NER - rmyeid/polyglot_ner <br>
</p>

<b> None of the models listed above run with sentence transformer. Using base model - All-MiniLM-L6-V2

distilbert_model = SentenceTransformer("nlpie/bio-distilbert-uncased")
<h5> WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name nlpie/bio-distilbert-uncased. Creating a new one with mean pooling.</h5>

kw_model = KeyBERT(model=distilbert_model)
keywords = kw_model.extract_keywords(test_abstracts[1])

In [ ]:
base_model = SentenceTransformer("all-MiniLM-L6-v2") # Uses All-MiniLM-L6-v2

In [ ]:
kw_base = KeyBERT(model=base_model)

In [ ]:
base_keywords = []

In [ ]:
for abstract in df['abstract_updated']:
  print(f'Document {index}')
  try:
    doc_embeddings, word_embeddings = kw_base.extract_embeddings(abstract)
    keywords = kw_base.extract_keywords(abstract, doc_embeddings=doc_embeddings, word_embeddings=word_embeddings)
    base_keywords.extend(keywords)
  except:
    continue

In [ ]:
base_keywords

#### Using sciSpaCy NER models - DOES NOT WORK - DO NOT USE - TOO NICHE

In [ ]:
test_str = """
Cardiovascular disease (CVD) is caused by a multitude of complex and largely heritable conditions.
Identifying key genes and understanding their susceptibility to CVD in the human genome can assist in early diagnosis and personalized treatment of the relevant patients.
Heart failure (HF) is among those CVD phenotypes that has a high rate of mortality.
In this study, we investigated genes primarily associated with HF and other CVDs.
Achieving the goals of this study, we built a cohort of thirty-five consented patients, and sequenced their serum-based samples.
We have generated and processed whole genome sequence (WGS) data, and performed functional mutation, splice, variant distribution, and divergence analysis to understand the relationships between each mutation type and its impact.
Our variant and prevalence analysis foundFLNA, CST3, LGALS3, and HBA1 linked to many enrichment pathways.
Functional mutation analysis uncovered ACE,MME,LGALS3,NR3C2,PIK3C2A,CALD1,TEK, and TRPV1 to be notable and potentially significant genes.
We discovered intron, 5ʹ Flank, 3ʹ UTR, and 3ʹ Flank mutations to be the most common among HF and other CVD genes.
Missense mutations were less common among HF and other CVD genes but had more of a functional impact.
We reported HBA1,FADD,NPPC,ADRB2,ADBR1,MYH6, and PLN to be consequential based on our divergence analysis.
Subject terms: Cardiovascular diseases, Genomics.
"""

In [ ]:
nlp_jnlpba_ner = spacy.load('en_ner_jnlpba_md')

In [ ]:
doc2 = nlp_jnlpba_ner(test_abstracts[1])
#doc2 = nlp_jnlpba_ner(test_str)

In [ ]:
NER_jnlpba_spacy = list(set([entity for entity in doc2.ents]))

In [ ]:
NER_jnlpba_spacy

[LPL,
 HF,
 lipoprotein,
 Mendelian cardiomyopathy genes,
 common-variant loci,
 coding variants,
 adipocyte,
 HF,
 HF,
 Mendelian cardiomyopathy gene TTN,
 Mendelian cardiomyopathy genes]

In [ ]:
[ent.label_ for ent in doc2.ents]

['CELL_TYPE',
 'CELL_TYPE',
 'DNA',
 'DNA',
 'DNA',
 'PROTEIN',
 'PROTEIN',
 'CELL_TYPE',
 'DNA',
 'DNA',
 'CELL_TYPE']

In [ ]:
displacy_image = displacy.render(doc2, jupyter = True, style = 'ent')

#### Using SciBERT for NER - Requires fine-tuning. Pretrained base model is incompetent

In [ ]:
model_name = "allenai/scibert_scivocab_uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

Some weights of BertForTokenClassification were not initialized from the model checkpoint at allenai/scibert_scivocab_uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
ner_pipeline = pipeline("ner",model = model,tokenizer = tokenizer)

In [ ]:
results = ner_pipeline(test_abstracts[1])

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

In [ ]:
len(test_abstracts[1])

2190

In [ ]:
len(results)

469

In [ ]:
scores = []
words = []
for result in results:
  scores.append(result['score'])
  words.append(result['word'])

In [ ]:
extracted_entities_df = pd.DataFrame.from_dict({'Word':words,'Score':scores})

In [ ]:
extracted_entities_df = extracted_entities_df.sort_values(by=['Score'],ascending=False)

In [ ]:
extracted_entities_df.to_csv('NER_Scibert.csv')

In [ ]:
print(results)

[{'entity': 'LABEL_1', 'score': 0.67813975, 'index': 1, 'word': 'heart', 'start': 2, 'end': 7}, {'entity': 'LABEL_1', 'score': 0.55739737, 'index': 2, 'word': 'failure', 'start': 8, 'end': 15}, {'entity': 'LABEL_1', 'score': 0.7890733, 'index': 3, 'word': '(', 'start': 16, 'end': 17}, {'entity': 'LABEL_1', 'score': 0.5935512, 'index': 4, 'word': 'hf', 'start': 17, 'end': 19}, {'entity': 'LABEL_1', 'score': 0.8056588, 'index': 5, 'word': ')', 'start': 19, 'end': 20}, {'entity': 'LABEL_1', 'score': 0.6938837, 'index': 6, 'word': 'is', 'start': 21, 'end': 23}, {'entity': 'LABEL_1', 'score': 0.62220496, 'index': 7, 'word': 'a', 'start': 24, 'end': 25}, {'entity': 'LABEL_1', 'score': 0.57755923, 'index': 8, 'word': 'complex', 'start': 26, 'end': 33}, {'entity': 'LABEL_1', 'score': 0.7040267, 'index': 9, 'word': 'trait', 'start': 34, 'end': 39}, {'entity': 'LABEL_1', 'score': 0.6892292, 'index': 10, 'word': ',', 'start': 39, 'end': 40}, {'entity': 'LABEL_1', 'score': 0.7136398, 'index': 11, 'word': 'influenced', 'start': 41, 'end': 51}, {'entity': 'LABEL_1', 'score': 0.6161826, 'index': 12, 'word': 'by', 'start': 52, 'end': 54}, {'entity': 'LABEL_0', 'score': 0.5381962, 'index': 13, 'word': 'environmental', 'start': 55, 'end': 68}, {'entity': 'LABEL_0', 'score': 0.5122348, 'index': 14, 'word': 'and', 'start': 69, 'end': 72}, {'entity': 'LABEL_1', 'score': 0.5621851, 'index': 15, 'word': 'genetic', 'start': 73, 'end': 80}, {'entity': 'LABEL_0', 'score': 0.51200986, 'index': 16, 'word': 'factors', 'start': 81, 'end': 88}, {'entity': 'LABEL_1', 'score': 0.7195728, 'index': 17, 'word': ',', 'start': 88, 'end': 89}, {'entity': 'LABEL_1', 'score': 0.72078156, 'index': 18, 'word': 'that', 'start': 90, 'end': 94}, {'entity': 'LABEL_1', 'score': 0.5373208, 'index': 19, 'word': 'affects', 'start': 95, 'end': 102}, {'entity': 'LABEL_0', 'score': 0.52950007, 'index': 20, 'word': 'over', 'start': 103, 'end': 107}, {'entity': 'LABEL_0', 'score': 0.5591849, 'index': 21, 'word': '30', 'start': 108, 'end': 110}, {'entity': 'LABEL_0', 'score': 0.5623022, 'index': 22, 'word': 'million', 'start': 111, 'end': 118}, {'entity': 'LABEL_1', 'score': 0.5444149, 'index': 23, 'word': 'individuals', 'start': 119, 'end': 130}, {'entity': 'LABEL_1', 'score': 0.6569419, 'index': 24, 'word': 'worldwide', 'start': 131, 'end': 140}, {'entity': 'LABEL_0', 'score': 0.5240704, 'index': 25, 'word': '.', 'start': 140, 'end': 141}, {'entity': 'LABEL_1', 'score': 0.6083411, 'index': 26, 'word': 'historically', 'start': 142, 'end': 154}, {'entity': 'LABEL_1', 'score': 0.786319, 'index': 27, 'word': ',', 'start': 154, 'end': 155}, {'entity': 'LABEL_1', 'score': 0.8167403, 'index': 28, 'word': 'the', 'start': 156, 'end': 159}, {'entity': 'LABEL_1', 'score': 0.75412077, 'index': 29, 'word': 'genetics', 'start': 160, 'end': 168}, {'entity': 'LABEL_1', 'score': 0.5412588, 'index': 30, 'word': 'of', 'start': 169, 'end': 171}, {'entity': 'LABEL_1', 'score': 0.73905706, 'index': 31, 'word': 'hf', 'start': 172, 'end': 174}, {'entity': 'LABEL_1', 'score': 0.74282587, 'index': 32, 'word': 'have', 'start': 175, 'end': 179}, {'entity': 'LABEL_1', 'score': 0.77429545, 'index': 33, 'word': 'been', 'start': 180, 'end': 184}, {'entity': 'LABEL_1', 'score': 0.8205842, 'index': 34, 'word': 'studied', 'start': 185, 'end': 192}, {'entity': 'LABEL_1', 'score': 0.8363921, 'index': 35, 'word': 'in', 'start': 193, 'end': 195}, {'entity': 'LABEL_1', 'score': 0.70250225, 'index': 36, 'word': 'mend', 'start': 196, 'end': 200}, {'entity': 'LABEL_1', 'score': 0.68021226, 'index': 37, 'word': '##elian', 'start': 200, 'end': 205}, {'entity': 'LABEL_1', 'score': 0.747839, 'index': 38, 'word': 'forms', 'start': 206, 'end': 211}, {'entity': 'LABEL_0', 'score': 0.51698774, 'index': 39, 'word': 'of', 'start': 212, 'end': 214}, {'entity': 'LABEL_1', 'score': 0.74465907, 'index': 40, 'word': 'disease', 'start': 215, 'end': 222}, {'entity': 'LABEL_1', 'score': 0.759869, 'index': 41, 'word': ',', 'start': 222, 'end': 223}, {'entity': 'LABEL_1', 'score': 0.75369304, 'index': 42, 'word': 'where', 'start': 224, 'end': 229}, {'entity': 'LABEL_1', 'score': 0.5868499, 'index': 43, 'word': 'rare', 'start': 230, 'end': 234}, {'entity': 'LABEL_1', 'score': 0.8245303, 'index': 44, 'word': 'genetic', 'start': 235, 'end': 242}, {'entity': 'LABEL_1', 'score': 0.71442956, 'index': 45, 'word': 'variants', 'start': 243, 'end': 251}, {'entity': 'LABEL_1', 'score': 0.71074057, 'index': 46, 'word': 'have', 'start': 252, 'end': 256}, {'entity': 'LABEL_1', 'score': 0.75957, 'index': 47, 'word': 'been', 'start': 257, 'end': 261}, {'entity': 'LABEL_1', 'score': 0.60801, 'index': 48, 'word': 'linked', 'start': 262, 'end': 268}, {'entity': 'LABEL_1', 'score': 0.75513643, 'index': 49, 'word': 'to', 'start': 269, 'end': 271}, {'entity': 'LABEL_1', 'score': 0.52901316, 'index': 50, 'word': 'familial', 'start': 272, 'end': 280}, {'entity': 'LABEL_0', 'score': 0.53144324, 'index': 51, 'word': 'cardiomy', 'start': 281, 'end': 289}, {'entity': 'LABEL_1', 'score': 0.60226893, 'index': 52, 'word': '##opathies', 'start': 289, 'end': 297}, {'entity': 'LABEL_0', 'score': 0.52915573, 'index': 53, 'word': '.', 'start': 297, 'end': 298}, {'entity': 'LABEL_1', 'score': 0.690834, 'index': 54, 'word': 'more', 'start': 299, 'end': 303}, {'entity': 'LABEL_1', 'score': 0.6947659, 'index': 55, 'word': 'recently', 'start': 304, 'end': 312}, {'entity': 'LABEL_1', 'score': 0.8325665, 'index': 56, 'word': ',', 'start': 312, 'end': 313}, {'entity': 'LABEL_1', 'score': 0.6528259, 'index': 57, 'word': 'genome', 'start': 314, 'end': 320}, {'entity': 'LABEL_1', 'score': 0.787376, 'index': 58, 'word': '-', 'start': 320, 'end': 321}, {'entity': 'LABEL_0', 'score': 0.6785704, 'index': 59, 'word': 'wide', 'start': 321, 'end': 325}, {'entity': 'LABEL_0', 'score': 0.52028537, 'index': 60, 'word': 'association', 'start': 326, 'end': 337}, {'entity': 'LABEL_1', 'score': 0.5625759, 'index': 61, 'word': 'studies', 'start': 338, 'end': 345}, {'entity': 'LABEL_1', 'score': 0.804344, 'index': 62, 'word': '(', 'start': 346, 'end': 347}, {'entity': 'LABEL_1', 'score': 0.711512, 'index': 63, 'word': 'gwas', 'start': 347, 'end': 351}, {'entity': 'LABEL_1', 'score': 0.82795274, 'index': 64, 'word': ')', 'start': 351, 'end': 352}, {'entity': 'LABEL_1', 'score': 0.76414025, 'index': 65, 'word': 'have', 'start': 353, 'end': 357}, {'entity': 'LABEL_1', 'score': 0.76607, 'index': 66, 'word': 'successfully', 'start': 358, 'end': 370}, {'entity': 'LABEL_1', 'score': 0.60034096, 'index': 67, 'word': 'identified', 'start': 371, 'end': 381}, {'entity': 'LABEL_1', 'score': 0.6880632, 'index': 68, 'word': 'common', 'start': 382, 'end': 388}, {'entity': 'LABEL_1', 'score': 0.8244221, 'index': 69, 'word': 'genetic', 'start': 389, 'end': 396}, {'entity': 'LABEL_1', 'score': 0.7245036, 'index': 70, 'word': 'variants', 'start': 397, 'end': 405}, {'entity': 'LABEL_0', 'score': 0.5275623, 'index': 71, 'word': 'associated', 'start': 406, 'end': 416}, {'entity': 'LABEL_1', 'score': 0.6414546, 'index': 72, 'word': 'with', 'start': 417, 'end': 421}, {'entity': 'LABEL_1', 'score': 0.5571019, 'index': 73, 'word': 'risk', 'start': 422, 'end': 426}, {'entity': 'LABEL_0', 'score': 0.6036149, 'index': 74, 'word': 'of', 'start': 427, 'end': 429}, {'entity': 'LABEL_1', 'score': 0.59774566, 'index': 75, 'word': 'hf', 'start': 430, 'end': 432}, {'entity': 'LABEL_0', 'score': 0.5317189, 'index': 76, 'word': '.', 'start': 432, 'end': 433}, {'entity': 'LABEL_1', 'score': 0.6619293, 'index': 77, 'word': 'however', 'start': 434, 'end': 441}, {'entity': 'LABEL_1', 'score': 0.7135799, 'index': 78, 'word': ',', 'start': 441, 'end': 442}, {'entity': 'LABEL_1', 'score': 0.6077184, 'index': 79, 'word': 'the', 'start': 443, 'end': 446}, {'entity': 'LABEL_1', 'score': 0.672283, 'index': 80, 'word': 'relative', 'start': 447, 'end': 455}, {'entity': 'LABEL_1', 'score': 0.73952585, 'index': 81, 'word': 'importance', 'start': 456, 'end': 466}, {'entity': 'LABEL_1', 'score': 0.62469673, 'index': 82, 'word': 'of', 'start': 467, 'end': 469}, {'entity': 'LABEL_1', 'score': 0.84688777, 'index': 83, 'word': 'genetic', 'start': 470, 'end': 477}, {'entity': 'LABEL_1', 'score': 0.7534829, 'index': 84, 'word': 'variants', 'start': 478, 'end': 486}, {'entity': 'LABEL_0', 'score': 0.5729, 'index': 85, 'word': 'across', 'start': 487, 'end': 493}, {'entity': 'LABEL_0', 'score': 0.5153302, 'index': 86, 'word': 'the', 'start': 494, 'end': 497}, {'entity': 'LABEL_1', 'score': 0.63610715, 'index': 87, 'word': 'allele', 'start': 498, 'end': 504}, {'entity': 'LABEL_1', 'score': 0.6605101, 'index': 88, 'word': '-', 'start': 504, 'end': 505}, {'entity': 'LABEL_1', 'score': 0.56062686, 'index': 89, 'word': 'frequency', 'start': 505, 'end': 514}, {'entity': 'LABEL_0', 'score': 0.61527336, 'index': 90, 'word': 'spectrum', 'start': 515, 'end': 523}, {'entity': 'LABEL_1', 'score': 0.5123317, 'index': 91, 'word': 'remains', 'start': 524, 'end': 531}, {'entity': 'LABEL_0', 'score': 0.57076806, 'index': 92, 'word': 'incomplete', 'start': 532, 'end': 542}, {'entity': 'LABEL_1', 'score': 0.5353801, 'index': 93, 'word': '##ly', 'start': 542, 'end': 544}, {'entity': 'LABEL_1', 'score': 0.57747114, 'index': 94, 'word': 'characterized', 'start': 545, 'end': 558}, {'entity': 'LABEL_0', 'score': 0.52451885, 'index': 95, 'word': '.', 'start': 558, 'end': 559}, {'entity': 'LABEL_1', 'score': 0.75274456, 'index': 96, 'word': 'here', 'start': 560, 'end': 564}, {'entity': 'LABEL_1', 'score': 0.7463081, 'index': 97, 'word': ',', 'start': 564, 'end': 565}, {'entity': 'LABEL_1', 'score': 0.7298373, 'index': 98, 'word': 'we', 'start': 566, 'end': 568}, {'entity': 'LABEL_1', 'score': 0.75971246, 'index': 99, 'word': 'report', 'start': 569, 'end': 575}, {'entity': 'LABEL_1', 'score': 0.6524911, 'index': 100, 'word': 'the', 'start': 576, 'end': 579}, {'entity': 'LABEL_1', 'score': 0.6502523, 'index': 101, 'word': 'results', 'start': 580, 'end': 587}, {'entity': 'LABEL_1', 'score': 0.52538437, 'index': 102, 'word': 'of', 'start': 588, 'end': 590}, {'entity': 'LABEL_1', 'score': 0.6452819, 'index': 103, 'word': 'common', 'start': 591, 'end': 597}, {'entity': 'LABEL_1', 'score': 0.6051782, 'index': 104, 'word': '-', 'start': 597, 'end': 598}, {'entity': 'LABEL_0', 'score': 0.5000881, 'index': 105, 'word': 'and', 'start': 599, 'end': 602}, {'entity': 'LABEL_0', 'score': 0.53477514, 'index': 106, 'word': 'rare', 'start': 603, 'end': 607}, {'entity': 'LABEL_1', 'score': 0.7414921, 'index': 107, 'word': '-', 'start': 607, 'end': 608}, {'entity': 'LABEL_1', 'score': 0.66009843, 'index': 108, 'word': 'variant', 'start': 608, 'end': 615}, {'entity': 'LABEL_1', 'score': 0.58125025, 'index': 109, 'word': 'association', 'start': 616, 'end': 627}, {'entity': 'LABEL_1', 'score': 0.61468065, 'index': 110, 'word': 'studies', 'start': 628, 'end': 635}, {'entity': 'LABEL_1', 'score': 0.6417113, 'index': 111, 'word': 'of', 'start': 636, 'end': 638}, {'entity': 'LABEL_0', 'score': 0.55636847, 'index': 112, 'word': 'all', 'start': 639, 'end': 642}, {'entity': 'LABEL_1', 'score': 0.74086994, 'index': 113, 'word': '-', 'start': 642, 'end': 643}, {'entity': 'LABEL_0', 'score': 0.5640173, 'index': 114, 'word': 'cause', 'start': 643, 'end': 648}, {'entity': 'LABEL_1', 'score': 0.6556996, 'index': 115, 'word': 'heart', 'start': 649, 'end': 654}, {'entity': 'LABEL_1', 'score': 0.6875391, 'index': 116, 'word': 'failure', 'start': 655, 'end': 662}, {'entity': 'LABEL_1', 'score': 0.8770963, 'index': 117, 'word': ',', 'start': 662, 'end': 663}, {'entity': 'LABEL_0', 'score': 0.5481696, 'index': 118, 'word': 'applying', 'start': 664, 'end': 672}, {'entity': 'LABEL_1', 'score': 0.74217916, 'index': 119, 'word': 'recently', 'start': 673, 'end': 681}, {'entity': 'LABEL_1', 'score': 0.5309737, 'index': 120, 'word': 'developed', 'start': 682, 'end': 691}, {'entity': 'LABEL_1', 'score': 0.61821127, 'index': 121, 'word': 'methods', 'start': 692, 'end': 699}, {'entity': 'LABEL_1', 'score': 0.7788968, 'index': 122, 'word': 'to', 'start': 700, 'end': 702}, {'entity': 'LABEL_1', 'score': 0.6934441, 'index': 123, 'word': 'quantify', 'start': 703, 'end': 711}, {'entity': 'LABEL_1', 'score': 0.6650034, 'index': 124, 'word': 'the', 'start': 712, 'end': 715}, {'entity': 'LABEL_1', 'score': 0.6048612, 'index': 125, 'word': 'heritability', 'start': 716, 'end': 728}, {'entity': 'LABEL_1', 'score': 0.51173335, 'index': 126, 'word': 'of', 'start': 729, 'end': 731}, {'entity': 'LABEL_1', 'score': 0.7173618, 'index': 127, 'word': 'hf', 'start': 732, 'end': 734}, {'entity': 'LABEL_1', 'score': 0.6173949, 'index': 128, 'word': 'attributable', 'start': 735, 'end': 747}, {'entity': 'LABEL_1', 'score': 0.8374978, 'index': 129, 'word': 'to', 'start': 748, 'end': 750}, {'entity': 'LABEL_1', 'score': 0.62717617, 'index': 130, 'word': 'different', 'start': 751, 'end': 760}, {'entity': 'LABEL_1', 'score': 0.67516667, 'index': 131, 'word': 'classes', 'start': 761, 'end': 768}, {'entity': 'LABEL_1', 'score': 0.55343765, 'index': 132, 'word': 'of', 'start': 769, 'end': 771}, {'entity': 'LABEL_1', 'score': 0.7916042, 'index': 133, 'word': 'genetic', 'start': 772, 'end': 779}, {'entity': 'LABEL_1', 'score': 0.7246928, 'index': 134, 'word': 'variation', 'start': 780, 'end': 789}, {'entity': 'LABEL_0', 'score': 0.5279088, 'index': 135, 'word': '.', 'start': 789, 'end': 790}, {'entity': 'LABEL_1', 'score': 0.7479266, 'index': 136, 'word': 'we', 'start': 791, 'end': 793}, {'entity': 'LABEL_1', 'score': 0.6368476, 'index': 137, 'word': 'combine', 'start': 794, 'end': 801}, {'entity': 'LABEL_1', 'score': 0.6556896, 'index': 138, 'word': 'gwas', 'start': 802, 'end': 806}, {'entity': 'LABEL_1', 'score': 0.62374115, 'index': 139, 'word': 'data', 'start': 807, 'end': 811}, {'entity': 'LABEL_0', 'score': 0.6130911, 'index': 140, 'word': 'across', 'start': 812, 'end': 818}, {'entity': 'LABEL_0', 'score': 0.73478794, 'index': 141, 'word': 'multiple', 'start': 819, 'end': 827}, {'entity': 'LABEL_1', 'score': 0.5001804, 'index': 142, 'word': 'populations', 'start': 828, 'end': 839}, {'entity': 'LABEL_0', 'score': 0.65015715, 'index': 143, 'word': 'including', 'start': 840, 'end': 849}, {'entity': 'LABEL_0', 'score': 0.6806086, 'index': 144, 'word': '207', 'start': 850, 'end': 853}, {'entity': 'LABEL_1', 'score': 0.6292013, 'index': 145, 'word': ',', 'start': 853, 'end': 854}, {'entity': 'LABEL_0', 'score': 0.75857145, 'index': 146, 'word': '34', 'start': 854, 'end': 856}, {'entity': 'LABEL_1', 'score': 0.5200537, 'index': 147, 'word': '##6', 'start': 856, 'end': 857}, {'entity': 'LABEL_0', 'score': 0.51667786, 'index': 148, 'word': 'individuals', 'start': 858, 'end': 869}, {'entity': 'LABEL_1', 'score': 0.5511791, 'index': 149, 'word': 'with', 'start': 870, 'end': 874}, {'entity': 'LABEL_1', 'score': 0.5162152, 'index': 150, 'word': 'hf', 'start': 875, 'end': 877}, {'entity': 'LABEL_1', 'score': 0.6069107, 'index': 151, 'word': 'and', 'start': 878, 'end': 881}, {'entity': 'LABEL_0', 'score': 0.64068764, 'index': 152, 'word': '2', 'start': 882, 'end': 883}, {'entity': 'LABEL_0', 'score': 0.6226095, 'index': 153, 'word': ',', 'start': 883, 'end': 884}, {'entity': 'LABEL_0', 'score': 0.79715806, 'index': 154, 'word': '151', 'start': 884, 'end': 887}, {'entity': 'LABEL_1', 'score': 0.6666438, 'index': 155, 'word': ',', 'start': 887, 'end': 888}, {'entity': 'LABEL_0', 'score': 0.64319164, 'index': 156, 'word': '210', 'start': 888, 'end': 891}, {'entity': 'LABEL_1', 'score': 0.58214355, 'index': 157, 'word': 'without', 'start': 892, 'end': 899}, {'entity': 'LABEL_1', 'score': 0.8663475, 'index': 158, 'word': ',', 'start': 899, 'end': 900}, {'entity': 'LABEL_1', 'score': 0.58966726, 'index': 159, 'word': 'identifying', 'start': 901, 'end': 912}, {'entity': 'LABEL_1', 'score': 0.6129667, 'index': 160, 'word': '176', 'start': 913, 'end': 916}, {'entity': 'LABEL_1', 'score': 0.5123111, 'index': 161, 'word': 'risk', 'start': 917, 'end': 921}, {'entity': 'LABEL_1', 'score': 0.6159915, 'index': 162, 'word': 'loci', 'start': 922, 'end': 926}, {'entity': 'LABEL_1', 'score': 0.503617, 'index': 163, 'word': 'at', 'start': 927, 'end': 929}, {'entity': 'LABEL_0', 'score': 0.5421727, 'index': 164, 'word': 'genome', 'start': 930, 'end': 936}, {'entity': 'LABEL_1', 'score': 0.7614786, 'index': 165, 'word': '-', 'start': 936, 'end': 937}, {'entity': 'LABEL_0', 'score': 0.61531043, 'index': 166, 'word': 'wide', 'start': 937, 'end': 941}, {'entity': 'LABEL_1', 'score': 0.7949366, 'index': 167, 'word': 'significance', 'start': 942, 'end': 954}, {'entity': 'LABEL_1', 'score': 0.7436885, 'index': 168, 'word': '(', 'start': 955, 'end': 956}, {'entity': 'LABEL_1', 'score': 0.8060936, 'index': 169, 'word': 'p', 'start': 956, 'end': 957}, {'entity': 'LABEL_1', 'score': 0.68902546, 'index': 170, 'word': '<', 'start': 958, 'end': 959}, {'entity': 'LABEL_1', 'score': 0.61778134, 'index': 171, 'word': '5', 'start': 960, 'end': 961}, {'entity': 'LABEL_0', 'score': 0.50367874, 'index': 172, 'word': '##×10', 'start': 961, 'end': 964}, {'entity': 'LABEL_0', 'score': 0.65098554, 'index': 173, 'word': '##−', 'start': 964, 'end': 965}, {'entity': 'LABEL_1', 'score': 0.56641865, 'index': 174, 'word': '##8', 'start': 965, 'end': 966}, {'entity': 'LABEL_1', 'score': 0.6890394, 'index': 175, 'word': ')', 'start': 966, 'end': 967}, {'entity': 'LABEL_0', 'score': 0.535719, 'index': 176, 'word': '.', 'start': 967, 'end': 968}, {'entity': 'LABEL_1', 'score': 0.7330925, 'index': 177, 'word': 'signals', 'start': 969, 'end': 976}, {'entity': 'LABEL_1', 'score': 0.72489667, 'index': 178, 'word': 'at', 'start': 977, 'end': 979}, {'entity': 'LABEL_1', 'score': 0.80968976, 'index': 179, 'word': 'newly', 'start': 980, 'end': 985}, {'entity': 'LABEL_1', 'score': 0.5127338, 'index': 180, 'word': 'identified', 'start': 986, 'end': 996}, {'entity': 'LABEL_1', 'score': 0.75739735, 'index': 181, 'word': 'common', 'start': 997, 'end': 1003}, {'entity': 'LABEL_1', 'score': 0.8261587, 'index': 182, 'word': '-', 'start': 1003, 'end': 1004}, {'entity': 'LABEL_1', 'score': 0.713448, 'index': 183, 'word': 'variant', 'start': 1004, 'end': 1011}, {'entity': 'LABEL_1', 'score': 0.68780124, 'index': 184, 'word': 'loci', 'start': 1012, 'end': 1016}, {'entity': 'LABEL_1', 'score': 0.68247306, 'index': 185, 'word': 'include', 'start': 1017, 'end': 1024}, {'entity': 'LABEL_1', 'score': 0.7115472, 'index': 186, 'word': 'coding', 'start': 1025, 'end': 1031}, {'entity': 'LABEL_1', 'score': 0.75727445, 'index': 187, 'word': 'variants', 'start': 1032, 'end': 1040}, {'entity': 'LABEL_1', 'score': 0.7824418, 'index': 188, 'word': 'in', 'start': 1041, 'end': 1043}, {'entity': 'LABEL_1', 'score': 0.62522346, 'index': 189, 'word': 'mend', 'start': 1044, 'end': 1048}, {'entity': 'LABEL_1', 'score': 0.58583355, 'index': 190, 'word': '##elian', 'start': 1048, 'end': 1053}, {'entity': 'LABEL_0', 'score': 0.5000819, 'index': 191, 'word': 'cardiomyopathy', 'start': 1054, 'end': 1068}, {'entity': 'LABEL_1', 'score': 0.73354906, 'index': 192, 'word': 'genes', 'start': 1069, 'end': 1074}, {'entity': 'LABEL_1', 'score': 0.7019745, 'index': 193, 'word': '(', 'start': 1075, 'end': 1076}, {'entity': 'LABEL_1', 'score': 0.56745005, 'index': 194, 'word': 'my', 'start': 1076, 'end': 1078}, {'entity': 'LABEL_1', 'score': 0.5428466, 'index': 195, 'word': '##bp', 'start': 1078, 'end': 1080}, {'entity': 'LABEL_1', 'score': 0.780798, 'index': 196, 'word': '##c', 'start': 1080, 'end': 1081}, {'entity': 'LABEL_1', 'score': 0.61886084, 'index': 197, 'word': '##3', 'start': 1081, 'end': 1082}, {'entity': 'LABEL_1', 'score': 0.70790094, 'index': 198, 'word': ',', 'start': 1082, 'end': 1083}, {'entity': 'LABEL_1', 'score': 0.54635566, 'index': 199, 'word': 'bag', 'start': 1083, 'end': 1086}, {'entity': 'LABEL_1', 'score': 0.7159655, 'index': 200, 'word': '##3', 'start': 1086, 'end': 1087}, {'entity': 'LABEL_1', 'score': 0.7844582, 'index': 201, 'word': ')', 'start': 1087,

#### Trying with Scideberta model

In [ ]:
scideberta_model_name = "KISTI-AI/Scideberta-full"
tokenizer = AutoTokenizer.from_pretrained(scideberta_model_name)
model = AutoModelForTokenClassification.from_pretrained(scideberta_model_name)

config.json:   0%|          | 0.00/630 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/convert_slow_tokenizer.py:561: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/370M [00:00<?, ?B/s]

Some weights of DebertaV2ForTokenClassification were not initialized from the model checkpoint at KISTI-AI/Scideberta-full and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
ner_pipeline_scideberta = pipeline("ner",model = model,tokenizer = tokenizer)

In [ ]:
results = ner_pipeline_scideberta(test_abstracts[1])

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

In [ ]:
print(results)

[{'entity': 'LABEL_0', 'score': 0.79368806, 'index': 1, 'word': '▁Heart', 'start': 2, 'end': 7}, {'entity': 'LABEL_0', 'score': 0.8546206, 'index': 2, 'word': '▁failure', 'start': 7, 'end': 15}, {'entity': 'LABEL_0', 'score': 0.8886659, 'index': 3, 'word': '▁(', 'start': 15, 'end': 17}, {'entity': 'LABEL_0', 'score': 0.77371, 'index': 4, 'word': 'HF', 'start': 17, 'end': 19}, {'entity': 'LABEL_0', 'score': 0.8920017, 'index': 5, 'word': ')', 'start': 19, 'end': 20}, {'entity': 'LABEL_0', 'score': 0.8978145, 'index': 6, 'word': '▁is', 'start': 20, 'end': 23}, {'entity': 'LABEL_0', 'score': 0.78522617, 'index': 7, 'word': '▁a', 'start': 23, 'end': 25}, {'entity': 'LABEL_0', 'score': 0.8166421, 'index': 8, 'word': '▁complex', 'start': 25, 'end': 33}, {'entity': 'LABEL_0', 'score': 0.7891117, 'index': 9, 'word': '▁trait', 'start': 33, 'end': 39}, {'entity': 'LABEL_0', 'score': 0.8242987, 'index': 10, 'word': ',', 'start': 39, 'end': 40}, {'entity': 'LABEL_0', 'score': 0.5747206, 'index': 11, 'word': '▁influenced', 'start': 40, 'end': 51}, {'entity': 'LABEL_0', 'score': 0.82879585, 'index': 12, 'word': '▁by', 'start': 51, 'end': 54}, {'entity': 'LABEL_0', 'score': 0.54712313, 'index': 13, 'word': '▁environmental', 'start': 54, 'end': 68}, {'entity': 'LABEL_0', 'score': 0.75500417, 'index': 14, 'word': '▁and', 'start': 68, 'end': 72}, {'entity': 'LABEL_0', 'score': 0.85502166, 'index': 15, 'word': '▁genetic', 'start': 72, 'end': 80}, {'entity': 'LABEL_0', 'score': 0.8708562, 'index': 16, 'word': '▁factors', 'start': 80, 'end': 88}, {'entity': 'LABEL_0', 'score': 0.7749074, 'index': 17, 'word': ',', 'start': 88, 'end': 89}, {'entity': 'LABEL_0', 'score': 0.6335417, 'index': 18, 'word': '▁that', 'start': 89, 'end': 94}, {'entity': 'LABEL_0', 'score': 0.58736575, 'index': 19, 'word': '▁affects', 'start': 94, 'end': 102}, {'entity': 'LABEL_0', 'score': 0.5688111, 'index': 20, 'word': '▁over', 'start': 102, 'end': 107}, {'entity': 'LABEL_0', 'score': 0.75396144, 'index': 21, 'word': '▁30', 'start': 107, 'end': 110}, {'entity': 'LABEL_0', 'score': 0.736021, 'index': 22, 'word': '▁million', 'start': 110, 'end': 118}, {'entity': 'LABEL_0', 'score': 0.756507, 'index': 23, 'word': '▁individuals', 'start': 118, 'end': 130}, {'entity': 'LABEL_0', 'score': 0.76148295, 'index': 24, 'word': '▁worldwide', 'start': 130, 'end': 140}, {'entity': 'LABEL_0', 'score': 0.71629757, 'index': 25, 'word': '.', 'start': 140, 'end': 141}, {'entity': 'LABEL_0', 'score': 0.61195606, 'index': 26, 'word': '▁Historically', 'start': 141, 'end': 154}, {'entity': 'LABEL_0', 'score': 0.77551895, 'index': 27, 'word': ',', 'start': 154, 'end': 155}, {'entity': 'LABEL_0', 'score': 0.85423577, 'index': 28, 'word': '▁the', 'start': 155, 'end': 159}, {'entity': 'LABEL_0', 'score': 0.89805895, 'index': 29, 'word': '▁genetics', 'start': 159, 'end': 168}, {'entity': 'LABEL_0', 'score': 0.9066133, 'index': 30, 'word': '▁of', 'start': 168, 'end': 171}, {'entity': 'LABEL_0', 'score': 0.8641772, 'index': 31, 'word': '▁HF', 'start': 171, 'end': 174}, {'entity': 'LABEL_0', 'score': 0.8325701, 'index': 32, 'word': '▁have', 'start': 174, 'end': 179}, {'entity': 'LABEL_0', 'score': 0.7493231, 'index': 33, 'word': '▁been', 'start': 179, 'end': 184}, {'entity': 'LABEL_0', 'score': 0.6817668, 'index': 34, 'word': '▁studied', 'start': 184, 'end': 192}, {'entity': 'LABEL_0', 'score': 0.85257006, 'index': 35, 'word': '▁in', 'start': 192, 'end': 195}, {'entity': 'LABEL_0', 'score': 0.623413, 'index': 36, 'word': '▁Mendel', 'start': 195, 'end': 202}, {'entity': 'LABEL_0', 'score': 0.78276765, 'index': 37, 'word': 'ian', 'start': 202, 'end': 205}, {'entity': 'LABEL_0', 'score': 0.90412533, 'index': 38, 'word': '▁forms', 'start': 205, 'end': 211}, {'entity': 'LABEL_0', 'score': 0.8894689, 'index': 39, 'word': '▁of', 'start': 211, 'end': 214}, {'entity': 'LABEL_0', 'score': 0.74648285, 'index': 40, 'word': '▁disease', 'start': 214, 'end': 222}, {'entity': 'LABEL_1', 'score': 0.671229, 'index': 41, 'word': ',', 'start': 222, 'end': 223}, {'entity': 'LABEL_0', 'score': 0.78000486, 'index': 42, 'word': '▁where', 'start': 223, 'end': 229}, {'entity': 'LABEL_0', 'score': 0.7509482, 'index': 43, 'word': '▁rare', 'start': 229, 'end': 234}, {'entity': 'LABEL_0', 'score': 0.9316364, 'index': 44, 'word': '▁genetic', 'start': 234, 'end': 242}, {'entity': 'LABEL_0', 'score': 0.8586547, 'index': 45, 'word': '▁variants', 'start': 242, 'end': 251}, {'entity': 'LABEL_0', 'score': 0.8473407, 'index': 46, 'word': '▁have', 'start': 251, 'end': 256}, {'entity': 'LABEL_0', 'score': 0.67518884, 'index': 47, 'word': '▁been', 'start': 256, 'end': 261}, {'entity': 'LABEL_0', 'score': 0.81766236, 'index': 48, 'word': '▁linked', 'start': 261, 'end': 268}, {'entity': 'LABEL_0', 'score': 0.9153471, 'index': 49, 'word': '▁to', 'start': 268, 'end': 271}, {'entity': 'LABEL_0', 'score': 0.8615932, 'index': 50, 'word': '▁familial', 'start': 271, 'end': 280}, {'entity': 'LABEL_0', 'score': 0.53530055, 'index': 51, 'word': '▁cardio', 'start': 280, 'end': 287}, {'entity': 'LABEL_0', 'score': 0.76092505, 'index': 52, 'word': 'my', 'start': 287, 'end': 289}, {'entity': 'LABEL_0', 'score': 0.78837246, 'index': 53, 'word': 'opathies', 'start': 289, 'end': 297}, {'entity': 'LABEL_0', 'score': 0.6678521, 'index': 54, 'word': '.', 'start': 297, 'end': 298}, {'entity': 'LABEL_0', 'score': 0.72987586, 'index': 55, 'word': '▁More', 'start': 298, 'end': 303}, {'entity': 'LABEL_0', 'score': 0.82957584, 'index': 56, 'word': '▁recently', 'start': 303, 'end': 312}, {'entity': 'LABEL_0', 'score': 0.7462279, 'index': 57, 'word': ',', 'start': 312, 'end': 313}, {'entity': 'LABEL_0', 'score': 0.8203296, 'index': 58, 'word': '▁genome', 'start': 313, 'end': 320}, {'entity': 'LABEL_0', 'score': 0.77655286, 'index': 59, 'word': '-', 'start': 320, 'end': 321}, {'entity': 'LABEL_0', 'score': 0.5610855, 'index': 60, 'word': 'wide', 'start': 321, 'end': 325}, {'entity': 'LABEL_0', 'score': 0.5942662, 'index': 61, 'word': '▁association', 'start': 325, 'end': 337}, {'entity': 'LABEL_0', 'score': 0.8457728, 'index': 62, 'word': '▁studies', 'start': 337, 'end': 345}, {'entity': 'LABEL_0', 'score': 0.8384866, 'index': 63, 'word': '▁(', 'start': 345, 'end': 347}, {'entity': 'LABEL_0', 'score': 0.5288194, 'index': 64, 'word': 'G', 'start': 347, 'end': 348}, {'entity': 'LABEL_0', 'score': 0.73968977, 'index': 65, 'word': 'WAS', 'start': 348, 'end': 351}, {'entity': 'LABEL_1', 'score': 0.5500135, 'index': 66, 'word': ')', 'start': 351, 'end': 352}, {'entity': 'LABEL_0', 'score': 0.83234453, 'index': 67, 'word': '▁have', 'start': 352, 'end': 357}, {'entity': 'LABEL_0', 'score': 0.756105, 'index': 68, 'word': '▁successfully', 'start': 357, 'end': 370}, {'entity': 'LABEL_0', 'score': 0.5506704, 'index': 69, 'word': '▁identified', 'start': 370, 'end': 381}, {'entity': 'LABEL_0', 'score': 0.8268494, 'index': 70, 'word': '▁common', 'start': 381, 'end': 388}, {'entity': 'LABEL_0', 'score': 0.90574116, 'index': 71, 'word': '▁genetic', 'start': 388, 'end': 396}, {'entity': 'LABEL_0', 'score': 0.7861071, 'index': 72, 'word': '▁variants', 'start': 396, 'end': 405}, {'entity': 'LABEL_0', 'score': 0.7153689, 'index': 73, 'word': '▁associated', 'start': 405, 'end': 416}, {'entity': 'LABEL_0', 'score': 0.9476901, 'index': 74, 'word': '▁with', 'start': 416, 'end': 421}, {'entity': 'LABEL_0', 'score': 0.90864474, 'index': 75, 'word': '▁risk', 'start': 421, 'end': 426}, {'entity': 'LABEL_0', 'score': 0.90441704, 'index': 76, 'word': '▁of', 'start': 426, 'end': 429}, {'entity': 'LABEL_0', 'score': 0.84794945, 'index': 77, 'word': '▁HF', 'start': 429, 'end': 432}, {'entity': 'LABEL_1', 'score': 0.58074194, 'index': 78, 'word': '.', 'start': 432, 'end': 433}, {'entity': 'LABEL_0', 'score': 0.71496445, 'index': 79, 'word': '▁However', 'start': 433, 'end': 441}, {'entity': 'LABEL_0', 'score': 0.68091697, 'index': 80, 'word': ',', 'start': 441, 'end': 442}, {'entity': 'LABEL_0', 'score': 0.8286752, 'index': 81, 'word': '▁the', 'start': 442, 'end': 446}, {'entity': 'LABEL_0', 'score': 0.8350482, 'index': 82, 'word': '▁relative', 'start': 446, 'end': 455}, {'entity': 'LABEL_0', 'score': 0.9124574, 'index': 83, 'word': '▁importance', 'start': 455, 'end': 466}, {'entity': 'LABEL_0', 'score': 0.90049636, 'index': 84, 'word': '▁of', 'start': 466, 'end': 469}, {'entity': 'LABEL_0', 'score': 0.93306947, 'index': 85, 'word': '▁genetic', 'start': 469, 'end': 477}, {'entity': 'LABEL_0', 'score': 0.7675924, 'index': 86, 'word': '▁variants', 'start': 477, 'end': 486}, {'entity': 'LABEL_0', 'score': 0.6762714, 'index': 87, 'word': '▁across', 'start': 486, 'end': 493}, {'entity': 'LABEL_0', 'score': 0.8490379, 'index': 88, 'word': '▁the', 'start': 493, 'end': 497}, {'entity': 'LABEL_0', 'score': 0.8462927, 'index': 89, 'word': '▁allele', 'start': 497, 'end': 504}, {'entity': 'LABEL_0', 'score': 0.8696791, 'index': 90, 'word': '-', 'start': 504, 'end': 505}, {'entity': 'LABEL_0', 'score': 0.84291506, 'index': 91, 'word': 'frequency', 'start': 505, 'end': 514}, {'entity': 'LABEL_0', 'score': 0.9248687, 'index': 92, 'word': '▁spectrum', 'start': 514, 'end': 523}, {'entity': 'LABEL_0', 'score': 0.75823486, 'index': 93, 'word': '▁remains', 'start': 523, 'end': 531}, {'entity': 'LABEL_0', 'score': 0.6240844, 'index': 94, 'word': '▁in', 'start': 531, 'end': 534}, {'entity': 'LABEL_1', 'score': 0.5550561, 'index': 95, 'word': 'completely', 'start': 534, 'end': 544}, {'entity': 'LABEL_0', 'score': 0.72867393, 'index': 96, 'word': '▁characterized', 'start': 544, 'end': 558}, {'entity': 'LABEL_1', 'score': 0.53044754, 'index': 97, 'word': '.', 'start': 558, 'end': 559}, {'entity': 'LABEL_0', 'score': 0.8916718, 'index': 98, 'word': '▁Here', 'start': 559, 'end': 564}, {'entity': 'LABEL_0', 'score': 0.510414, 'index': 99, 'word': ',', 'start': 564, 'end': 565}, {'entity': 'LABEL_0', 'score': 0.86414677, 'index': 100, 'word': '▁we', 'start': 565, 'end': 568}, {'entity': 'LABEL_0', 'score': 0.905978, 'index': 101, 'word': '▁report', 'start': 568, 'end': 575}, {'entity': 'LABEL_0', 'score': 0.87220114, 'index': 102, 'word': '▁the', 'start': 575, 'end': 579}, {'entity': 'LABEL_0', 'score': 0.9291103, 'index': 103, 'word': '▁results', 'start': 579, 'end': 587}, {'entity': 'LABEL_0', 'score': 0.8645258, 'index': 104, 'word': '▁of', 'start': 587, 'end': 590}, {'entity': 'LABEL_0', 'score': 0.8110061, 'index': 105, 'word': '▁common', 'start': 590, 'end': 597}, {'entity': 'LABEL_1', 'score': 0.5488974, 'index': 106, 'word': '-', 'start': 597, 'end': 598}, {'entity': 'LABEL_0', 'score': 0.7882397, 'index': 107, 'word': '▁and', 'start': 598, 'end': 602}, {'entity': 'LABEL_0', 'score': 0.7810302, 'index': 108, 'word': '▁rare', 'start': 602, 'end': 607}, {'entity': 'LABEL_0', 'score': 0.742279, 'index': 109, 'word': '-', 'start': 607, 'end': 608}, {'entity': 'LABEL_0', 'score': 0.635732, 'index': 110, 'word': 'variant', 'start': 608, 'end': 615}, {'entity': 'LABEL_0', 'score': 0.81105685, 'index': 111, 'word': '▁association', 'start': 615, 'end': 627}, {'entity': 'LABEL_0', 'score': 0.9254116, 'index': 112, 'word': '▁studies', 'start': 627, 'end': 635}, {'entity': 'LABEL_0', 'score': 0.8855015, 'index': 113, 'word': '▁of', 'start': 635, 'end': 638}, {'entity': 'LABEL_0', 'score': 0.8840304, 'index': 114, 'word': '▁all', 'start': 638, 'end': 642}, {'entity': 'LABEL_0', 'score': 0.9117949, 'index': 115, 'word': '-', 'start': 642, 'end': 643}, {'entity': 'LABEL_0', 'score': 0.6828719, 'index': 116, 'word': 'cause', 'start': 643, 'end': 648}, {'entity': 'LABEL_0', 'score': 0.8998082, 'index': 117, 'word': '▁heart', 'start': 648, 'end': 654}, {'entity': 'LABEL_0', 'score': 0.878946, 'index': 118, 'word': '▁failure', 'start': 654, 'end': 662}, {'entity': 'LABEL_0', 'score': 0.8302567, 'index': 119, 'word': ',', 'start': 662, 'end': 663}, {'entity': 'LABEL_0', 'score': 0.66527385, 'index': 120, 'word': '▁applying', 'start': 663, 'end': 672}, {'entity': 'LABEL_0', 'score': 0.88939583, 'index': 121, 'word': '▁recently', 'start': 672, 'end': 681}, {'entity': 'LABEL_0', 'score': 0.6870794, 'index': 122, 'word': '▁developed', 'start': 681, 'end': 691}, {'entity': 'LABEL_0', 'score': 0.84774965, 'index': 123, 'word': '▁methods', 'start': 691, 'end': 699}, {'entity': 'LABEL_0', 'score': 0.9005467, 'index': 124, 'word': '▁to', 'start': 699, 'end': 702}, {'entity': 'LABEL_0', 'score': 0.824474, 'index': 125, 'word': '▁quantify', 'start': 702, 'end': 711}, {'entity': 'LABEL_0', 'score': 0.906935, 'index': 126, 'word': '▁the', 'start': 711, 'end': 715}, {'entity': 'LABEL_0', 'score': 0.8796411, 'index': 127, 'word': '▁heritability', 'start': 715, 'end': 728}, {'entity': 'LABEL_0', 'score': 0.9205151, 'index': 128, 'word': '▁of', 'start': 728, 'end': 731}, {'entity': 'LABEL_0', 'score': 0.8972079, 'index': 129, 'word': '▁HF', 'start': 731, 'end': 734}, {'entity': 'LABEL_0', 'score': 0.6796497, 'index': 130, 'word': '▁attributable', 'start': 734, 'end': 747}, {'entity': 'LABEL_0', 'score': 0.9124614, 'index': 131, 'word': '▁to', 'start': 747, 'end': 750}, {'entity': 'LABEL_0', 'score': 0.8932211, 'index': 132, 'word': '▁different', 'start': 750, 'end': 760}, {'entity': 'LABEL_0', 'score': 0.9377352, 'index': 133, 'word': '▁classes', 'start': 760, 'end': 768}, {'entity': 'LABEL_0', 'score': 0.88198954, 'index': 134, 'word': '▁of', 'start': 768, 'end': 771}, {'entity': 'LABEL_0', 'score': 0.91523, 'index': 135, 'word': '▁genetic', 'start': 771, 'end': 779}, {'entity': 'LABEL_0', 'score': 0.81690025, 'index': 136, 'word': '▁variation', 'start': 779, 'end': 789}, {'entity': 'LABEL_0', 'score': 0.74611706, 'index': 137, 'word': '.', 'start': 789, 'end': 790}, {'entity': 'LABEL_0', 'score': 0.74278885, 'index': 138, 'word': '▁We', 'start': 790, 'end': 793}, {'entity': 'LABEL_0', 'score': 0.78716254, 'index': 139, 'word': '▁combine', 'start': 793, 'end': 801}, {'entity': 'LABEL_0', 'score': 0.7699528, 'index': 140, 'word': '▁GWAS', 'start': 801, 'end': 806}, {'entity': 'LABEL_0', 'score': 0.9134005, 'index': 141, 'word': '▁data', 'start': 806, 'end': 811}, {'entity': 'LABEL_0', 'score': 0.6004134, 'index': 142, 'word': '▁across', 'start': 811, 'end': 818}, {'entity': 'LABEL_0', 'score': 0.582292, 'index': 143, 'word': '▁multiple', 'start': 818, 'end': 827}, {'entity': 'LABEL_0', 'score': 0.818505, 'index': 144, 'word': '▁populations', 'start': 827, 'end': 839}, {'entity': 'LABEL_0', 'score': 0.6865095, 'index': 145, 'word': '▁including', 'start': 839, 'end': 849}, {'entity': 'LABEL_0', 'score': 0.65925246, 'index': 146, 'word': '▁207', 'start': 849, 'end': 853}, {'entity': 'LABEL_0', 'score': 0.52232337, 'index': 147, 'word': ',', 'start': 853, 'end': 854}, {'entity': 'LABEL_0', 'score': 0.69217634, 'index': 148, 'word': '346', 'start': 854, 'end': 857}, {'entity': 'LABEL_0', 'score': 0.7839087, 'index': 149, 'word': '▁individuals', 'start': 857, 'end': 869}, {'entity': 'LABEL_0', 'score': 0.88147855, 'index': 150, 'word': '▁with', 'start': 869, 'end': 874}, {'entity': 'LABEL_0', 'score': 0.7799909, 'index': 151, 'word': '▁HF', 'start': 874, 'end': 877}, {'entity': 'LABEL_0', 'score': 0.8557174, 'index': 152, 'word': '▁and', 'start': 877, 'end': 881}, {'entity': 'LABEL_0', 'score': 0.5960745, 'index': 153, 'word': '▁2', 'start': 881, 'end': 883}, {'entity': 'LABEL_0', 'score': 0.5117744, 'index': 154, 'word': ',', 'start': 883, 'end': 884}, {'entity': 'LABEL_0', 'score': 0.6889692, 'index': 155, 'word': '151', 'start': 884, 'end': 887}, {'entity': 'LABEL_1', 'score': 0.5894132, 'index': 156, 'word': ',', 'start': 887, 'end': 888}, {'entity': 'LABEL_0', 'score': 0.69317687, 'index': 157, 'word': '210', 'start': 888, 'end': 891}, {'entity': 'LABEL_0', 'score': 0.77203584, 'index': 158, 'word': '▁without', 'start': 891, 'end': 899}, {'entity': 'LABEL_0', 'score': 0.80469143, 'index': 159, 'word': ',', 'start': 899, 'end': 900}, {'entity': 'LABEL_1', 'score': 0.566279, 'index': 160, 'word': '▁identifying', 'start': 900, 'end': 912}, {'entity': 'LABEL_0', 'score': 0.79513997, 'index': 161, 'word': '▁176', 'start': 912, 'end': 916}, {'entity': 'LABEL_0', 'score': 0.7988101, 'index': 162, 'word': '▁risk', 'start': 916, 'end': 921}, {'entity': 'LABEL_0', 'score': 0.76332533, 'index': 163, 'word': '▁loci', 'start': 921, 'end': 926}, {'entity': 'LABEL_0', 'score': 0.5477825, 'index': 164, 'word': '▁at', 'start': 926, 'end': 929}, {'entity': 'LABEL_0', 'score': 0.7339964, 'index': 165, 'word': '▁genome', 'start': 929, 'end': 936}, {'entity': 'LABEL_0', 'score': 0.66177005, 'index': 166, 'word': '-', 'start': 936, 'end': 937}, {'entity': 'LABEL_0', 'score': 0.5334452, 'index': 167, 'word': 'wide', 'start': 937, 'end': 941}, {'entity': 'LABEL_0', 'score': 0.6401232, 'index': 168, 'word': '▁significance', 'start': 941, 'end': 954}, {'entity': 'LABEL_0', 'score': 0.8022613, 'index': 169, 'word': '▁(', 'start': 954, 'end': 956}, {'entity': 'LABEL_0', 'score': 0.81609344, 'index': 170, 'word': 'p', 'start': 956, 'end': 957}, {'entity': 'LABEL_0', 'score': 0.677399, 'index': 171, 'word': '▁<', 'start': 957, 'end': 959}, {'entity': 'LABEL_0', 'score': 0.5392665, 'index': 172, 'word': '▁5', 'start': 959, 'end': 961}, {'entity': 'LABEL_0', 'score': 0.6767776, 'index': 173, 'word': '×10', 'start': 961, 'end': 964}, {'entity': 'LABEL_1', 'score': 0.50485754, 'index': 174, 'word': '−', 'start': 964, 'end': 965}, {'entity': 'LABEL_1', 'score': 0.7772244, 'index': 175, 'word': '8', 'start': 965, 'end': 966}, {'entity': 'LABEL_0', 'score': 0.821686, 'index': 176, 'word': ')', 'start': 966, 'end': 967}, {'entity': 'LABEL_0', 'score': 0.8299475, 'index': 177, 'word': '.', 'start': 967, 'end': 968}, {'entity': 'LABEL_0', 'score': 0.7826803, 'index': 178, 'word': '▁Signals', 'start': 968, 'end': 976}, {'entity': 'LABEL_0', 'score': 0.50361794, 'index': 179, 'word': '▁at', 'start': 976, 'end': 979}, {'entity': 'LABEL_0', 'score': 0.68556345, 'index': 180, 'word': '▁newly', 'start': 979, 'end': 985}, {'entity': 'LABEL_1', 'score': 0.6289835, 'index': 181, 'word': '▁identified', 'start': 985, 'end': 996}, {'entity': 'LABEL_0', 'score': 0.8017686, 'index': 182, 'word': '▁common', 'start': 996, 'end': 1003}, {'entity': 'LABEL_0', 'score': 0.7719631, 'index': 183, 'word': '-', 'start': 1003, 'end': 1004}, {'entity': 'LABEL_1', 'score': 0.5416324, 'index': 184, 'word': 'variant', 'start': 1004, 'end': 1011}, {'entity': 'LABEL_0', 'score': 0.89526606, 'index': 185, 'word': '▁loci', 'start': 1011, 'end': 1016}, {'entity': 'LABEL_0', 'score': 0.84017223, 'index': 186, 'word': '▁include', 'start': 1016, 'end': 1024}, {'entity': 'LABEL_0', 'score': 0.8435999, 'index': 187, 'word': '▁coding', 'start': 1024, 'end': 1031}, {'entity': 'LABEL_0', 'score': 0.82395554, 'index': 188, 'word': '▁variants', 'start': 1031, 'end': 1040}, {'entity': 'LABEL_0', 'score': 0.7539075, 'index': 189, 'word': '▁in', 'start': 1040, 'end': 1043}, {'entity': 'LABEL_1', 'score': 0.5464313, 'index': 190, 'word': '▁Mendel', 'start': 1043, 'end': 1050}, {'entity': 'LABEL_0', 'score': 0.73186225, 'index': 191, 'word': 'ian', 'start': 1050, 'end': 1053}, {'entity': 'LABEL_0', 'score': 0.66392344, 'index': 192, 'word': '▁cardiomyopathy', 'start': 1053, 'end': 1068}, {'entity': 'LABEL_0', 'score': 0.76202893, 'index': 193, 'word': '▁genes', 'start': 1068, 'end': 1074}, {'entity': 'LABEL_0', 'score': 0.73542994, 'index': 194, 'word': '▁(', 'start': 1074, 'end': 1076}, {'entity': 'LABEL_0', 'score': 0.7940784, 'index': 195, 'word': 'MY', 'start': 1076, 'end': 1078}, {'entity': 'LABEL_0', 'score': 0.6169747, 'index': 196, 'word': 'BP', 'start': 1078, 'end': 1080}, {'entity': 'LABEL_0', 'score': 0.7199486, 'index': 197, 'word': 'C', 'start': 1080, 'end': 1081}, {'entity': 'LABEL_0', 'score': 0.76943916, 'index': 198, 'word': '3', 'start': 1081, 'end': 1082}, {'entity': 'LABEL_0', 'score': 0.66414857, 'index': 199, 'word': ',', 'start': 1082, 'end': 1083}, {'entity': 'LABEL_0', 'score': 0.7871428, 'index': 200, 'word': 'BAG',

In [ ]:
scores = []
words = []
for result in results:
  scores.append(result['score'])
  words.append(result['word'])

In [ ]:
len(results)

472

In [ ]:
extracted_entities_df = pd.DataFrame.from_dict({'Word':words,'Score':scores})

In [ ]:
extracted_entities_df = extracted_entities_df.sort_values(by=['Score'],ascending=False)

In [ ]:
extracted_entities_df.head()

         Word     Score
250    ▁types  0.958435
73      ▁with  0.947690
132  ▁classes  0.937735
84   ▁genetic  0.933069
43   ▁genetic  0.931636

#### Finetuning SciBERT

1) SCIERC - Scientific entity and relationship corpus <br>
2) S2ORC - The Semantic Scholar Open Research Corpus <br>

EXTRA - SemEval-2017 Task-10 <br>
Models considered - SciDeBERTa: This tests SCIERC

In [ ]:
scierc_re = load_dataset("nsusemiehl/SciERC") # This has labels for Relationship extraction but not for Entity extraction

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/242 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

train.jsonl:   0%|          | 0.00/824k [00:00<?, ?B/s]

dev.jsonl:   0%|          | 0.00/118k [00:00<?, ?B/s]

test.jsonl:   0%|          | 0.00/249k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3219 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/455 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/974 [00:00<?, ? examples/s]

In [ ]:
print(scierc_re)

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'metadata'],
        num_rows: 3219
    })
    validation: Dataset({
        features: ['text', 'label', 'metadata'],
        num_rows: 455
    })
    test: Dataset({
        features: ['text', 'label', 'metadata'],
        num_rows: 974
    })
})

In [ ]:
train_df = scierc_re['train'].to_pandas()

In [ ]:
train_df.head()

,text,label,metadata
0,The agreement in question involves number in [...,CONJUNCTION,"[7, 7, 9, 10]"
1,The agreement in question involves number in n...,FEATURE-OF,"[26, 27, 29, 29]"
2,The agreement in question involves number in n...,HYPONYM-OF,"[32, 32, 29, 29]"
3,"In this paper , a novel [[ method ]] to learn ...",USED-FOR,"[6, 6, 10, 12]"
4,"In this paper , a novel method to learn the [[...",USED-FOR,"[10, 12, 14, 16]"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("allenai/scibert_scivocab_uncased")

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/228k [00:00<?, ?B/s]

In [ ]:
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples, truncation=True, is_split_into_words=False)

    # Align labels with subword tokens
    labels = []
    for i, label in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_id = None
        label_ids = []
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)  # Special tokens
            elif word_id != previous_word_id:
                label_ids.append(label[word_id])  # Assign label
            else:
                label_ids.append(-100)  # Subword tokens
            previous_word_id = word_id
        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

In [ ]:
tokenized_datasets = train_df.map(tokenize_and_align_labels)

In [ ]:
test_str = train_df['text'][0]

In [ ]:
tokenized_inputs = tokenizer(test_str, truncation=True, is_split_into_words=False)

{'input_ids': [102, 111, 4111, 121, 2214, 5185, 649, 121, 260, 260, 24748, 1901, 1901, 137, 962, 962, 11229, 1090, 29213, 30113, 1374, 1374, 137, 165, 13510, 2316, 506, 5437, 121, 2540, 923, 22956, 649, 121, 6170, 422, 1967, 22956, 4703, 121, 6554, 555, 188, 10282, 422, 165, 9632, 5765, 205, 103], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

#### Testing with SciERC

In [ ]:
scierc_train_df = pd.read_json('/content/train.json', lines=True)

In [ ]:
scierc_train_df.head()

,clusters,sentences,ner,relations,doc_key
0,"[[[17, 20], [23, 23]]]","[[English, is, shown, to, be, trans-context-fr...","[[[0, 0, Material], [10, 10, OtherScientificTe...","[[], [[29, 29, 31, 32, CONJUNCTION], [48, 49, ...",J87-1003
1,"[[[62, 64], [90, 91], [96, 98], [112, 114]], [...","[[In, this, paper, ,, a, novel, method, to, le...","[[[6, 6, Method], [10, 12, OtherScientificTerm...","[[[6, 6, 10, 12, USED-FOR], [10, 12, 14, 16, U...",CVPR_2003_18_abs
2,"[[[154, 154], [214, 214]], [[40, 44], [85, 85]...","[[In, this, paper, ,, we, present, a, digital,...","[[[7, 13, Method], [15, 21, Method], [23, 25, ...","[[[7, 13, 15, 21, USED-FOR], [15, 21, 23, 25, ...",INTERSPEECH_2013_31_abs
3,"[[[3, 3], [110, 110]]]","[[We, propose, a, method, that, automatically,...","[[[3, 3, Generic], [7, 7, OtherScientificTerm]...","[[[3, 3, 7, 7, USED-FOR], [7, 7, 20, 23, USED-...",I05-5008
4,"[[[35, 35], [69, 69]]]","[[Graph, unification, remains, the, most, expe...","[[[0, 1, Task], [8, 10, Task]], [[16, 17, Meth...","[[[0, 1, 8, 10, PART-OF]], [[16, 17, 22, 23, P...",C92-2068

In [ ]:
tokens = scierc_train_df.iloc[0,1]

In [ ]:
extracted_entities = scierc_train_df.iloc[0,2]

In [ ]:
relations = scierc_train_df.iloc[0,3]

In [ ]:
text = ''

In [ ]:
for sentence in tokens:
  text = ' '.join(sentence)
  # text += ' '.join(sentence)
  print(text)

English is shown to be trans-context-free on the basis of coordinations of the respectively type that involve strictly syntactic cross-serial agreement .
The agreement in question involves number in nouns and reflexive pronouns and is syntactic rather than semantic in nature because grammatical number in English , like grammatical gender in languages such as French , is partly arbitrary .
The formal proof , which makes crucial use of the Interchange Lemma of Ogden et al. , is so constructed as to be valid even if English is presumed to contain grammatical sentences in which respectively operates across a pair of coordinate phrases one of whose members has fewer conjuncts than the other ; it thus goes through whatever the facts may be regarding constructions with unequal numbers of conjuncts in the scope of respectively , whereas other arguments have foundered on this problem .

In [ ]:
print(f'Extracted text: {text}\n')

Extracted text: The formal proof , which makes crucial use of the Interchange Lemma of Ogden et al. , is so constructed as to be valid even if English is presumed to contain grammatical sentences in which respectively operates across a pair of coordinate phrases one of whose members has fewer conjuncts than the other ; it thus goes through whatever the facts may be regarding constructions with unequal numbers of conjuncts in the scope of respectively , whereas other arguments have foundered on this problem .


The goal is to loop through each row, identify the number of sentences, and triplets for each sentence.

In [ ]:
def preprocess_scierc_gpt(row):
    sentences = row["sentences"]
    ner = row["ner"]
    relations = row["relations"]

    triplets = []

    for sentence, sentence_ner, sentence_relations in zip(sentences, ner, relations):
        # Convert indices to entity text spans
        entities = {}
        for start, end, _ in sentence_ner:
            entity_text = " ".join(sentence[start:end + 1])
            entities[(start, end)] = entity_text

        # Extract triplets based on relations
        for rel in sentence_relations:
            start1, end1, start2, end2, rel_type = rel
            entity1 = entities.get((start1, end1))
            entity2 = entities.get((start2, end2))
            if entity1 and entity2:
                triplets.append((entity1, rel_type, entity2))

    return triplets

In [ ]:
scierc_train_df["triplets"] = scierc_train_df.apply(preprocess_scierc_gpt, axis=1)

In [ ]:
def prepare_training_data(row):
    sentences = row["sentences"]
    triplets = row["triplets"]

    examples = []
    for sentence, triplet in zip(sentences, triplets):
        #input_text = " ".join(sentence)
        input_text = f"Extract entities and relationships from: {' '.join(sentence)}"
        entity1, relation, entity2 = triplet

        # Concatenate entities with the sentence for training
        output_text = f"<entity1> {entity1} </entity1> <relation> {relation} </relation> <entity2> {entity2} </entity2>"
        examples.append((input_text, output_text))

    return examples

In [ ]:
training_data = scierc_train_df.apply(prepare_training_data, axis=1)

In [ ]:
training_data_updated = scierc_train_df.apply(prepare_training_data, axis=1)

In [ ]:
training_examples = [example for examples in training_data for example in examples]

In [ ]:
training_examples

[('Extract entities and relationships from: English is shown to be trans-context-free on the basis of coordinations of the respectively type that involve strictly syntactic cross-serial agreement .',
  '<entity1> languages </entity1> <relation> CONJUNCTION </relation> <entity2> as French </entity2>'),
 ('Extract entities and relationships from: In this paper , a novel method to learn the intrinsic object structure for robust visual tracking is proposed .',
  '<entity1> method </entity1> <relation> USED-FOR </relation> <entity2> intrinsic object structure </entity2>'),
 ('Extract entities and relationships from: The basic assumption is that the parameterized object state lies on a low dimensional manifold and can be learned from training data .',
  '<entity1> intrinsic object structure </entity1> <relation> USED-FOR </relation> <entity2> robust visual tracking </entity2>'),
 ('Extract entities and relationships from: In this paper , we present a digital signal processor -LRB- DSP -RRB- implementation of real-time statistical voice conversion -LRB- VC -RRB- for silent speech enhancement and electrolaryngeal speech enhancement .',
  '<entity1> digital signal processor -LRB- DSP -RRB- implementation </entity1> <relation> USED-FOR </relation> <entity2> real-time statistical voice conversion -LRB- VC -RRB- </entity2>'),
 ('Extract entities and relationships from: As a silent speech interface , we focus on non-audible murmur -LRB- NAM -RRB- , which can be used in situations where audible speech is not acceptable .',
  '<entity1> real-time statistical voice conversion -LRB- VC -RRB- </entity1> <relation> USED-FOR </relation> <entity2> silent speech enhancement </entity2>'),
 ('Extract entities and relationships from: Electrolaryngeal speech is one of the typical types of alaryngeal speech produced by an alternative speaking method for laryngectomees .',
  '<entity1> real-time statistical voice conversion -LRB- VC -RRB- </entity1> <relation> USED-FOR </relation> <entity2> electrolaryngeal speech enhancement </entity2>'),
 ('Extract entities and relationships from: However , the sound quality of NAM and electrolaryngeal speech suffers from lack of naturalness .',
  '<entity1> silent speech enhancement </entity1> <relation> CONJUNCTION </relation> <entity2> electrolaryngeal speech enhancement </entity2>'),
 ('Extract entities and relationships from: We propose a method that automatically generates paraphrase sets from seed sentences to be used as reference sets in objective machine translation evaluation measures like BLEU and NIST .',
  '<entity1> method </entity1> <relation> USED-FOR </relation> <entity2> paraphrase </entity2>'),
 ('Extract entities and relationships from: We measured the quality of the paraphrases produced in an experiment , i.e. , -LRB- i -RRB- their grammaticality : at least 99 % correct sentences ; -LRB- ii -RRB- their equivalence in meaning : at least 96 % correct paraphrases either by meaning equivalence or entailment ; and , -LRB- iii -RRB- the amount of internal lexical and syntactical variation in a set of paraphrases : slightly superior to that of hand-produced sets .',
  '<entity1> paraphrase </entity1> <relation> USED-FOR </relation> <entity2> machine translation evaluation measures </entity2>'),
 ('Extract entities and relationships from: The paraphrase sets produced by this method thus seem adequate as reference sets to be used for MT evaluation .',
  '<entity1> BLEU </entity1> <relation> HYPONYM-OF </relation> <entity2> machine translation evaluation measures </entity2>'),
 ('Extract entities and relationships from: Graph unification remains the most expensive part of unification-based grammar parsing .',
  '<entity1> Graph unification </entity1> <relation> PART-OF </relation> <entity2> unification-based grammar parsing </entity2>'),
 ('Extract entities and relationships from: We describe a novel technique and implemented system for constructing a subcategorization dictionary from textual corpora .',
  '<entity1> system </entity1> <relation> USED-FOR </relation> <entity2> subcategorization dictionary </entity2>'),
 ('Extract entities and relationships from: Each dictionary entry encodes the relative frequency of occurrence of a comprehensive set of subcategorization classes for English .',
  '<entity1> textual corpora </entity1> <relation> USED-FOR </relation> <entity2> system </entity2>'),
 ('Extract entities and relationships from: We introduce a new interactive corpus exploration tool called InfoMagnets .',
  '<entity1> InfoMagnets </entity1> <relation> HYPONYM-OF </relation> <entity2> interactive corpus exploration tool </entity2>'),
 ('Extract entities and relationships from: InfoMagnets aims at making exploratory corpus analysis accessible to researchers who are not experts in text mining .',
  '<entity1> are </entity1> <relation> USED-FOR </relation> <entity2> text mining . </entity2>'),
 ('Extract entities and relationships from: Sources of training data suitable for language modeling of conversational speech are limited .',
  '<entity1> conversational speech </entity1> <relation> USED-FOR </relation> <entity2> language modeling </entity2>'),
 ('Extract entities and relationships from: We present a method for detecting 3D objects using multi-modalities .',
  '<entity1> method </entity1> <relation> USED-FOR </relation> <entity2> detecting 3D objects </entity2>'),
 ('Extract entities and relationships from: While it is generic , we demonstrate it on the combination of an image and a dense depth map which give complementary object information .',
  '<entity1> multi-modalities </entity1> <relation> USED-FOR </relation> <entity2> method </entity2>'),
 ('Extract entities and relationships from: It works in real-time , under heavy clutter , does not require a time consuming training stage , and can handle untextured objects .',
  '<entity1> an </entity1> <relation> USED-FOR </relation> <entity2> map </entity2>'),
 ('Extract entities and relationships from: It is based on an efficient representation of templates that capture the different modalities , and we show in many experiments on commodity hardware that our approach significantly outperforms state-of-the-art methods on single modalities .',
  '<entity1> . </entity1> <relation> USED-FOR </relation> <entity2> map </entity2>'),
 ('Extract entities and relationships from: The compact description of a video sequence through a single image map and a dominant motion has applications in several domains , including video browsing and retrieval , compression , mosaicing , and visual summarization .',
  '<entity1> compact description of a video sequence </entity1> <relation> USED-FOR </relation> <entity2> domains </entity2>'),
 ('Extract entities and relationships from: Building such a representation requires the capability to register all the frames with respect to the dominant object in the scene , a task which has been , in the past , addressed through temporally localized motion estimates .',
  '<entity1> image map </entity1> <relation> USED-FOR </relation> <entity2> compact description of a video sequence </entity2>'),
 ('Extract entities and relationships from: In this paper , we show how the lack of temporal consistency associated with such estimates can undermine the validity of the dominant motion assumption , leading to oscillation between different scene interpretations and poor registration .',
  '<entity1> image map </entity1> <relation> CONJUNCTION </relation> <entity2> dominant motion </entity2>'),
 ('Extract entities and relationships from: To avoid this oscillation , we augment the motion model with a generic temporal constraint which increases the robustness against competing interpretations , leading to more meaningful content summarization .',
  '<entity1> dominant motion </entity1> <relation> USED-FOR </relation> <entity2> compact description of a video sequence </entity2>'),
 ('Extract entities and relationships from: In cross-domain learning , there is a more challenging problem that the domain divergence involves more than one dominant factors , e.g. , different viewpoints , various resolutions and changing illuminations .',
  '<entity1> dominant factors </entity1> <relation> PART-OF </relation> <entity2> domain divergence </entity2>'),
 ('Extract entities and relationships from: Fortunately , an intermediate domain could often be found to build a bridge across them to facilitate the learning problem .',
  '<entity1> viewpoints </entity1> <relation> HYPONYM-OF </relation> <entity2> dominant factors </entity2>'),
 ('Extract entities and relationships from: In this paper , we propose a Coupled Marginalized Denoising Auto-encoders framework to address the cross-domain problem .',
  '<entity1> viewpoints </entity1> <relation> CONJUNCTION </relation> <entity2> resolutions </entity2>'),
 ('Extract entities and relationships from: Specifically , we design two marginalized denoising auto-encoders , one for the target and the other for source as well as the intermediate one .',
  '<entity1> resolutions </entity1> <relation> HYPONYM-OF </relation> <entity2> dominant factors </entity2>'),
 ('Extract entities and relationships from: To better couple the two denoising auto-encoders learning , we incorporate a feature mapping , which tends to transfer knowledge between the intermediate domain and the target one .',
  '<entity1> resolutions </entity1> <relation> CONJUNCTION </relation> <entity2> illuminations </entity2>'),
 ('Extract entities and relationships from: In this paper , we aim to automatically render aging faces in a personalized way .',
  '<entity1> pattern cross </entity1> <relation> PART-OF </relation> <entity2> from different dictionaries </entity2>'),
 ('Extract entities and relationships from: We propose a draft scheme of the model formalizing the structure of communicative context in dialogue interaction .',
  '<entity1> model </entity1> <relation> USED-FOR </relation> <entity2> structure of communicative context </entity2>'),
 ('Extract entities and relationships from: The relationships between the interacting partners are considered as system of three automata representing the partners of the dialogue and environment .',
  '<entity1> dialogue interaction </entity1> <relation> FEATURE-OF </relation> <entity2> structure of communicative context </entity2>'),
 ('Extract entities and relationships from: Visitors who browse the web from wireless PDAs , cell phones , and pagers are frequently stymied by web interfaces optimized for desktop PCs .',
  '<entity1> web interfaces </entity1> <relation> USED-FOR </relation> <entity2> desktop PCs </entity2>'),
 ('Extract entities and relationships from: This paper describes a particular approach to parsing that utilizes recent advances in unification-based parsing and in classification-based knowledge representation .',
  '<entity1> approach </entity1> <relation> USED-FOR </relation> <entity2> parsing </entity2>'),
 ('Extract entities and relationships from: As unification-based grammatical frameworks are extended to handle richer descriptions of linguistic information , they begin to share many of the properties that have been developed in KL-ONE-like knowledge representation systems .',
  '<entity1> unification-based parsing </entity1> <relation> USED-FOR </relation> <entity2> approach </entity2>'),
 ('Extract entities and relationships from: This commonality suggests that some of the classification-based representation techniques can be applied to unification-based linguistic descriptions .',
  '<entity1> classification-based knowledge representation </entity1> <relation> USED-FOR </relation> <entity2> approach </entity2>'),
 ('Extract entities and relationships from: This merging supports the integration of semantic and syntactic information into the same system , simultaneously subject to the same types of processes , in an efficient manner .',
  '<entity1> classification-based knowledge representation </entity1> <relation> CONJUNCTION </relation> <entity2> unification-based parsing </entity2>'),
 ('Extract entities and relationships from: In this paper we discuss a proposed user knowledge modeling architecture for the ICICLE system , a language tutoring application for deaf learners of written English .',
  '<entity1> user knowledge modeling architecture </entity1> <relation> USED-FOR </relation> <entity2> ICICLE system </entity2>'),
 ('Extract entities and relationships from: The model will represent the language proficiency of the user and is designed to be referenced during both writing analysis and feedback production .',
  '<entity1> ICICLE system </entity1> <relation> HYPONYM-OF </relation> <entity2> language tutoring application </entity2>'),
 ('Extract entities and relationships from: We motivate our model design by citing relevant research on second language and cognitive skill acquisition , and briefly discuss preliminary empirical evidence supporting the design .',
  '<entity1> language tutoring application </entity1> <relation> USED-FOR </relation> <entity2> deaf learners </entity2>'),
 ('Extract entities and relationships from: We conclude by showing how our design can provide a rich and robust information base to a language assessment / correction application by modeling user proficiency at a high level of granularity and specificity .',
  '<entity1> written English </entity1> <relation> USED-FOR </relation> <entity2> language tutoring application </entity2>'),
 ('Extract entities and relationships from: Constraint propagation is one of the key techniques in constraint programming , and a large body of work has built up around it .',
  '<entity1> Constraint propagation </entity1> <relation> PART-OF </relation> <entity2> constraint programming </entity2>'),
 ('Extract entities and relationships from: We propose a detection method for orthographic variants caused by transliteration in a large corpus .',
  '<entity1> detection method </entity1> <relation> USED-FOR </relation> <entity2> orthographic variants </entity2>'),
 ('Extract entities and relationships from: Uncertainty handling plays an important role during shape tracking .',
  '<entity1> Uncertainty handling </entity1> <relation> USED-FOR </relation> <entity2> shape tracking </entity2>'),
 ('Extract entities and relationships from: We have recently shown that the fusion of measurement information with system dynamics and shape priors greatly improves the tracking performance for very noisy images such as ultrasound sequences -LSB- 22 -RSB- .',
  '<entity1> greatly improves the tracking performance for very noisy images such </entity1> <relation> USED-FOR </relation> <entity2> -LSB- </entity2>'),
 ('Extract entities and relationships from: We present a syntax-based constraint for word alignment , known as the cohesion constraint .',
  '<entity1> syntax-based constraint </entity1> <relation> USED-FOR </relation> <entity2> word alignment </entity2>'),
 ('Extract entities and relationships from: It requires disjoint English phrases to be mapped to non-overlapping intervals in the French sentence .',
  '<entity1> cohesion constraint </entity1> <relation> HYPONYM-OF </relation> <entity2> syntax-based constraint </entity2>'),
 ('Extract entities and relationships from: This paper introduces a robust interactive method for speech understanding .',
  '<entity1> robust interactive method </entity1> <relation> USED-FOR </relation> <entity2> speech understanding </entity2>'),
 ('Extract entities and relationships from: This paper shows that it is very often possible to identify the source language of medium-length speeches in the EUROPARL corpus on the basis of frequency counts of word n-grams -LRB- 87.2 % -96.7 % accuracy depending on classification method -RRB- .',
  '<entity1> medium-length speeches </entity1> <relation> PART-OF </relation> <entity2> EUROPARL corpus </entity2>'),
 ('Extract entities and relationships from: The paper also examines in detail which positive markers are most powerful and identifies a number of linguistic aspects as well as culture - and domain-related ones .',
  '<entity1> accuracy </entity1> <relation> EVALUATE-FOR </relation> <entity2> classification method </entity2>'),
 ('Extract entities and relationships from: We investigated whether automatic phonetic transcriptions -LRB- APTs -RRB- can replace manually verified phonetic transcriptions -LRB- MPTs -RRB- in a large corpus-based study on pronunciation variation .',
  '<entity1> automatic phonetic transcriptions -LRB- APTs -RRB- </entity1> <relation> COMPARE </relation> <entity2> manually verified phonetic transcriptions </entity2>'),
 ('Extract entities and relationships from: To this end , we compared the performance of both transcription types in a classification experiment aimed at establishing the direct influence of a particular situational setting on pronunciation variation .',
  '<entity1> automatic phonetic transcriptions -LRB- APTs -RRB- </entity1> <relation> USED-FOR </relation> <entity2> pronunciation variation </entity2>'),
 ('Extract entities and relationships from: We trained classifiers on the speech processes extracted from the alignments of an APT and an MPT with a canonical transcription .',
  '<entity1> manually verified phonetic transcriptions </entity1> <relation> USED-FOR </relation> <entity2> pronunciation variation </entity2>'),
 ('Extract entities and relationships from: Machine reading is a relatively new field that features computer programs designed to read flowing text and extract fact assertions expressed by the narrative content .',
  '<entity1> computer programs </entity1> <relation> USED-FOR </relation> <entity2> flowing text </entity2>'),
 ('Extract entities and relationships from: This task involves two core technologies : natural language processing -LRB- NLP -RRB- and information extraction -LRB- IE -RRB- .',
  '<entity1> computer programs </entity1> <relation> USED-FOR </relation> <entity2> fact assertions </entity2>'),
 ('Extract entities and relationships from: In this paper we describe a machine reading system that we have developed within a cognitive architecture .',
  '<entity1> fact assertions </entity1> <relation> FEATURE-OF </relation> <entity2> narrative content </entity2>'),
 ('Extract entities and relationships from: Nonstationary chaotic behavior is not an oxymoron .',
  '<entity1> a </entity1> <relation> USED-FOR </relation> <entity2> including biological </entity2>'),
 ('Extract entities and relationships from: We present two methods for capturing nonstationary chaos , then present a few examples including biological signals , ocean waves and traffic flow .',
  '<entity1> . </entity1> <relation> HYPONYM-OF </relation> <entity2> traffic </entity2>'),
 ('Extract entities and relationships from: This paper presents a formal analysis for a large class of words called alternative markers , which includes other -LRB- than -RRB- , such -LRB- as -RRB- , and besides .',
  '<entity1> formal analysis </entity1> <relation> USED-FOR </relation> <entity2> alternative markers </entity2>'),
 ('Extract entities and relationships from: In this paper , we address the problem of combining several language models -LRB- LMs -RRB- .',
  '<entity1> . </entity1> <relation> HYPONYM-OF </relation> <entity2> performance of </entity2>'),
 ('Extract entities and relationships from: We describe a new method for the representation of NLP structures within reranking approaches .',
  '<entity1> method </entity1> <relation> USED-FOR </relation> <entity2> NLP structures </entity2>'),
 ('Extract entities and relationships from: We make use of a conditional log-linear model , with hidden variables representing the assignment of lexical items to word clusters or word senses .',
  '<entity1> reranking approaches </entity1> <relation> FEATURE-OF </relation> <entity2> NLP structures </entity2>'),

In [ ]:
from sklearn.model_selection import train_test_split

train_texts, eval_texts = train_test_split(training_examples, test_size=0.1)

train_dataset = Dataset.from_dict({
    "input_texts": [example[0] for example in train_texts],
    "output_texts": [example[1] for example in train_texts],
})

eval_dataset = Dataset.from_dict({
    "input_texts": [example[0] for example in eval_texts],
    "output_texts": [example[1] for example in eval_texts],
})

In [ ]:
train_dataset['input_texts']

['Extract entities and relationships from: A deterministic parser is under development which represents a departure from traditional deterministic parsers in that it combines both symbolic and connectionist components .',
 'Extract entities and relationships from: Spelling-checkers have become an integral part of most text processing software .',
 "Extract entities and relationships from: To alleviate this degradation , we propose a statistical conversion process that directly modifies the signal in the waveform domain by estimating the difference in the spectra of the source and target singers ' singing voices .",
 'Extract entities and relationships from: We demonstrate that an approximation of HPSG produces a more effective CFG filter than that of LTAG .',
 'Extract entities and relationships from: The basic assumption is that the parameterized object state lies on a low dimensional manifold and can be learned from training data .',
 'Extract entities and relationships from: A key complementary objective is to define and develop applications of robust speech recognition and understanding systems , and to help catalyze the transition of spoken language technology into military and civilian systems , with particular focus on application of robust CSR to mobile military command and control .',
 'Extract entities and relationships from: Recent advances in linear classification have shown that for applications such as document classification , the training can be extremely efficient .',
 'Extract entities and relationships from: Consequently , in this article we look at the problem of estimating these gear scale factors from training data consisting only of speed measurements and measurements of the signal in question .',
 'Extract entities and relationships from: This paper reports a completed stage of ongoing research at the University of York .',
 'Extract entities and relationships from: We present an algorithm for calibrated camera relative pose estimation from lines .',
 'Extract entities and relationships from: Additionally we present algorithms exploiting local smoothness in more aggressive ways , which perform even better in practice .',
 'Extract entities and relationships from: We detail the computational complexity and average retrieval times for looking up phrase translations in our suffix array-based data structure .',
 'Extract entities and relationships from: The wordnets are aligned to the Princeton Wordnet , according to the principles established by EuroWordNet .',
 'Extract entities and relationships from: Owing to the problem of insufficient training data and approximation error introduced by the language model , traditional statistical approaches , which resolve ambiguities by indirectly and implicitly using maximum likelihood method , fail to achieve high performance in real applications .',
 'Extract entities and relationships from: In noisy conditions , the mismatch between corrupted speech signals and models trained on clean speech may cause the decoder to produce word matches with unrealistic durations .',
 "Extract entities and relationships from: Many description logics -LRB- DLs -RRB- combine knowledge representation on an abstract , logical level with an interface to `` concrete '' domains such as numbers and strings .",
 'Extract entities and relationships from: This paper presents a new two-pass algorithm for Extra Large -LRB- more than 1M words -RRB- Vocabulary COntinuous Speech recognition based on the Information Retrieval -LRB- ELVIRCOS -RRB- .',
 'Extract entities and relationships from: We propose a solution to the challenge of the CoNLL 2008 shared task that uses a generative history-based latent variable model to predict the most likely derivation of a synchronous dependency parser for both syntactic and semantic dependencies .',
 'Extract entities and relationships from: This paper presents an approach to the unsupervised learning of parts of speech which uses both morphological and syntactic information .',
 'Extract entities and relationships from: In this paper , we propose a learning-based approach to construct a joint filter based on Convolution-al Neural Networks .',
 'Extract entities and relationships from: Error correction is done by strongly biasing parsing toward expected meanings unless clear evidence from the input shows the current sentence is not expected .',
 'Extract entities and relationships from: Moreover , both extensions are generic and can therefore be applied to any MRF energy function as well .',
 'Extract entities and relationships from: Johnston 1998 presents an approach in which strategies for multimodal integration are stated declaratively using a unification-based grammar that is used by a multidimensional chart parser to compose inputs .',
 'Extract entities and relationships from: Syntax-based statistical machine translation -LRB- MT -RRB- aims at applying statistical models to structured data .',
 'Extract entities and relationships from: We address the limitations of the well known Motion History Image -LRB- MHI -RRB- and propose a new Hierarchical Motion History Histogram -LRB- HMHH -RRB- feature to represent the motion information .',
 'Extract entities and relationships from: These signals could potentially be used to estimate the speed and related states of the vehicle .',
 'Extract entities and relationships from: Our approach yields phrasal and single word lexical paraphrases as well as syntactic paraphrases .',
 'Extract entities and relationships from: It is thus difficult to understand , improve , and accelerate them in a coherent framework .',
 'Extract entities and relationships from: We discuss maximum a posteriori estimation of continuous density hidden Markov models -LRB- CDHMM -RRB- .',
 'Extract entities and relationships from: We conducted experiments with an EBMT system .',
 'Extract entities and relationships from: In this paper we present a statistical profile of the Named Entity task , a specific information extraction task for which corpora in several languages are available .',
 'Extract entities and relationships from: We address the problem of populating object category detection datasets with dense , per-object 3D reconstructions , bootstrapped from class labels , ground truth figure-ground segmentations and a small set of keypoint annotations .',
 'Extract entities and relationships from: The system participated in all the tracks of the segmentation bakeoff -- PK-open , PK-closed , AS-open , AS-closed , HK-open , HK-closed , MSR-open and MSR - closed -- and achieved the state-of-the-art performance in MSR-open , MSR-close and PK-open tracks .',
 'Extract entities and relationships from: We investigate the utility of an algorithm for translation lexicon acquisition -LRB- SABLE -RRB- , used previously on a very large corpus to acquire general translation lexicons , when that algorithm is applied to a much smaller corpus to produce candidates for domain-specific translation lexicons .',
 'Extract entities and relationships from: In this paper , we present a syntax-based statistical machine translation system based on a probabilistic synchronous dependency insertion grammar .',
 'Extract entities and relationships from: In this paper , we focus on the minimal labeling problem -LRB- MLP -RRB- and we propose an algorithm to efficiently derive all the feasible base relations of a QCN .',
 "Extract entities and relationships from: For example , they '' attract '' people to approach them for satisfying certain needs -LRB- e.g. , vending machines could quench thirst -RRB- , or '' repel '' people to avoid them -LRB- e.g. , grass lawns -RRB- .",
 'Extract entities and relationships from: Conventional HMMs have weak duration constraints .',
 'Extract entities and relationships from: Since user interfaces work best when customized for particular applications , it is appropriator that no particular user interface styles or conventions are described in the TIPSTER Architecture specification .',
 'Extract entities and relationships from: It works in real-time , under heavy clutter , does not require a time consuming training stage , and can handle untextured objects .',
 'Extract entities and relationships from: In this paper , we develop a geometric framework for linear or nonlinear discriminant subspace learning and classification .',
 'Extract entities and relationships from: We introduce a new interactive corpus exploration tool called InfoMagnets .',
 'Extract entities and relationships from: In this paper , we address the problem of combining several language models -LRB- LMs -RRB- .',
 'Extract entities and relationships from: We primarily focus on the description of the syntactically motivated relations in discourse , basing our findings on the theoretical background of the Prague Dependency Treebank 2.0 and the Penn Discourse Treebank 2 .',
 'Extract entities and relationships from: The analysis in -LRB- Partee , 1984 -RRB- of quantified sentences , introduced by a temporal connective , gives the wrong truth-conditions when the temporal connective in the subordinate clause is before or after .',
 "Extract entities and relationships from: The method allows a user to explore a model of syntax-based statistical machine translation -LRB- MT -RRB- , to understand the model 's strengths and weaknesses , and to compare it to other MT systems .",
 'Extract entities and relationships from: To further improve performance , various error correction mechanisms have been developed , but in practice , most of them can not be relied on to predictably improve performance on unseen data ; indeed , depending upon the test set , they are as likely to degrade accuracy as to improve it .',
 'Extract entities and relationships from: In our method , unsupervised training is first used to train a phone n-gram model for a particular domain ; the output of recognition with this model is then passed to a phone-string classifier .',
 'Extract entities and relationships from: Using linearly interpolated language models , we find that blogs and movie subtitles are more relevant for language modeling of conversational telephone speech and obtain large reductions in out-of-vocabulary keywords .',
 'Extract entities and relationships from: The TIPSTER Architecture has been designed to enable a variety of different text applications to use a set of common text processing modules .',
 'Extract entities and relationships from: Experiments with the TREC 2003 and TREC 2004 QA tracks indicate that rankings produced by our metric correlate highly with official rankings , and that POURPRE outperforms direct application of existing metrics .',
 'Extract entities and relationships from: In this paper , we explore multilingual feature-level data sharing via Deep Neural Network -LRB- DNN -RRB- stacked bottleneck features .',
 'Extract entities and relationships from: Previous work has used monolingual parallel corpora to extract and generate paraphrases .',
 'Extract entities and relationships from: The corpus of human created extracts is created from a newspaper corpus and used as a test set .',
 'Extract entities and relationships from: While the first ones have been applied to reconstruct poorly-textured surfaces , they assume the availability of a 3D shape model prior to reconstruction .',
 'Extract entities and relationships from: Though some details of the CAS are particular to individual domains , the Comparator software is domain-independent , as is the CAS approach .',
 'Extract entities and relationships from: This paper presents a method for blind estimation of reverberation times in reverberant enclosures .',
 'Extract entities and relationships from: Such qualitative information can be formulated as a Qualitative Constraint Network -LRB- QCN -RRB- .',
 'Extract entities and relationships from: We propose a method of organizing reading materials for vocabulary learning .',
 'Extract entities and relationships from: This work presents a real-time system for multiple object tracking in dynamic scenes .',
 'Extract entities and relationships from: We present an efficient algorithm for the redundancy elimination problem : Given an underspecified semantic representation -LRB- USR -RRB- of a scope ambiguity , compute an USR with fewer mutually equivalent readings .',
 'Extract entities and relationships from: The connectionist component is trained either from patterns derived from the rules of a deterministic grammar .',
 'Extract entities and relationships from: We describe a set of supervised machine learning experiments centering on the construction of statistical models of WH-questions .',
 'Extract entities and relationships from: Motivated by the success of ensemble methods in machine learning and other areas of natural language processing , we developed a multi-strategy and multi-source approach to question answering which is based on combining the results from different answering agents searching for answers in multiple corpora .',
 'Extract entities and relationships from: A central problem of word sense disambiguation -LRB- WSD -RRB- is the lack of manually sense-tagged data required for supervised learning .',
 'Extract entities and relationships from: Following recent developments in the automatic evaluation of machine translation and document summarization , we present a similar approach , implemented in a measure called POURPRE , for automatically evaluating answers to definition questions .',
 'Extract entities and relationships from: We present an operable definition of focus which is argued to be of a cognito-pragmatic nature and explore how it is determined in discourse in a formalized manner .',
 'Extract entities and relationships from: The system will accept continuous speech , and will handle multiple speakers without explicit speaker enrollment .',
 'Extract entities and relationships from: In this paper , we evaluate an approach to automatically acquire sense-tagged training data from English-Chinese parallel corpora , which are then used for disambiguating the nouns in the SENSEVAL-2 English lexical sample task .',
 'Extract entities and relationships from: The paper also examines in detail which positive markers are most powerful and identifies a number of linguistic aspects as well as culture - and domain-related ones .',
 'Extract entities and relationships from: Moreover , the performance is even consistently better than those based on handcrafted rules .',
 'Extract entities and relationships from: The co-occurrence pattern , a combination of binary or local features , is more discriminative than individual features and has shown its advantages in object , scene , and action recognition .',
 'Extract entities and relationships from: We show that the crucial operation of consistency checking for such descriptions is NP-complete , and therefore probably intractable , but proceed to develop algorithms which can sometimes alleviate the unpleasant consequences of this intractability .',
 'Extract entities and relationships from: We propose an exact , general and efficient coarse-to-fine energy minimization strategy for semantic video segmenta-tion .',
 'Extract entities and relationships from: To avoid grammar coverage problems we use a fully-connected first-order statistical class grammar .',
 'Extract entities and relationships from: In this paper , for the first time , we propose to use a Neural Network classifier furnished by an SAE structure for detecting the errors made by a strong Automatic Speech Recognition -LRB- ASR -RRB- system .',
 'Extract entities and relationships from: In this paper I will argue for a model of grammatical processing that is based on uniform processing and knowledge sources .',
 'Extract entities and relationships from: This paper presents an unsupervised learning approach to building a non-English -LRB- Arabic -RRB- stemmer .',
 'Extract entities and relationships from: These two extensions work in cooperation to deal with the intolerable computational cost of BP caused by the huge number of existing labels .',
 'Extract entities and relationships from: This is achieved by solving a static Schrödinger equation instead of the corresponding static Hamilton-Jacobi equation in this setting .',
 'Extract entities and relationships from: It concerns a process of automatically labeling the image contents with a pre-defined set of keywords which are exploited to represent the image semantics .',
 'Extract entities and relationships from: A new exemplar-based framework unifying image completion , texture synthesis and image inpainting is presented in this work .',
 'Extract entities and relationships from: Recent advances in Automatic Speech Recognition technology have put the goal of naturally sounding dialog systems within reach .',
 'Extract entities and relationships from: A new algorithm for solving the three dimensional container packing problem is proposed in this paper .',
 'Extract entities and relationships from: While paraphrasing is critical both for interpretation and generation of natural language , current systems use manual or semi-automatic methods to collect paraphrases .',
 'Extract entities and relationships from: In contrast to many of the past efforts that make use of heuristic rules whose development requires intense knowledge engineering , our approach attempts to express the speech knowledge within a formal framework using well-defined mathematical tools .',
 'Extract entities and relationships from: It requires disjoint English phrases to be mapped to non-overlapping intervals in the French sentence .',
 'Extract entities and relationships from: HMHH not only provides rich motion information , but also remains computationally inexpensive .',
 'Extract entities and relationships from: `` To explain complex phenomena , an explanation system must be able to select information from a formal representation of domain knowledge , organize the selected information into multisentential discourse plans , and realize the discourse plans in text .',
 'Extract entities and relationships from: Deictic reference and feedback about the discourse are enabled .',
 'Extract entities and relationships from: Probabilistic models have been previously shown to be efficient and effective for modeling and recognition of human motion .',
 'Extract entities and relationships from: Instead of representing scene/object by a collection of isolated 3D features -LRB- usually points -RRB- , our algorithm uses a surface controlled by a small set of parameters .',
 'Extract entities and relationships from: Unlike previous video relighting methods , the approach does not assume regions of uniform albedo , which makes it applicable to richly textured scenes .',
 'Extract entities and relationships from: We present the first known empirical test of an increasingly common speculative claim , by evaluating a representative Chinese-to-English SMT model directly on word sense disambiguation performance , using standard WSD evaluation methodology and datasets from the Senseval-3 Chinese lexical sample task .',
 'Extract entities and relationships from: With the recent popularity of animated GIFs on social media , there is need for ways to index them with rich meta-data .',
 'Extract entities and relationships from: It enables us to select a concise set of reading texts -LRB- from a target corpus -RRB- that contains all the target vocabulary to be learned .',
 'Extract entities and relationships from: We describe a new approach which involves clustering subcategorization frame -LRB- SCF -RRB- distributions using the Information Bottleneck and nearest neighbour methods .',

#### Experimenting with t5 small model for NER

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("t5-small")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [ ]:
def tokenize_data(example):
    return tokenizer(
        example["input_texts"], text_target=example["output_texts"], truncation=True, padding="max_length", max_length=512
    )

In [ ]:
#tokenized_dataset = train_dataset.map(tokenize_data, batched=True)
train_tokenized = train_dataset.map(tokenize_data, batched=True)
eval_tokenized = eval_dataset.map(tokenize_data, batched=True)

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/67 [00:00<?, ? examples/s]

In [ ]:
train_dataset['output_texts']

In [ ]:
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

In [ ]:
training_args = Seq2SeqTrainingArguments(
    output_dir="./t5_triplet_extraction",
    evaluation_strategy="epoch",  # Evaluate at the end of each epoch
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    save_strategy="epoch",
    predict_with_generate=True,
    logging_dir="./logs",  # Log directory
    logging_steps=100,  # Log every 100 steps
    #report_to=["wandb", "console"],  # Log to Weights & Biases and console
    logging_first_step=True,  # Log at the first step
)

In [ ]:
trainer = Seq2SeqTrainer(
    model = model,
    args = training_args,
    train_dataset = train_tokenized,
    eval_dataset = eval_tokenized,
    tokenizer=tokenizer,
)

In [ ]:
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

TrainOutput(global_step=375, training_loss=0.5120221786499023, metrics={'train_runtime': 19355.5374, 'train_samples_per_second': 0.155, 'train_steps_per_second': 0.019, 'total_flos': 406025404416000.0, 'train_loss': 0.5120221786499023, 'epoch': 5.0})

In [ ]:
model_path = r'/content/gdrive/MyDrive/CS_546_Project_Dependencies/fine_tuned_t5_triplet_extraction'

In [ ]:
model.save_pretrained(model_path)
tokenizer.save_pretrained(model_path)

('/content/gdrive/MyDrive/CS_546_Project_Dependencies/fine_tuned_t5_triplet_extraction/tokenizer_config.json',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/fine_tuned_t5_triplet_extraction/special_tokens_map.json',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/fine_tuned_t5_triplet_extraction/spiece.model',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/fine_tuned_t5_triplet_extraction/added_tokens.json',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/fine_tuned_t5_triplet_extraction/tokenizer.json')

#### SciERC Experimental

In [ ]:
extracted_entities[0]

[[0, 0, 'Material'],
 [10, 10, 'OtherScientificTerm'],
 [17, 20, 'OtherScientificTerm']]

In [ ]:
relations[1]

[[29, 29, 31, 32, 'CONJUNCTION'],
 [48, 49, 51, 51, 'FEATURE-OF'],
 [54, 54, 51, 51, 'HYPONYM-OF']]

In [ ]:
entity_tag = [[[0, 0, 'Material'], [10, 10, 'OtherScientificTerm'], [17, 20, 'OtherScientificTerm']]]

In [ ]:
sentence = ['English', 'is', 'shown', 'to', 'be', 'trans-context-free', 'on', 'the', 'basis', 'of', 'coordinations', 'of', 'the', 'respectively', 'type', 'that', 'involve', 'strictly', 'syntactic', 'cross-serial', 'agreement', '.']

In [ ]:
for tag in entity_tag:
  start_idx = tag[0]
  end_idx = tag[1]
  if start_idx!=end_idx:
    print(sentence[start_idx:end_idx])
  else:
    print(sentence[start_idx])

English
coordinations
['strictly', 'syntactic', 'cross-serial']

In [ ]:
for example in scierc_train_df.iloc[0,:]:
  print(example)
  '''
  sentences = example["sentences"]
  for index in range(len(sentences)):
    sentence = sentences[index]
    ner = example["ner"][index]
    relation = example["relation"][index]
  '''

[[[17, 20], [23, 23]]]
[['English', 'is', 'shown', 'to', 'be', 'trans-context-free', 'on', 'the', 'basis', 'of', 'coordinations', 'of', 'the', 'respectively', 'type', 'that', 'involve', 'strictly', 'syntactic', 'cross-serial', 'agreement', '.'], ['The', 'agreement', 'in', 'question', 'involves', 'number', 'in', 'nouns', 'and', 'reflexive', 'pronouns', 'and', 'is', 'syntactic', 'rather', 'than', 'semantic', 'in', 'nature', 'because', 'grammatical', 'number', 'in', 'English', ',', 'like', 'grammatical', 'gender', 'in', 'languages', 'such', 'as', 'French', ',', 'is', 'partly', 'arbitrary', '.'], ['The', 'formal', 'proof', ',', 'which', 'makes', 'crucial', 'use', 'of', 'the', 'Interchange', 'Lemma', 'of', 'Ogden', 'et', 'al.', ',', 'is', 'so', 'constructed', 'as', 'to', 'be', 'valid', 'even', 'if', 'English', 'is', 'presumed', 'to', 'contain', 'grammatical', 'sentences', 'in', 'which', 'respectively', 'operates', 'across', 'a', 'pair', 'of', 'coordinate', 'phrases', 'one', 'of', 'whose', 'members', 'has', 'fewer', 'conjuncts', 'than', 'the', 'other', ';', 'it', 'thus', 'goes', 'through', 'whatever', 'the', 'facts', 'may', 'be', 'regarding', 'constructions', 'with', 'unequal', 'numbers', 'of', 'conjuncts', 'in', 'the', 'scope', 'of', 'respectively', ',', 'whereas', 'other', 'arguments', 'have', 'foundered', 'on', 'this', 'problem', '.']]
[[[0, 0, 'Material'], [10, 10, 'OtherScientificTerm'], [17, 20, 'OtherScientificTerm']], [[23, 23, 'Generic'], [29, 29, 'OtherScientificTerm'], [31, 32, 'OtherScientificTerm'], [42, 43, 'OtherScientificTerm'], [45, 45, 'Material'], [48, 49, 'OtherScientificTerm'], [51, 51, 'Material'], [54, 54, 'Material']], [[70, 71, 'Method'], [86, 86, 'Material']]]
[[], [[29, 29, 31, 32, 'CONJUNCTION'], [48, 49, 51, 51, 'FEATURE-OF'], [54, 54, 51, 51, 'HYPONYM-OF']], []]
J87-1003

#### Trying with OpenIE

In [ ]:
from openie import StanfordOpenIE

In [ ]:
# Initialize OpenIE
with StanfordOpenIE() as client:
    text = "Operation Blow to the Head was a Yemeni military operation against the militants in the insurgent Yemeni town of Sa'dah in the Saada Governorate "
    triples = client.annotate(text)

Starting server with command: java -Xmx8G -cp /root/.stanfordnlp_resources/stanford-corenlp-4.5.3/* edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000 -threads 5 -maxCharLength 100000 -quiet True -serverProperties corenlp_server-fb14d7195e9949a8.props -preload openie

PermanentlyFailedException: Timed out waiting for service to come alive.

In [ ]:
for triple in triples:
    print(triple)

#### Triplet Extraction Pipeline
<p> This consists of two modules, Coreference resolution + Triplet Extraction. <br>
  <ul>
    <li> Coreference resolution - Using fastcoref </li>
    <li> Triplet Extraction </li>
  </ul>
</p>

##### Coreference Resolution:
Trying with fastcoref

https://medium.com/@michaelwood33311/creating-accurate-ai-coreference-resolution-with-fastcoref-20f06044bdf9

In [ ]:
from spacy.tokens import Doc, Span
from fastcoref import FCoref

In [ ]:
def core_logic_part(document: Doc, coref: list[int], resolved: list[str], mention_span: Span):
    final_token = document[coref[1]]
    if final_token.tag_ in ["PRP$", "POS"]:
        resolved[coref[0]] = mention_span.text + "'s" + final_token.whitespace_
    else:
        resolved[coref[0]] = mention_span.text + final_token.whitespace_
    for i in range(coref[0] + 1, coref[1] + 1):
        resolved[i] = ""
    return resolved

In [ ]:
def get_span_noun_indices(doc: Doc, cluster: list[list[int]]) -> list[int]:
    try:
      spans = [doc[span[0]:span[1]+1] for span in cluster]
      spans_pos = [[token.pos_ for token in span] for span in spans]
      span_noun_indices = [i for i, span_pos in enumerate(spans_pos)
          if any(pos in span_pos for pos in ['NOUN', 'PROPN'])]
      return span_noun_indices
    except Exception as e:
      print(f'Error received while getting span noun indices. {e}. Returning empty list')
      return []

In [ ]:
def get_cluster_head(doc: Doc, cluster: list[list[int]], noun_indices: list[int]):
    head_idx = noun_indices[0]
    head_start, head_end = cluster[head_idx]
    head_span = doc[head_start:head_end+1]
    return head_span, [head_start, head_end]

In [ ]:
def is_containing_other_spans(span: list[int], all_spans: list[list[int]]):
    return any([s[0] >= span[0] and s[1] <= span[1] and s != span for s in all_spans])

In [ ]:
def improved_replace_corefs(document, clusters):
    resolved = list(tok.text_with_ws for tok in document)
    all_spans = [span for cluster in clusters for span in cluster]  # flattened list of all spans

    for cluster in clusters:
        noun_indices = get_span_noun_indices(document, cluster)

        if noun_indices:
            mention_span, mention = get_cluster_head(document, cluster, noun_indices)

            for coref in cluster:
                if coref != mention and not is_containing_other_spans(coref, all_spans):
                    core_logic_part(document, coref, resolved, mention_span)

    return "".join(resolved)

In [ ]:
def get_fast_cluster_spans(doc, clusters):
    fast_clusters = []
    for cluster in clusters:
        new_group = []
        for tuple in cluster:
            #print(type(tuple), tuple)
            (start, end) = tuple
            #print("start, end", start, end)
            span = doc.char_span(start, end)
            #print('span', span.start, span.end)
            new_group.append([span.start, span.end-1])
        fast_clusters.append(new_group)
    return fast_clusters

In [ ]:
def get_fastcoref_clusters(doc, text, fcoref_model):
  try:
    preds = fcoref_model.predict(texts=[text])
    fast_clusters = preds[0].get_clusters(as_strings=False)
    fast_cluster_spans = get_fast_cluster_spans(doc, fast_clusters)
  except Exception as e:
    print(f'Error received while getting coreference clusters. {e}. Returning original text')
    return text
  return fast_cluster_spans

###### Testing - Inference

In [ ]:
nlp = spacy.load('en_core_web_sm')
nlp_scispacy = spacy.load('en_core_sci_md')

/usr/local/lib/python3.11/dist-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

In [ ]:
fcoref_model = FCoref(device=device)

In [ ]:
test = "We want to take our code and create a game. Let's remind ourselves how to do that."
text5 = "Jennifer Doudna discovered the CRISPR-Cas9 system. She later won a Nobel Prize."
text5_a = "Jennifer Doudna and Emmanuelle Charpentier discovered the CRISPR-Cas9 system. She later won a Nobel Prize."
string = "Cardiovascular disease (CVD) is the leading cause of death. It is fatal for children."

In [ ]:
domain_data = 'Hepatocyte nuclear factor-6: associations between genetic variability and type II diabetes and between genetic variability and estimates of insulin secretion. The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.'

In [ ]:
doc = nlp(string)
doc_scispacy = nlp_scispacy(string)

In [ ]:
fcoref_model.predict([string])

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

[CorefResult(text="Cardiovascular disease (CVD) is the leading cause ...", clusters=[['Cardiovascular disease (CVD)', 'It']])]

In [ ]:
clusters_base = get_fastcoref_clusters(doc, string, fcoref_model)
clusters_scispacy = get_fastcoref_clusters(doc_scispacy, string, fcoref_model)

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
coref_text_base = improved_replace_corefs(doc, clusters_base)
coref_text_scispacy = improved_replace_corefs(doc_scispacy, clusters_scispacy)

##### Triplet Extraction

Trying with REBEL: Relation Extraction With End-To-End Language Generation.

###### Starting with inference on random queries

In [ ]:
text = "English is shown to be trans-context-free."
text2 = "English is a language that is trans-context-free."
text3 = "Albert Einstein was a physicist who studied at ETH Zurich."
text4 = "The CRISPR-Cas9 system, discovered by Jennifer Doudna and Emmanuelle Charpentier, has revolutionized gene editing techniques in molecular biology."
text4_a = "The CRISPR-Cas9 system was discovered by Jennifer Doudna and Emmanuelle Charpentier"
text4_b = "The CRISPR-Cas9 system has revolutionized gene editing techniques in molecular biology."

In [ ]:
text5 = "Jennifer Doudna discovered the CRISPR-Cas9 system. She later won a Nobel Prize."
text5_a = "Jennifer Doudna and Emmanuelle Charpentier discovered the CRISPR-Cas9 system. She later won a Nobel Prize."

In [ ]:
text6 = "Chandragupta Maurya was the founder of the Maurya Empire and dynasty, based in Magadha. His rise to power began after the death of Alaxander in 323 BCE."
text6_a = "Chandragupta Maurya was the founder of the Maurya Empire and dynasty. His rise to power began after the death of Alaxander in 323 BCE."
text6_b = "Chandragupta Maurya's rise to power began after the death of Alaxander in 323 BCE."
text6_c = "Chandragupta Maurya's rise to power began in 323 BCE."
text6_d = "Chandragupta Maurya's rise to power began after he won the war."

In [ ]:
test_text = 'Elon Musk co-founded SpaceX with a vision to colonize Mars.'
test_text_1 = 'The Taj Mahal was built by Akbar.'

In [ ]:
test_txt_1 = text3 +" "+text4_a
test_txt_2 = text4_a + " " + text3

In [ ]:
model_name = "Babelscape/rebel-large"
rebel_tokenizer = AutoTokenizer.from_pretrained(model_name)
rebel_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/1.23k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/344 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

In [ ]:
inputs = rebel_tokenizer(test_text_1, return_tensors="pt", max_length=1024, truncation=False)

In [ ]:
inputs = {key: value.to(device) for key, value in inputs.items()}

In [ ]:
inputs

{'input_ids': tensor([[    0,   133, 17335,  3634,   337,    21,  1490,    30,  3773,  4901,
              4,     2]]),
 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
outputs = rebel_model.generate(**inputs)
extracted_text = rebel_tokenizer.decode(outputs[0], skip_special_tokens=True)

In [ ]:
extracted_text

' Taj Mahal  Akbar  owned by  Akbar  Taj Mahal  owner of'

<table style="width:100%">
  <tr>
    <th>Var</th>
    <th style="width:70%">Input</th>
    <th style="width:25%">Triplets</th>
  </tr>
  <tr>
    <td>6</td>
    <td>Chandragupta Maurya was the founder of the Maurya Empire and dynasty, based in Magadha.<br>His rise to power began after the death of Alaxander in 323 BCE.</td>
    <td>Maurya Empire  Chandragupta Maurya  founded by  Magadha  capital  Magadha  Maurya Empire  capital of</td>
  </tr>
  <tr>
    <td>6_a</td>
    <td>Chandragupta Maurya was the founder of the Maurya Empire and dynasty.<br>His rise to power began after the death of Alaxander in 323 BCE.</td>
    <td> Maurya Empire  Chandragupta Maurya  founded by </td>
  </tr>
  <tr>
    <td>6_b</td>
    <td>Chandragupta Maurya's rise to power began after the death of Alaxander in 323 BCE.</td>
    <td>Alaxander  Chandragupta Maurya  replaced by</td>
  </tr>
  <tr>
    <td>6_c</td>
    <td>Chandragupta Maurya's rise to power began in 323 BCE.</td>
    <td>Chandragupta Maurya  rise to power  conflict</td>
  </tr>
  <tr>
    <td>1</td>
    <td>The Taj Mahal was built by Picasso.</td>
    <td> Taj Mahal  Picasso  creator  Picasso  Taj Mahal  notable work</td>
  </tr>
    <tr>
    <td>2</td>
    <td>The Taj Mahal was built by Akbar.</td>
    <td> Taj Mahal  Akbar  owned by  Akbar  Taj Mahal  owner of</td>
  </tr>
</table>

##### Component Integration + BioRED finetune

In [ ]:
def transform_biored_to_rebel_format_updated(dataset):
    """
    Transforms the BioRED dataset into REBEL-compatible format with consolidated triplets.

    Args:
        dataset: The BioRED dataset as a list of entries.

    Returns:
        List of dictionaries in the REBEL format.
    """
    rebel_data = []

    for entry in dataset:
        # Concatenate title and abstract
        title = entry['passages'][0]['text'][0]  # Title
        abstract = entry['passages'][1]['text'][0]  # Abstract
        input_text = f"{title} {abstract}"

        # Map entity IDs to entity text
        entity_map = {entity['concept_id']: entity['text'][0] for entity in entry['entities']}

        # Generate triplets and group by head entity
        triplet_groups = {}
        for relation in entry['relations']:
            concept_1 = relation['concept_1']
            concept_2 = relation['concept_2']
            rel_type = relation['type']

            # Ensure both entities exist
            if concept_1 in entity_map and concept_2 in entity_map:
                head = entity_map[concept_1]
                tail = entity_map[concept_2]
                relation_triplet = f"{tail} <obj> {rel_type}"

                # Group relations by head entity
                if head not in triplet_groups:
                    triplet_groups[head] = []
                triplet_groups[head].append(relation_triplet)

        # Consolidate triplets for each head entity
        consolidated_triplets = []
        for head, relations in triplet_groups.items():
            relation_strings = " <subj> ".join(relations)
            consolidated_triplets.append(f"<triplet> {head} <subj> {relation_strings}")

        # Only include rows with valid triplets
        if consolidated_triplets:
            rebel_data.append({"input": input_text, "output": " ".join(consolidated_triplets)})

    return rebel_data

In [ ]:
def perform_coreference_resolution(text):
    doc = nlp_scispacy(text)
    clusters = get_fastcoref_clusters(doc, text, fcoref_model)
    coref_text = improved_replace_corefs(doc, clusters)
    return coref_text

In [ ]:
biored_df = load_dataset("bigbio/biored",trust_remote_code=True)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

biored.py:   0%|          | 0.00/13.9k [00:00<?, ?B/s]

bigbiohub.py:   0%|          | 0.00/19.3k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/2.19M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

In [ ]:
biored_train_df = biored_df['train']

In [ ]:
biored_train_df

Dataset({
    features: ['pmid', 'passages', 'entities', 'relations'],
    num_rows: 400
})

In [ ]:
biored_train_df['passages'][0]

[{'type': 'title',
  'text': ['Hepatocyte nuclear factor-6: associations between genetic variability and type II diabetes and between genetic variability and estimates of insulin secretion.'],
  'offsets': [[0, 158]]},
 {'type': 'abstract',
  'text': ['The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.'],
  'offsets': [[159, 1797]]}]

In [ ]:
rebel_formatted_data_updated = transform_biored_to_rebel_format_updated(biored_train_df)

In [ ]:
rebel_formatted_df = pd.DataFrame(rebel_formatted_data_updated)

In [ ]:
#nlp = spacy.load('en_core_web_sm')
nlp_scispacy = spacy.load('en_core_sci_md')

/usr/local/lib/python3.11/dist-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

In [ ]:
#fcoref_model = FCoref(device='cpu')
fcoref_model = FCoref(device=device)
#Tesla T4

In [ ]:
rebel_formatted_df['input_coref'] = rebel_formatted_df['input'].apply(perform_coreference_resolution)

In [ ]:
test_rebel_df = copy.deepcopy(rebel_formatted_df)

In [ ]:
test_rebel_df.to_csv('test_rebel_df.csv', index=False)

In [ ]:
rebel_formatted_df = pd.read_csv('test_rebel_df.csv')

In [ ]:
rebel_formatted_df['input_coref']

0      Hepatocyte nuclear factor-6: associations betw...
1      Langerin, a novel C-type lectin specific to La...
2      Founder mutations in the BRCA1 gene in Polish ...
3      Apomorphine: an underutilized therapy for Park...
4      Rab6c, a new member of the rab gene family, is...
                             ...
389    Cholecystokinin-octapeptide restored morphine-...
390    Comparison of effects of isotonic sodium chlor...
391    Prevention of etomidate-induced myoclonus: whi...
392    Testosterone ameliorates streptozotocin-induce...
393    Rhabdomyolysis in a hepatitis C virus infected...
Name: input_coref, Length: 394, dtype: object

In [ ]:
biored_test_df = biored_df['test']

In [ ]:
biored_test_df

Dataset({
    features: ['pmid', 'passages', 'entities', 'relations'],
    num_rows: 100
})

In [ ]:
biored_test_df['passages'][0]

[{'type': 'title',
  'text': ['A novel SCN5A mutation manifests as a malignant form of long QT syndrome with perinatal onset of tachycardia/bradycardia.'],
  'offsets': [[0, 121]]},
 {'type': 'abstract',
  'text': ['OBJECTIVE: Congenital long QT syndrome (LQTS) with in utero onset of the rhythm disturbances is associated with a poor prognosis. In this study we investigated a newborn patient with fetal bradycardia, 2:1 atrioventricular block and ventricular tachycardia soon after birth. METHODS: Mutational analysis and DNA sequencing were conducted in a newborn. The 2:1 atrioventricular block improved to 1:1 conduction only after intravenous lidocaine infusion or a high dose of mexiletine, which also controlled the ventricular tachycardia. RESULTS: A novel, spontaneous LQTS-3 mutation was identified in the transmembrane segment 6 of domain IV of the Na(v)1.5 cardiac sodium channel, with a G-->A substitution at codon 1763, which changed a valine (GTG) to a methionine (ATG). The proband was heterozygous but the mutation was absent in the parents and the sister. Expression of this mutant channel in tsA201 mammalian cells by site-directed mutagenesis revealed a persistent tetrodotoxin-sensitive but lidocaine-resistant current that was associated with a positive shift of the steady-state inactivation curve, steeper activation curve and faster recovery from inactivation. We also found a similar electrophysiological profile for the neighboring V1764M mutant. But, the other neighboring I1762A mutant had no persistent current and was still associated with a positive shift of inactivation. CONCLUSIONS: These findings suggest that the Na(v)1.5/V1763M channel dysfunction and possible neighboring mutants contribute to a persistent inward current due to altered inactivation kinetics and clinically congenital LQTS with perinatal onset of arrhythmias that responded to lidocaine and mexiletine.'],
  'offsets': [[122, 1815]]}]

In [ ]:
rebel_test_data = transform_biored_to_rebel_format_updated(biored_test_df)

In [ ]:
rebel_test_df = pd.DataFrame(rebel_test_data)

In [ ]:
rebel_test_df['input_coref'] = rebel_test_df['input'].apply(perform_coreference_resolution)

In [ ]:
rebel_df_test_data = copy.deepcopy(rebel_test_df)

In [ ]:
rebel_df_test_data['input_coref']

0     A novel SCN5A mutation manifests as a malignan...
1     Allelic expression imbalance of human mu opioi...
2     Genetic polymorphisms in the carbonyl reductas...
3     Debrisoquine phenotype and the pharmacokinetic...
4     The first founder DGUOK mutation associated wi...
                            ...
95    Delirium in a patient with toxic flecainide pl...
96    Depression, impulsiveness, sleep, and memory i...
97    A comparison of severe hemodynamic disturbance...
98    Effects of dehydroepiandrosterone in amphetami...
99    Aconitine-induced Ca2+ overload causes arrhyth...
Name: input_coref, Length: 100, dtype: object

In [ ]:
rebel_df_test_data.to_csv('rebel_df_test_data.csv', index=False)

In [ ]:
#rebel_df_test_data = pd.read_csv('/content/rebel_df_test_data.csv')

In [ ]:
rebel_df_test_data[['input_coref','output']]

,input_coref,output
0,A novel SCN5A mutation manifests as a malignan...,<triplet> bradycardia <subj> Na(v)1.5 <obj> As...
1,Allelic expression imbalance of human mu opioi...,<triplet> OPRM1 <subj> pain <obj> Association ...
2,Genetic polymorphisms in the carbonyl reductas...,<triplet> cardiotoxic <subj> doxorubicinol <ob...
3,Debrisoquine phenotype and the pharmacokinetic...,<triplet> beta-1 adrenoceptor <subj> metoprolo...
4,The first founder DGUOK mutation associated wi...,<triplet> dGK <subj> mitochondrial DNA depleti...
...,...,...
95,Delirium in a patient with toxic flecainide pl...,<triplet> sodium <subj> delirium <obj> Associa...
96,"Depression, impulsiveness, sleep, and memory i...",<triplet> ecstasy <subj> sleep disturbance <ob...
97,A comparison of severe hemodynamic disturbance...,<triplet> propofol <subj> bradycardia <obj> Po...
98,Effects of dehydroepiandrosterone in amphetami...,<triplet> DHEA <subj> catalepsy <obj> Positive...
99,Aconitine-induced Ca2+ overload causes arrhyth...,<triplet> Na(+) <subj> cardiotoxicity <obj> As...

In [ ]:
model_path = '/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118'

In [ ]:
model_name = "Babelscape/rebel-large"

In [ ]:
rebel_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
#rebel_model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

In [ ]:
#rebel_tokenizer = AutoTokenizer.from_pretrained(model_path)

In [ ]:
rebel_tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/1.23k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/344 [00:00<?, ?B/s]

def preprocess_function(examples):
    # Tokenize the input
    model_inputs = rebel_tokenizer(
        examples["input_coref"],  # Source text
        max_length=512,     # Limit to model's max length
        truncation=True,     # Truncate if longer than max length
        padding="max_length"
    )

    # Tokenize the output
    with rebel_tokenizer.as_target_tokenizer():
        labels = rebel_tokenizer(
            examples["output"],  # Target text
            max_length=512,      # Limit to model's max length
            truncation=True,     # Truncate if longer than max length
            padding="max_length"
        )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
def preprocess_function(examples):
    # Tokenize the input (source text)
    model_inputs = rebel_tokenizer(
        text = examples["input_coref"],  # Source text
        max_length = 512,           # Limit to model's max length
        truncation = True,          # Truncate if longer than max length
        padding = "max_length"
    )

    # Tokenize the output (target text)
    labels = rebel_tokenizer(
        text = examples["output"],  # Target text
        max_length = 512,                 # Limit to model's max length
        truncation = True,                # Truncate if longer than max length
        padding = "max_length"
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

##### Latest finetuning of BioRED - 01/09/2025

In [ ]:
#rebel_df_latest = pd.read_csv('/content/Groq_BioRED_Triplets_Main.csv',encoding='cp1252')
biored_train_df = pd.read_csv('/content/gdrive/MyDrive/CS_546_Project_Dependencies/RE_Finetuning/Train_BioRED_Triplets_Annotated.csv')

In [ ]:
biored_train_df = biored_train_df.rename(columns={'Passage':'input_coref','Triplets':'output'})

In [ ]:
biored_train_df.head()

,input_coref,output
0,Hepatocyte nuclear factor-6: associations betw...,<triplet> Hepatocyte nuclear factor-6 <subj> v...
1,"Langerin, a novel C-type lectin specific to La...",<triplet> Langerin <subj> C-type lectin <obj> ...
2,Founder mutations in the BRCA1 gene in Polish ...,<triplet> BRCA1 gene <subj> founder mutations ...
3,Apomorphine: an underutilized therapy for Park...,<triplet> Subcutaneous apomorphine <subj> moto...
4,"Rab6c, a new member of the rab gene family, is...",<triplet> Rab6c <subj> drug resistance <obj> i...

In [ ]:
biored_train_df.isna().sum()

input_coref    0
output         0
dtype: int64

In [ ]:
biored_train_df[biored_train_df.output.isna()==True]

                                           input_coref output
179  Identities, frequencies and origins of TMC1 mu...    NaN

##### Inference with Relik

In [ ]:
!pip install relik --target=$package_directory

Collecting relik
  Downloading relik-1.0.7-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 2.2 MB/s eta 0:00:00
Collecting torch==2.3.1 (from relik)
  Downloading torch-2.3.1-cp311-cp311-manylinux1_x86_64.whl.metadata (26 kB)
Collecting transformers<4.42,>=4.41 (from transformers[sentencepiece]<4.42,>=4.41->relik)
  Downloading transformers-4.41.2-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 2.7 MB/s eta 0:00:00
Collecting rich<14.0.0,>=13.0.0 (from relik)
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting scikit-learn<1.6,>=1.5 (from relik)
  Downloading scikit_learn-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting overrides<7.9,>=7.4 (from relik)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting art==6.2 (from relik)
  Downloading art-6.2-py3-none-any.whl.metadata (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 kB 4.6 MB/s eta 0:00:00
Collecting pprintpp==0.4.0 (from relik)
  Downloading pprintpp-0.4.0-py2.py3-none-any.whl.metadata (7.9 kB)
Collecting colorama==0.4.6 (from relik)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting termcolor==2.4.0 (from relik)
  Downloading termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Collecting spacy<3.8,>=3.7 (from relik)
  Downloading spacy-3.7.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting typer<0.13,>=0.12 (from relik)
  Downloading typer-0.12.5-py3-none-any.whl.metadata (15 kB)
Collecting lightning<2.4,>=2.3 (from relik)
  Downloading lightning-2.3.3-py3-none-any.whl.metadata (35 kB)
Collecting datasets<2.15,>=2.13 (from relik)
  Downloading datasets-2.14.7-py3-none-any.whl.metadata (19 kB)
Collecting hydra-core<1.4,>=1.3 (from relik)
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting hydra-colorlog (from relik)
  Downloading hydra_colorlog-1.2.0-py3-none-any.whl.metadata (949 bytes)
Collecting wandb<0.18,>=0.15 (from relik)
  Downloading wandb-0.17.9-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting filelock (from torch==2.3.1->relik)
  Downloading filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.8.0 (from torch==2.3.1->relik)
  Downloading typing_extensions-4.14.0-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.3.1->relik)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.3.1->relik)
  Downloading networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch==2.3.1->relik)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch==2.3.1->relik)
  Downloading fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.3.1->relik)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.3.1->relik)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.3.1->relik)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.3.1->relik)
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.3.1->relik)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.3.1->relik)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.3.1->relik)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.3.1->relik)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.3.1->relik)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.3.1->relik)
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.3.1->relik)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.3.1 (from torch==2.3.1->relik)
  Downloading triton-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.3.1->relik)
  Downloading nvidia_nvjitlink_cu12-12.9.86-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting numpy>=1.17 (from datasets<2.15,>=2.13->relik)
  Downloading numpy-2.3.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 3.7 MB/s eta 0:00:00
Collecting pyarrow>=8.0.0 (from datasets<2.15,>=2.13->relik)
  Downloading pyarrow-20.0.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting pyarrow-hotfix (from datasets<2.15,>=2.13->relik)
  Downloading pyarrow_hotfix-0.7-py3-none-any.whl.metadata (3.6 kB)
Collecting dill<0.3.8,>=0.3.0 (from datasets<2.15,>=2.13->relik)
  Downloading dill-0.3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting pandas (from datasets<2.15,>=2.13->relik)
  Downloading pandas-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 6.0 MB/s eta 0:00:00
Collecting requests>=2.19.0 (from datasets<2.15,>=2.13->relik)
  Downloading requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm>=4.62.1 (from datasets<2.15,>=2.13->relik)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.2 MB/s eta 0:00:00
Collecting xxhash (from datasets<2.15,>=2.13->relik)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess (from datasets<2.15,>=2.13->relik)
  Downloading multiprocess-0.70.18-py311-none-any.whl.metadata (7.5 kB)
Collecting fsspec (from torch==2.3.1->relik)
  Downloading fsspec-2023.10.0-py3-none-any.whl.metadata (6.8 kB)
Collecting aiohttp (from datasets<2.15,>=2.13->relik)
  Downloading aiohttp-3.12.13-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting huggingface-hub<1.0.0,>=0.14.0 (from datasets<2.15,>=2.13->relik)
  Downloading huggingface_hub-0.33.0-py3-none-any.whl.metadata (14 kB)
Collecting packaging (from datasets<2.15,>=2.13->relik)
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml>=5.1 (from datasets<2.15,>=2.13->relik)
  Downloading PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting omegaconf<2.4,>=2.2 (from hydra-core<1.4,>=1.3->relik)
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting antlr4-python3-runtime==4.9.* (from hydra-core<1.4,>=1.3->relik)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<2.4,>=2.3->relik)
  Downloading lightning_utilities-0.14.3-py3-none-any.whl.metadata (5.6 kB)
Collecting packaging (from datasets<2.15,>=2.13->relik)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting torchmetrics<3.0,>=0.7.0 (from lightning<2.4,>=2.3->relik)
  Downloading torchmetrics-1.7.3-py3-none-any.whl.metadata (21 kB)
Collecting pytorch-lightning (from lightning<2.4,>=2.3->relik)
  Downloading pytorch_lightning-2.5.1.post0-py3-none-any.whl.metadata (20 kB)
Collecting markdown-it-py>=2.2.0 (from rich<14.0.0,>=13.0.0->relik)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich<14.0.0,>=13.0.0->relik)
  Downloading pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)
Collecting scipy>=1.6.0 (from scikit-learn<1.6,>=1.5->relik)
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.0 MB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn<1.6,>=1.5->relik)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn<1.6,>=1.5->relik)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy<3.8,>=3.7->relik)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy<3.8,>=3.7->relik)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy<3.8,>=3.7->relik)
  Downloading murmurhash-1.0.13-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy<3.8,>=3.7->relik)
  Downloading cymem-2.0.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.5 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy<3.8,>=3.7->relik)
  Downloading preshed-3.0.10-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.4 kB)
Collecting thinc<8.3.0,>=8.2.2 (from spacy<3.8,>=3.7->relik)
  Downloading thinc-8.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy<3.8,>=3.7->relik)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy<3.8,>=3.7->relik)
  Downloading srsly-2.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy<3.8,>=3.7->relik)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy<3.8,>=3.7->relik)
  Downloading weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy<3.8,>=3.7->relik)
  Downloading pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.0/68.0 kB 4.7 MB/s eta 0:00:00
Collecting setuptools (from spacy<3.8,>=3.7->relik)
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy<3.8,>=3.7->relik)
  Downloading langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Collecting regex!=2019.12.17 (from transformers<4.42,>=4.41->transformers[sentencepiece]<4.42,>=4.41->relik)
  Downloading regex-2024.11.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 2.2 MB/s eta 0:00:00
Collecting tokenizers<0.20,>=0.19 (from transformers<4.42,>=4.41->transformers[sentencepiece]<4.42,>=4.41->relik)
  Downloading tokenizers-0.19.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers<4.42,>=4.41->transformers[sentencepiece]<4.42,>=4.41->relik)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting sentencepiece!=0.1.92,>=0.1.91 (from transformers[sentencepiece]<4.42,>=4.41->relik)
  Downloading sentencepiece-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting protobuf (from transformers[sentencepiece]<4.42,>=4.41->relik)
  Downloading protobuf-6.31.1-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting click>=8.0.0 (from typer<0.13,>=0.12->relik)
  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
Collecting shellingham>=1.3.0 (from typer<0.13,>=0.12->relik)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting docker-pycreds>=0.4.0 (from wandb<0.18,>=0.15->relik)
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting gitpython!=3.1.29,>=1.0.0 (from wandb<0.18,>=0.15->relik)
  Downloading GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)
Collecting platformdirs (from wandb<0.18,>=0.15->relik)
  Downloading platformdirs-4.3.8-py3-none-any.whl.metadata (12 kB)
Collecting protobuf (from transformers[sentencepiece]<4.42,>=4.41->relik)
  Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting psutil>=5.0.0 (from wandb<0.18,>=0.15->relik)
  Downloading psutil-7.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting sentry-sdk>=1.0.0 (from wandb<0.18,>=0.15->relik)
  Downloading sentry_sdk-2.30.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting setproctitle (from wandb<0.18,>=0.15->relik)
  Downloading setproctitle-1.3.6-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting colorlog (from hydra-colorlog->relik)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Collecting six>=1.4.0 (from docker-pycreds>=0.4.0->wandb<0.18,>=0.15->relik)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp->datasets<2.15,>=2.13->relik)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets<2.15,>=2.13->relik)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting attrs>=17.3.0 (from aiohttp->datasets<2.15,>=2.13->relik)
  Downloading attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->datasets<2.15,>=2.13->relik)
  Downloading frozenlist-1.7.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets<2.15,>=2.13->relik)
  Downloading multidict-6.4.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp->datasets<2.15,>=2.13->relik)
  Downloading propcache-0.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets<2.15,>=2.13->relik)
  Downloading yarl-1.20.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.9/73.9 kB 4.5 MB/s eta 0:00:00
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.29,>=1.0.0->wandb<0.18,>=0.15->relik)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting hf-xet<2.0.0,>=1.1.2 (from huggingface-hub<1.0.0,>=0.14.0->datasets<2.15,>=2.13->relik)
  Downloading hf_xet-1.1.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (879 bytes)
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy<3.8,>=3.7->relik)
  Downloading language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.0.0->relik)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8,>=3.7->relik)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8,>=3.7->relik)
  Downloading pydantic_core-2.33.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting typing-inspection>=0.4.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8,>=3.7->relik)
  Downloading typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.19.0->datasets<2.15,>=2.13->relik)
  Downloading charset_normalizer-3.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from requests>=2.19.0->datasets<2.15,>=2.13->relik)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.19.0->datasets<2.15,>=2.13->relik)
  Downloading urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests>=2.19.0->datasets<2.15,>=2.13->relik)
  Downloading certifi-2025.6.15-py3-none-any.whl.metadata (2.4 kB)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.2.2->spacy<3.8,>=3.7->relik)
  Downloading blis-0.7.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.3.0,>=8.2.2->spacy<3.8,>=3.7->relik)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.17 (from datasets<2.15,>=2.13->relik)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.7 MB/s eta 0:00:00
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy<3.8,>=3.7->relik)
  Downloading cloudpathlib-0.21.1-py3-none-any.whl.metadata (14 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.1.0->spacy<3.8,>=3.7->relik)
  Downloading smart_open-7.1.0-py3-none-any.whl.metadata (24 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.3.1->relik)
  Downloading MarkupSafe-3.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
INFO: pip is looking at multiple versions of multiprocess to determine which version is compatible with other requirements. This could take a while.
Collecting multiprocess (from datasets<2.15,>=2.13->relik)
  Downloading multiprocess-0.70.17-py311-none-any.whl.metadata (7.2 kB)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
  Downloading multiprocess-0.70.15-py311-none-any.whl.metadata (7.2 kB)
Collecting python-dateutil>=2.8.2 (from pandas->datasets<2.15,>=2.13->relik)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->datasets<2.15,>=2.13->relik)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->datasets<2.15,>=2.13->relik)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.3.1->relik)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb<0.18,>=0.15->relik)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8,>=3.7->relik)
  Downloading marisa_trie-1.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting wrapt (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8,>=3.7->relik)
  Downloading wrapt-1.17.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Downloading relik-1.0.7-py3-none-any.whl (222 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.1/222.1 kB 13.9 MB/s eta 0:00:00
Downloading art-6.2-py3-none-any.whl (601 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 601.8/601.8 kB 25.7 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading pprintpp-0.4.0-py2.py3-none-any.whl (16 kB)
Downloading termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Downloading torch-2.3.1-cp311-cp311-manylinux1_x86_64.whl (779.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 779.2/779.2 MB 2.3 MB/s eta 0:00:00

In [ ]:
from relik import Relik
from relik.inference.data.objects import RelikOutput

AttributeError: 'OutStream' object has no attribute 'watch_fd_thread'

In [ ]:
relik = Relik.from_pretrained("sapienzanlp/relik-entity-linking-large")
relik_out: RelikOutput = relik("Michael Jordan was one of the best players in the NBA.")

##### Initial training- Older code

In [ ]:
#dataset = Dataset.from_pandas(rebel_formatted_df[['input_coref','output']])
dataset = Dataset.from_pandas(biored_train_df[['input_coref','output']])

In [ ]:
dataset

Dataset({
    features: ['input_coref', 'output'],
    num_rows: 443
})

In [ ]:
tokenized_dataset = dataset.map(preprocess_function,batched=True)

Map:   0%|          | 0/443 [00:00<?, ? examples/s]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#train_df, val_df = train_test_split(rebel_formatted_df, test_size=0.2, random_state=42)
train_df, val_df = train_test_split(biored_train_df, test_size=0.2, random_state=42)

In [ ]:
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

In [ ]:
tokenized_train_dataset = train_dataset.map(preprocess_function, batched=True)
tokenized_val_dataset = val_dataset.map(preprocess_function, batched=True)

Map:   0%|          | 0/354 [00:00<?, ? examples/s]

Map:   0%|          | 0/89 [00:00<?, ? examples/s]

In [ ]:
tokenized_train_dataset

Dataset({
    features: ['input_coref', 'output', '__index_level_0__', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 354
})

In [ ]:
from sklearn.metrics import precision_recall_fscore_support

In [ ]:
def extract_triplets(decoded_string):
    decoded_str_copy = decoded_string
    if '<s>' in decoded_string:
      decoded_str_copy = ''.join(decoded_string.split('<s>')[1:])
      decoded_str_copy = decoded_str_copy.split('</s>')[0]

    triplets = []
    parts = decoded_str_copy.split("<triplet>")

    for part in parts[1:]:  # Skip the first empty split
        # Extract the head entity (the first part before <subj>)
        head, *relations = part.split("<subj>")
        head = head.strip()

        # Parse each <subj> and <obj> pair
        for relation in relations:
            if "<obj>" in relation:
                subj, obj = relation.split("<obj>", 1)
                triplets.append((head, subj.strip(), obj.strip()))

    return triplets

In [ ]:
def compute_metrics(eval_preds):
    """
    Compute Precision, Recall, and F1-Score for triplet extraction.
    """
    # Unpack predictions and labels
    predictions, labels = eval_preds

    # Decode predictions and labels into strings
    decoded_predictions = [rebel_tokenizer.decode(pred, skip_special_tokens=False) for pred in predictions]
    decoded_labels = [rebel_tokenizer.decode(label, skip_special_tokens=False) for label in labels]

    '''
    print(f'Length of predictions list: {len(decoded_predictions)}')
    print(f'Length of labels list: {len(decoded_labels)}')

    # Debugging print to inspect outputs
    print("=== Sample Predictions ===")
    for i, pred in enumerate(decoded_predictions[:5]):  # Print first 5 predictions
        print(f"Prediction {i+1}: {pred}")

    print("\n=== Sample Ground Truth Labels ===")
    for i, label in enumerate(decoded_labels[:5]):  # Print first 5 ground truths
        print(f"Ground Truth {i+1}: {label}")

    return {"precision": 0.0, "recall": 0.0, "f1": 0.0}
    '''
    # Triplet extraction and metric computation
    tp, fp, fn = 0, 0, 0
    for pred, label in zip(decoded_predictions, decoded_labels):
        predicted_triplets = set(extract_triplets(pred))
        ground_truth_triplets = set(extract_triplets(label))

        # Compute True Positives, False Positives, and False Negatives
        tp += len(predicted_triplets & ground_truth_triplets)
        fp += len(predicted_triplets - ground_truth_triplets)
        fn += len(ground_truth_triplets - predicted_triplets)

    # Calculate Precision, Recall, and F1
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    return {"precision": precision, "recall": recall, "f1": f1}

In [ ]:
output_dir = "/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results"

In [ ]:
training_args = Seq2SeqTrainingArguments(
    output_dir=output_dir,             # Output directory
    eval_strategy='epoch', # Previously epoch
    #eval_steps=100,
    learning_rate=5e-5,                 # Learning rate
    save_strategy="epoch",
    per_device_train_batch_size=4,      # Batch size for training
    per_device_eval_batch_size=4,       # Batch size for evaluation
    gradient_accumulation_steps=2,
    num_train_epochs=10,                 # Number of epochs
    weight_decay=0.01,                  # Weight decay
    logging_dir=output_dir+"/logs",               # Logging directory
    logging_steps=50,
    #log_level="info",
    save_total_limit=2,
    metric_for_best_model = 'f1',
    load_best_model_at_end=True,        # Load the best model at the end of training
    predict_with_generate=True,          # Enable text generation during evaluation
    disable_tqdm=False,
    fp16=True
)

In [ ]:
trainer = Seq2SeqTrainer(
    model=rebel_model,                   # The model to fine-tune
    args=training_args,                  # Training arguments
    train_dataset=tokenized_train_dataset,  # Tokenized training dataset
    eval_dataset=tokenized_val_dataset,     # Tokenized validation dataset
    tokenizer=rebel_tokenizer,                 # Tokenizer
    compute_metrics=compute_metrics      # (Optional) Custom metrics function
)

<ipython-input-35-8ed90a133f1a>:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

In [ ]:
trainer.train()

The following columns in the training set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: __index_level_0__, input_coref, output. If __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 354
  Num Epochs = 10
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 2
  Total optimization steps = 440
  Number of trainable parameters = 406,298,624
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········

wandb: ERROR API key must be 40 characters long, yours was 27

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: __index_level_0__, input_coref, output. If __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 89
  Batch size = 4
Generate config GenerationConfig {
  "bos_token_id": 0,
  "decoder_start_token_id": 0,
  "eos_token_id": 2,
  "forced_eos_token_id": 2,
  "max_length": 200,
  "num_beams": 4,
  "pad_token_id": 1
}

Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-45
/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:2817: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 200, 'num_beams': 4}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-45/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-45/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-45/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-45/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-45/special_tokens_map.json
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: __index_level_0__, input_coref, output. If __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 89
  Batch size = 4
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-90
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-90/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-90/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-90/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-90/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-90/special_tokens_map.json
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: __index_level_0__, input_coref, output. If __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 89
  Batch size = 4
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-135
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-135/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-135/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-135/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-135/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-135/special_tokens_map.json
Deleting older checkpoint [/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-90] due to args.save_total_limit
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: __index_level_0__, input_coref, output. If __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 89
  Batch size = 4
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-180
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-180/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-180/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-180/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-180/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-180/special_tokens_map.json
Deleting older checkpoint [/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-45] due to args.save_total_limit
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: __index_level_0__, input_coref, output. If __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 89
  Batch size = 4
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-225
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-225/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-225/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-225/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-225/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-225/special_tokens_map.json
Deleting older checkpoint [/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-135] due to args.save_total_limit

TrainOutput(global_step=440, training_loss=2.1987757997079327, metrics={'train_runtime': 2330.1568, 'train_samples_per_second': 1.519, 'train_steps_per_second': 0.189, 'total_flos': 3755592275460096.0, 'train_loss': 2.1987757997079327, 'epoch': 9.786516853932584})

In [ ]:
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: abhijith3008 to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:3353: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 200, 'num_beams': 4}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=440, training_loss=1.0619294621727684, metrics={'train_runtime': 2195.9003, 'train_samples_per_second': 1.612, 'train_steps_per_second': 0.2, 'total_flos': 3755592275460096.0, 'train_loss': 1.0619294621727684, 'epoch': 9.786516853932584})

In [ ]:
# Old cell - Contains results trainer.train()

The following columns in the training set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: input, __index_level_0__, input_coref, output. If input, __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.
***** Running training *****
  Num examples = 315
  Num Epochs = 10
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 2
  Total optimization steps = 390
  Number of trainable parameters = 406,298,624
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"

The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: input, __index_level_0__, input_coref, output. If input, __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 79
  Batch size = 4
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-39
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-39/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-39/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-39/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-39/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-39/special_tokens_map.json
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: input, __index_level_0__, input_coref, output. If input, __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 79
  Batch size = 4
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-79
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-79/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-79/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-79/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-79/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-79/special_tokens_map.json
Deleting older checkpoint [/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-79] due to args.save_total_limit
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: input, __index_level_0__, input_coref, output. If input, __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 79
  Batch size = 4
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118/special_tokens_map.json
Deleting older checkpoint [/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-117] due to args.save_total_limit
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: input, __index_level_0__, input_coref, output. If input, __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 79
  Batch size = 4
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-158
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-158/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-158/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-158/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-158/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-158/special_tokens_map.json
Deleting older checkpoint [/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-118] due to args.save_total_limit
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: input, __index_level_0__, input_coref, output. If input, __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 79
  Batch size = 4
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Saving model checkpoint to /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-197
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-197/config.json
Configuration saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-197/generation_config.json
Model weights saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-197/model.safetensors
tokenizer config file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-197/tokenizer_config.json
Special tokens file saved in /content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-197/special_tokens_map.json
Deleting older checkpoint [/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/checkpoint-158] due to args.save_total_limit
The following columns in the evaluation set don't have a corresponding argument in `BartForConditionalGeneration.forward` and have been ignored: input, __index_level_0__, input_coref, output. If input, __index_level_0__, input_coref, output are not expected by `BartForConditionalGeneration.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 79
  Batch size = 4
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.

TrainOutput(global_step=390, training_loss=0.3999919839394398, metrics={'train_runtime': 2134.3902, 'train_samples_per_second': 1.476, 'train_steps_per_second': 0.183, 'total_flos': 3370931208585216.0, 'train_loss': 0.3999919839394398, 'epoch': 9.873417721518987})

In [ ]:
model_path = output_dir

In [ ]:
model_path

'/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results'

In [ ]:
rebel_model.state_dict()

In [ ]:
torch.save(rebel_model.state_dict(),model_path+'/model_state_dict.pth')

In [ ]:
rebel_model.save_pretrained(model_path)
rebel_tokenizer.save_pretrained(model_path)

('/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/model_finetuning/tokenizer_config.json',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/model_finetuning/special_tokens_map.json',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/model_finetuning/vocab.json',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/model_finetuning/merges.txt',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/model_finetuning/added_tokens.json',
 '/content/gdrive/MyDrive/CS_546_Project_Dependencies/BioRED_Results/model_finetuning/tokenizer.json')

In [ ]:
rebel_model.to(device)

BartForConditionalGeneration(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50272, 1024, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50272, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartEncoderLayer(
          (self_attn): BartSdpaAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): BartDecoder(
      (embed_tokens): BartScaledWordEmbedding(50272, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartDecoderLayer(
          (self_attn): BartSdpaAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): BartSdpaAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=50272, bias=False)
)

In [ ]:
def preprocess_test_data(examples):
    model_inputs = rebel_tokenizer(
        examples["input_coref"],  # Source text
        max_length=512,
        truncation=True,
        padding="max_length"
    )
    return model_inputs

In [ ]:
#rebel_df_latest = pd.read_csv('/content/Groq_BioRED_Triplets_Main.csv',encoding='cp1252')
biored_test_df = pd.read_csv('/content/gdrive/MyDrive/CS_546_Project_Dependencies/RE_Finetuning/Test_BioRED_Triplets_Annotated.csv')

In [ ]:
biored_test_df = biored_test_df.rename(columns={'Passage':'input_coref','Triplets':'output'})

In [ ]:
test_dataset = Dataset.from_pandas(biored_test_df[['input_coref','output']])

In [ ]:
test_dataset

Dataset({
    features: ['input_coref', 'output'],
    num_rows: 51
})

In [ ]:
tokenized_test_dataset = test_dataset.map(preprocess_test_data, batched=True)

Map:   0%|          | 0/51 [00:00<?, ? examples/s]

In [ ]:
predictions = trainer.predict(tokenized_test_dataset)

In [ ]:
def evaluate_test_set(pred_values,true_values):
  tp, fp, fn = 0, 0, 0
  for pred, label in zip(pred_values, true_values):
      predicted_triplets = set(extract_triplets(pred))
      ground_truth_triplets = set(extract_triplets(label))

      # Compute True Positives, False Positives, and False Negatives
      tp += len(predicted_triplets & ground_truth_triplets)
      fp += len(predicted_triplets - ground_truth_triplets)
      fn += len(ground_truth_triplets - predicted_triplets)

  # Calculate Precision, Recall, and F1
  precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
  recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
  f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

  return {"precision": precision, "recall": recall, "f1": f1}

In [ ]:
decoded_preds = [rebel_tokenizer.decode(pred, skip_special_tokens=False) for pred in predictions.predictions]

In [ ]:
true_labels = test_dataset['output']

In [ ]:
evaluate_test_set(decoded_preds, true_labels)

{'precision': 0.0034602076124567475,
 'recall': 0.0022624434389140274,
 'f1': 0.002735978112175103}

In [ ]:
for pred, label in zip(decoded_preds[:5], true_labels[:5]):
  predicted_triplets = set(extract_triplets(pred))
  ground_truth_triplets = set(extract_triplets(label))
  print(f'Predicted Triplets: {predicted_triplets}')
  print(f'Ground truth Triplets: {ground_truth_triplets}\n')

Predicted Triplets: {('Serum lipid', 'intracellular lipoprotein metabolism', 'influenced by rs8099917 SNP.'), ('Hepatitis C virus', 'IL28B SNP', 'linked to lipid levels'), ('PEG-IFN/RBV therapy', 'hepatic response', 'improved in patients with rs8099917 TT genotype'), ('Serum lipid', 'hepatic response', 'influenced by rs8099917 TT genotype'), ('Hepatitis C virus', 'rs8099917 TT genotype', 'associated with LDL cholesterol.')}
Ground truth Triplets: {('rs8099917 TT genotype', 'therapeutic outcomes', 'predicts'), ('apoB-100 concentration', 'intracellular metabolism', 'indicates'), ('Hepatitis C virus (HCV) core region', 'Arg70 substitution', 'linked to'), ('Hepatitis C virus (HCV) core region', 'lipid metabolism', 'alters'), ('apoB-100 concentration', 'HCV response', 'predicts'), ('Chronic HCV infection', 'LDL cholesterol', 'impacts'), ('Chronic HCV infection', 'lipoprotein pathways', 'disrupts'), ('IL28B rs8099917 SNP', 'serum apoB-100 levels', 'influences'), ('rs8099917 TT genotype', 'lipid markers', 'associates with'), ('IL28B rs8099917 SNP', 'PEG-IFN/RBV therapy response', 'correlates with')}

Predicted Triplets: {('Phosphatidylinositol 4-kinase IIb depletion', 'MT1-MMP trafficking', 'induces'), ('PI4KII enzymes', 'invadopodia formation', 'regulates'), ('Phosphatidylinositol 4-kinase IIb mRNA', 'degradative pathway', 'disrupts'), ('PI4KII enzymes', 'lipid phosphatidylinositol 4-phosphate', 'synthesizes'), ('Phosphatidylinositol 4-kinase IIb depletion', 'invasive phenotype', 'associated')}
Ground truth Triplets: {('PI4KIIb depletion', 'MT1-MMP plasma membrane localization', 'increases'), ('PI4KIIb', 'invadopodia formation and MT1-MMP trafficking', 'suppresses'), ('Oncogenomic data', 'degradation pathway for MT1-MMP', 'regulates'), ('PI4KIIb depletion', 'Rab8 trafficking and invasion', 'promotes'), ('Oncogenomic data', 'PI4KIIb underexpression and cancer', 'associates'), ('PI4KIIb', 'aggressive cancer', 'counteracts'), ('PI4KIIb', 'PI(4)P production and TGN traffic', 'maintains'), ('PI4KIIb', 'invasive cellular phenotype', 'prevents'), ('Oncogenomic data', 'tumor suppressor role', 'highlights'), ('PI4KIIb', 'cytoskeletal remodeling', 'prevents'), ('PI4KIIb', 'endosomal compartment function', 'supports'), ('PI4KIIb depletion', 'cancer invasiveness', 'correlates'), ('PI4KIIb', 'Rab5 and Rab7 colocalization', 'reduces')}

Predicted Triplets: {('Spindle organization', 'germinal vesicle breakdown', 'unaffected'), ('CenpH', 'cyclin B1', 'restores'), ('CenpH', 'meiotic G2/M transition', 'regulates'), ('Cyclin B1', 'CenpH depletion', 'restores')}
Ground truth Triplets: {('CenpH', 'meiotic G2/M transition', 'promotes'), ('CenpH', 'cyclin B1 protection from APC/CCdh1', 'regulates'), ('CenpH', 'MPF activation', 'ensures'), ('CenpH', 'spindle organization', 'does not affect'), ('CenpH depletion', 'cyclin B1 destruction', 'increases'), ('CenpH depletion', 'meiotic resumption', 'impairs'), ('CenpH depletion', 'MPF activation', 'disrupts'), ('CenpH', 'meiotic resumption', 'facilitates'), ('Exogenous cyclin B1', 'CenpH depletion effects', 'rescues'), ('Exogenous cyclin B1', 'APC/CCdh1-cyclin B1 pathway', 'bypasses'), ('Exogenous cyclin B1', 'G2/M transition defects', 'mitigates')}

Predicted Triplets: {('Affected individuals', 'suture-sparing congenital cataract', 'observed in'), ('CRYBA3/A1 gene', 'suture-sparing congenital cataract', 'associated with'), ('Affected individuals', 'phenotypic heterogeneity', 'observed in'), ('CRYBA3/A1 gene', 'mutations in exon 4 (279delGAG) and IVS3+1G/A (IVS3+1G/A)', 'linked to')}
Ground truth Triplets: {('DeltaG91 mutation', 'glycine-91 deletion', 'involves'), ('CRYBA3/A1 mutation', 'lens fiber morphology', 'preserves'), ('DeltaG91 mutation', 'disease severity', 'impacts'), ('CRYBA3/A1 mutation', 'suture-sparing autosomal dominant congenital nuclear cataract', 'causes'), ('Linkage analysis', 'zonular cataract distinction', 'highlights'), ('CRYBA3/A1 mutation', 'phenotypic heterogeneity', 'explains'), ('Linkage analysis', 'suture-sparing phenotype', 'confirms'), ('DeltaG91 mutation', 'cataract progression', 'drives'), ('Linkage analysis', 'chromosome 17 and CRYBA3/A1 mutation', 'associates')}

Predicted Triplets: {('DBP Glu-containing genotype', 'GAD65 antibodies', 'unaffected by'), ('DBP polymorphism', 'autoimmune markers', 'associated with'), ('DBP polymorphism', 'cellular endocytosis', 'essential for'), ('Glu/Glu polymorphism', 'autoimmune markers', 'linked to'), ('GAT substitution', 'autoantibodies', 'linked to')}
Ground truth Triplets: {('Vitamin D-binding protein (DBP)', 'IA-2 antibody association', 'influences'), ('Vitamin D endocrine system', 'genetic predisposition', 'underscores'), ('Vitamin D-binding protein (DBP)', '1.25(OH)2D3 affinity variation', 'explains'), ('Vitamin D endocrine system', 'type 1 diabetes autoimmunity', 'links'), ('DBP polymorphisms', 'codon 416 substitutions (Asp/Glu, Glu/Glu)', 'correlate'), ('Vitamin D-binding protein (DBP)', 'autoimmune process in type 1 diabetes', 'supports'), ('DBP polymorphisms', 'type 1 diabetes susceptibility', 'indicates'), ('Vitamin D endocrine system', 'IA-2 antibody presence', 'emphasizes'), ('DBP polymorphisms', 'GAD65 antibody presence', 'does not affect')}

In [ ]:
test_str = """Debrisoquine phenotype and the pharmacokinetics and beta-2 receptor pharmacodynamics of metoprolol and metoprolol's enantiomers. The metabolism of the cardioselective beta-blocker metoprolol is under genetic control of the debrisoquine/sparteine type. The two metabolic phenotypes, extensive (EM) and poor metabolizers (PM), show different stereoselective metabolism, resulting in apparently higher beta-1 adrenoceptor antagonistic potency of the cardioselective beta-blocker metoprolol in EMs. We investigated if apparently higher beta-1 adrenoceptor antagonistic potency of racemic metoprolol in EMs also applies to the beta-2 adrenoceptor antagonism by metoprolol. The drug effect studied was the antagonism by metoprolol of terbutaline-induced hypokalemia. By using pharmacokinetic pharmacodynamic modeling the pharmacodynamics of the cardioselective beta-blocker metoprolol and the active S-isomer, were quantitated in EMs and PMs in terms of IC50 values, representing metoprolol plasma concentrations resulting in half-maximum receptor occupancy. Six EMs received 0.5 mg of terbutaline s.c. on two different occasions: 1) 1 hr after administration of a placebo and 2) 1 hr after 150 mg of metoprolol p.o. Five PMs were studied according to the same protocol, except for a higher terbutaline dose (0.75 mg) on day 2. Blood samples for the analysis of plasma potassium, terbutaline, metoprolol (racemic, R- and S-isomer), and alpha-hydroxymetoprolol concentrations were taken at regular time intervals, during 8 hr after metoprolol. In PMs, metoprolol increased the terbutaline area under the plasma concentration vs. time curve (+67%). Higher metoprolol/alpha-hydroxymetoprolol ratios in PMs were predictive for higher R-/S-isomer ratios of unchanged drug. There was a difference in metoprolol potency with higher racemic metoprolol IC50 values in PMs (72 +/- 7 ng.ml-1) than EMs (42 +/- 8 ng.ml-1, P less than .001)"""

In [ ]:
rebel_df_test_data['input_coref'][4]

In [ ]:
try:
    extracted_triplets = []
    for sentence in test_str.split('. '):
        inputs = rebel_tokenizer(
            sentence, return_tensors="pt", truncation=True, max_length=512
        ).to(device)
        outputs = rebel_model.generate(**inputs)
        decoded_output = rebel_tokenizer.decode(outputs[0], skip_special_tokens=False)
        triplets = list(set(extract_triplets(decoded_output)))
        if triplets:
            extracted_triplets.extend(triplets)
except Exception as e:
    print(f"Error during inference: {e}")

In [ ]:
extracted_triplets

[('Metoprolol', 'beta-2 receptor pharmacodynamics', 'influenced by.'),
 ('Debrisoquine phenotype',
  'beta-2 receptor pharmacodynamics',
  'influenced by.'),
 ('enantiomers', 'metoprolol', 'different from'),
 ('Metoprolol', 'pharmacokinetics', 'influenced by'),
 ('Debrisoquine phenotype', 'pharmacokinetics', 'influenced by'),
 ('Metoprolol metabolism',
  'beta-blocker metabolism',
  'regulated by genetic control'),
 ('Metoprolol metabolism',
  'debrisoquine/sparteine type',
  'under genetic control.'),
 ('Metoprolol',
  'beta-1 adrenoceptor antagonistic potency',
  'increased in EMs.'),
 ('Metoprolol', 'beta-1 adrenoceptor antagonistic potency', 'higher in EMs'),
 ('Metoprolol',
  'beta-2 adrenoceptor antagonism',
  'higher in metoprolol-treated mice.'),
 ('Metoprolol', 'terbutaline-induced hypokalemia', 'antagonizes.'),
 ('terbutaline s.c', 'EMs', 'received 0.5 mg per week'),
 ('Metoprolol p.o', 'placebo', 'follows'),
 ('PMs', 'day 2', 'higher than day 2.'),
 ('Terbutaline', 'day 2', 'higher than day 2.'),
 ('Terbutaline', '0.75 mg/day', 'higher than PMs'),
 ('PMs', 'terbutaline', 'higher than day 2'),
 ('Plasma potassium', 'alpha-hydroxymetoprolol', 'analyzed'),
 ('Metoprolol concentration', 'terbutaline, metoprolol', 'analyzed'),
 ('Terbutaline', 'alpha-hydroxymetoprolol', 'analyzed'),
 ('Metoprolol concentration', 'plasma potassium', 'analyzed'),
 ('Terbutaline', 'metoprolol concentration', 'analyzed'),
 ('Blood samples', 'metoprolol concentration', 'analyzed'),
 ('Blood samples', 'alpha-hydroxymetoprolol', 'analyzed'),
 ('Plasma potassium', 'terbutaline, metoprolol', 'analyzed'),
 ('Plasma potassium', 'metoprolol concentration', 'analyzed'),
 ('Metoprolol/alpha-hydroxymetoprolol ratios',
  'R-/S-isomer ratios',
  'predictive for unchanged drug'),
 ('Metoprolol/alpha-hydroxymetoprolol ratios',
  'higher metoprolol/alpha-hydroxymetoprolol ratios',
  'predictive for higher R-/S-isomer ratios.'),
 ('Metoprolol IC50', 'PMs', 'higher in'),
 ('Metoprolol IC50', 'EMs', 'lower in.'),
 ('Racemic metoprolol potency', 'IC50 values', 'higher in'),
 ('Racemic metoprolol potency', 'PMs', 'lower in.')]

In [ ]:
text = 'Insulin helps to mitigate diabetes'

In [ ]:
inputs = rebel_tokenizer(text, return_tensors="pt", max_length=1024, truncation=False)

In [ ]:
inputs = {key: value.to(device) for key, value in inputs.items()}

In [ ]:
outputs = rebel_model.generate(**inputs)

In [ ]:
extracted_text = rebel_tokenizer.decode(outputs[0], skip_special_tokens=False)

In [ ]:
extracted_text

'<s><triplet> Insulin <subj> diabetes <obj> mitigates\n<triplet> Diabetes <subj> Insulin <obj> drug used for treatment</s>'

results = trainer.evaluate()

##### Testing on PubMed Heart Disease dataset

- Load PubMed dataset
- Use page title + abstract as input
- Tokenize input
- Generate triplets as output

In [ ]:
pubmed_df = pd.read_json('/content/research_text_pubmed_heart_failure.json')

In [ ]:
pubmed_df.head()

,associated data,title,url,reference_links__associated data,reference__associated data,abstract,reference_links__abstract,reference__abstract,introduction,reference_links__introduction,...,reference__institutional review board statement,informed consent statement,reference_links__informed consent statement,reference__informed consent statement,data availability statement,reference_links__data availability statement,reference__data availability statement,conflicts of interest,reference_links__conflicts of interest,reference__conflicts of interest
0,associated data,"Functional mutation, splice, distribution, and...",https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,,,abstract Cardiovascular disease (CVD) is cau...,,,introduction Cardiovascular disease (CVD) is...,"1 /pmc/articles/PMC6366352/, 2 https://pubmed....",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,associated data,Common- and rare-variant genetic architecture ...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,,,abstract Heart failure (HF) is a complex tra...,,,introduction Heart failure (HF) is a heterog...,"1 /pmc/articles/PMC4868779/, 2 /pmc/articles/P...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,associated data,Single-cell RNA sequencing in donor and end-st...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1...,,,abstract BackgroundDilation may be the first...,,,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,associated data,Overlap phenotypes of the left ventricular non...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8...,,,abstract BackgroundThe left ventricular nonc...,,,introduction The left ventricular noncompact...,"1 /pmc/articles/PMC7566488/, 2 https://pubmed....",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,associated data,Titin‐truncating variants are associated with ...,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6...,,,abstract BackgroundTitin‐truncating variants...,,,introduction Left ventricular non‐compaction...,"1 https://pubmed.ncbi.nlm.nih.gov/25865865, 2 ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pubmed_df.shape

(9, 147)

In [ ]:
def preprocess_text(text: str):
  '''
  The aim of this function is to preprocess text by converting it to lowercase, and punctuations.
  '''
  text = text.lower()
  text = re.sub(r",\s?",' ', text)
  text = re.sub(r'\.\s*', ' ', text)
  return text

In [ ]:
def filter_text(text:str):
    try:
        if type(text) != str:
            return ''
        else:
            if 'abstract' not in text:
                return text
            else:
                text = text.replace('abstract ', '')
                return text
    except:
        print(f'Error text: {text}...{type(text)}')

In [ ]:
pubmed_df = pubmed_df[['abstract','title']]

In [ ]:
pubmed_df['abstract_updated'] = pubmed_df['abstract'].apply(lambda row: filter_text(row))

In [ ]:
pubmed_df['abstract_updated'] = pubmed_df['abstract_updated'].apply(lambda row: preprocess_text(row))

In [ ]:
pubmed_df['input_data'] = pubmed_df['title']+" "+pubmed_df['abstract_updated']

In [ ]:
pubmed_df.head()

,abstract,title,abstract_updated,input_data
0,abstract Cardiovascular disease (CVD) is cau...,"Functional mutation, splice, distribution, and...",cardiovascular disease (cvd) is caused by a ...,"Functional mutation, splice, distribution, and..."
1,abstract Heart failure (HF) is a complex tra...,Common- and rare-variant genetic architecture ...,heart failure (hf) is a complex trait influe...,Common- and rare-variant genetic architecture ...
2,abstract BackgroundDilation may be the first...,Single-cell RNA sequencing in donor and end-st...,backgrounddilation may be the first right ve...,Single-cell RNA sequencing in donor and end-st...
3,abstract BackgroundThe left ventricular nonc...,Overlap phenotypes of the left ventricular non...,backgroundthe left ventricular noncompaction...,Overlap phenotypes of the left ventricular non...
4,abstract BackgroundTitin‐truncating variants...,Titin‐truncating variants are associated with ...,backgroundtitin‐truncating variants (ttntv) ...,Titin‐truncating variants are associated with ...

In [ ]:
pubmed_df['input_coref'] = pubmed_df['input_data'].apply(perform_coreference_resolution)

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/1 [00:00<?, ? examples/s]

Inference:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
pubmed_dataset = Dataset.from_pandas(pubmed_df[['input_coref']])

In [ ]:
pubmed_df.columns
#pubmed_df['input_coref'].shape

Index(['associated data', 'title', 'url', 'reference_links__associated data',
       'reference__associated data', 'abstract', 'reference_links__abstract',
       'reference__abstract', 'introduction', 'reference_links__introduction',
       ...
       'reference__informed consent statement', 'data availability statement',
       'reference_links__data availability statement',
       'reference__data availability statement', 'conflicts of interest',
       'reference_links__conflicts of interest',
       'reference__conflicts of interest', 'abstract_updated', 'input_data',
       'input_coref'],
      dtype='object', length=150)

In [ ]:
pubmed_df[['associated data', 'title', 'url']]

NameError: name 'pubmed_df' is not defined

In [ ]:
pubmed_dataset

Dataset({
    features: ['input_coref'],
    num_rows: 9
})

In [ ]:
tokenized_pubmed_dataset = pubmed_dataset.map(preprocess_test_data, batched=True)

Map:   0%|          | 0/9 [00:00<?, ? examples/s]

In [ ]:
pubmed_predictions = trainer.predict(tokenized_pubmed_dataset)

In [ ]:
decoded_preds_pubmed = [rebel_tokenizer.decode(pred, skip_special_tokens=False) for pred in pubmed_predictions.predictions]

In [ ]:
pubmed_triplets = []
for triplet in decoded_preds:
  extracted_triplet = set(extract_triplets(triplet))
  pubmed_triplets.append(extracted_triplet)

In [ ]:
pubmed_triplets

[{('cvd', 'cald1 tek', 'Association'),
  ('cvd', 'myh6', 'Association'),
  ('cvd', 'pln', 'Association'),
  ('hba1', 'cald1 tek', 'Association'),
  ('hba1', 'cvd', 'Association'),
  ('hba1', 'myh6', 'Association'),
  ('hba1', 'pln', 'Association'),
  ('heart failure', 'cald1 tek', 'Association'),
  ('heart failure', 'cvd', 'Association'),
  ('heart failure', 'myh6', 'Association'),
  ('heart failure', 'pln', 'Association')},
 set(),
 set(),
 {('desmocollin2', 'arrhythmia', 'Association'),
  ('desmocollin2',
   'atrial fibrillation (af) ventricular tachycardia (vt)',
   'Association'),
  ('desmocollin2', 'desmocollin2 desmosome', 'Bind'),
  ('desmocollin2', 'heart failure', 'Association'),
  ('desmocollin2',
   'left ventricular noncompaction cardiomyopathy',
   'Association'),
  ('desmocollin2', 'sudden cardiac death', 'Association'),
  ('left ventricular noncompaction cardiomyopathy',
   'arrhythmia',
   'Association'),
  ('left ventricular noncompaction cardiomyopathy',
   'atrial fibrillation (af) ventricular tachycardia (vt)',
   'Association'),
  ('left ventricular noncompaction cardiomyopathy',
   'desmocollin2',
   'Negative_Correlation'),
  ('left ventricular noncompaction cardiomyopathy',
   'dsc2p k47rfs*2',
   'Negative'),
  ('left ventricular noncompaction cardiomyopathy',
   'heart failure',
   'Association'),
  ('p k47rfs*2', 'desmocollin2', 'Negative_Correlation')},
 {('ttntv', 'heart failure', 'Positive_Correlation'),
  ('ttntv', 'hf', 'Positive_Correlation'),
  ('ttntv', 'left ventricular non‐compaction cardiomyopathy', 'Association')},
 set(),
 {('dcm', 'dcm', 'Association'),
  ('dcm', 'dcm', 'Positive_Correlation'),
  ('dcm',
   'dcm',
   'Positive_Correlation <obj> Positive_Correlation <obj> Association'),
  ('dcm', 'titin', 'Association')},
 set(),
 {('hf', 'cardiomyopathies', 'Association')}]

In [ ]:
output_file = output_dir+"/pubmed_triplets_output.txt"
with open(output_file, "w") as f:
    for idx, triplet_set in enumerate(pubmed_triplets):
        f.write(f"Set {idx+1}:\n")
        for triplet in triplet_set:
            f.write(f"{triplet}\n")
        f.write("\n")

###### Misc

In [ ]:
inputs = rebel_tokenizer(test, return_tensors="pt", max_length=1024, truncation=False)

In [ ]:
inputs = {key: value.to(device) for key, value in inputs.items()}

In [ ]:
outputs = rebel_model.generate(**inputs)
extracted_text = rebel_tokenizer.decode(outputs[0], skip_special_tokens=True)

In [ ]:
extracted_text

' MODY1  gene  instance of  MODY4  gene  instance of'

In [ ]:
torch.cuda.empty_cache()

In [ ]:
!nvidia-smi

Mon Dec 16 11:23:55 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0              30W /  70W |  14695MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

###### Experimenting

decoded_string = '<triplet> RIP1 <subj> caspases <obj> Positive_Correlation <triplet> BV6 <subj> tumor <obj> Negative_Correlation <triplet> cIAP2 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> cIAP1 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> Smac <subj> cIAP2 <obj> Negative_Correlation <subj> cIAP1 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> tumor <subj> FasL <obj> Association <subj> perforin <obj> Association <triplet> TNFa <subj> RIP3 <obj> Positive_Correlation <subj> RIP1 <obj> Positive_Correlation <subj> caspases <obj> Positive_Correlation <subj> tumor <obj> Association <subj> sarcoma <obj> Association <triplet> NF-kB <subj> tumor <obj> Association <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind <triplet> p65 <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind'

decoded_str = '<s><triplet> RIP1 <subj> caspases <obj> Positive_Correlation <triplet> BV6 <subj> tumor <obj> Negative_Correlation <triplet> cIAP2 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> cIAP1 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> Smac <subj> cIAP2 <obj> Negative_Correlation <subj> cIAP1 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> tumor <subj> FasL <obj> Association <subj> perforin <obj> Association <triplet> TNFa <subj> RIP3 <obj> Positive_Correlation <subj> RIP1 <obj> Positive_Correlation <subj> caspases <obj> Positive_Correlation <subj> tumor <obj> Association <subj> sarcoma <obj> Association <triplet> NF-kB <subj> tumor <obj> Association <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind <triplet> p65 <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>'

st = decoded_str
if '<s>' in decoded_str:
  st = ''.join(decoded_str.split('<s>')[1:])
  st = st.split('</s>')[0]

st

extract_triplets(st)

prediction_mixed = {
    ('The Playtones', 'Swedish', 'country of origin'),
    ('The Playtones', 'rock', 'genre'),                
    ('rock n roll', '1950', 'start time')              
}

gt = [
  '<s><triplet> Th1/Tc1 T cells <subj> T cell <obj> subclass of <triplet> CCL2 <subj> T cell <obj> subclass of <triplet> CCL5 <subj> T cell <obj> subclass of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>',
  '<s><triplet> ALDH1A2 <subj> gene <obj> instance of <triplet> ALDH1B1 <subj> gene <obj> instance of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>',
  '<s><triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>',
  '<s><triplet> IFNAR1 <subj> type I interferon <obj> subclass of <subj> type I interferon <obj> subclass of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>',
  '<s><triplet> hippocampus <subj> dentate gyrus <obj> has part <triplet> dentate gyrus <subj> hippocampus <obj> part of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>',
  '<triplet> The Playtones <subj> Swedish <obj> country of origin <subj> rock n roll <obj> genre <subj> 2008 <obj> inception <subj> Kallinge <obj> location of formation <triplet> rock n roll <subj> 1950 <obj> start time'
]

ground_truth_triplets = extract_triplets(gt[-1])
ground_truth_triplets_set = set(extract_triplets(gt[-1]))

ground_truth_triplets_set

prediction_mixed

tp, fp, fn = 0, 0, 0

predicted_triplets = set(extract_triplets(pred))
ground_truth_triplets = set(extract_triplets(label))

Compute True Positives, False Positives, and False Negatives
tp = len(prediction_mixed & ground_truth_triplets_set)
fp = len(prediction_mixed - ground_truth_triplets_set)
fn = len(ground_truth_triplets_set - prediction_mixed)

print(f'TP: {tp}, FP: {fp}, FN: {fn}')

Length of predictions list: 79
Length of labels list: 79
=== Sample Predictions ===
Prediction 1: <s><triplet> Th1/Tc1 T cells <subj> T cell <obj> subclass of <triplet> CCL2 <subj> T cell <obj> subclass of <triplet> CCL5 <subj> T cell <obj> subclass of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Prediction 2: <s><triplet> ALDH1A2 <subj> gene <obj> instance of <triplet> ALDH1B1 <subj> gene <obj> instance of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Prediction 3: <s><triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role <triplet> TIPE2 <subj> apoptosis <obj> subject has role</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Prediction 4: <s><triplet> IFNAR1 <subj> type I interferon <obj> subclass of <subj> type I interferon <obj> subclass of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Prediction 5: <s><triplet> hippocampus <subj> dentate gyrus <obj> has part <triplet> dentate gyrus <subj> hippocampus <obj> part of</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>

=== Sample Ground Truth Labels ===
Ground Truth 1: <s><triplet> RIP1 <subj> caspases <obj> Positive_Correlation <triplet> BV6 <subj> tumor <obj> Negative_Correlation <triplet> cIAP2 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> cIAP1 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> Smac <subj> cIAP2 <obj> Negative_Correlation <subj> cIAP1 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> tumor <subj> FasL <obj> Association <subj> perforin <obj> Association <triplet> TNFa <subj> RIP3 <obj> Positive_Correlation <subj> RIP1 <obj> Positive_Correlation <subj> caspases <obj> Positive_Correlation <subj> tumor <obj> Association <subj> sarcoma <obj> Association <triplet> NF-kB <subj> tumor <obj> Association <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind <triplet> p65 <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Ground Truth 2: <s><triplet> rs10973794 <subj> prostate cancer <obj> Positive_Correlation <triplet> ALDH1B1 <subj> prostate cancer <obj> Association <triplet> rs8041922 <subj> prostate cancer <obj> Positive_Correlation <triplet> rs12910509 <subj> prostate cancer <obj> Positive_Correlation <triplet> rs1441817 <subj> prostate cancer <obj> Positive_Correlation <triplet> ALDH1A2 <subj> prostate cancer <obj> Association <triplet> alcohol <subj> prostate cancer <obj> Association <subj> ALDH1A2 <obj> Association <subj> ADHs <obj> Association</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Ground Truth 3: <s><triplet> Bcl-2 <subj> lung cancer <obj> Association <triplet> Bax <subj> lung cancer <obj> Association <triplet> caspase-9 <subj> lung cancer <obj> Association <triplet> caspase-3 <subj> lung cancer <obj> Association <triplet> TIPE2 <subj> P38 <obj> Association <subj> Akt <obj> Association <subj> Bcl-2 <obj> Negative_Correlation <subj> Bax <obj> Positive_Correlation <subj> caspase-9 <obj> Positive_Correlation <subj> caspase-3 <obj> Positive_Correlation <subj> tumors <obj> Association <subj> lung cancer <obj> Negative_Correlation <subj> small cell lung cancer <obj> Negative_Correlation</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Ground Truth 4: <s><triplet> insulitis <subj> IFNAR1 <obj> Association <triplet> diabetes <subj> IFN <obj> Association <subj> poly I:C <obj> Positive_Correlation <subj> IFNAR1 <obj> Association <triplet> IFN receptor <subj> type 1 diabetes <obj> Association <triplet> type I interferon <subj> type 1 diabetes <obj> Association <triplet> type 1 diabetes <subj> insulin <obj> Association <triplet> IFNAR1 <subj> type 1 diabetes <obj> Association</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Ground Truth 5: <s><triplet> CCK1 receptor <subj> L-364,718 <obj> Negative_Correlation <triplet> morphine <subj> amnesia <obj> Positive_Correlation <subj> memory impairment <obj> Positive_Correlation <subj> CCK2 receptors <obj> Association <triplet> CCK-8 <subj> amnesia <obj> Negative_Correlation <subj> memory impairment <obj> Negative_Correlation <subj> morphine <obj> Negative_Correlation <subj> CCK2 receptors <obj> Association <triplet> L-365,260 <subj> CCK-8 <obj> Negative_Correlation <triplet> CCK2 receptors <subj> L-365,260 <obj> Negative_Correlation</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

KeyboardInterrupt:

In [ ]:
print(results)

In [ ]:
test_str = 'In this paper, a novel method to learn the intrinsic object structure for robust visual tracking is proposed.'
test = 'Hepatocyte nuclear factor-6: associations between genetic variability and type II diabetes and between genetic variability and estimates of insulin secretion. Hepatocyte nuclear factor-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in Hepatocyte nuclear factor-6 is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of Hepatocyte nuclear factor-6. We then examined the coding region as well as the intron-exon boundaries of the HNF-6 gene on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of An identified missense variant was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II (non-insulin-dependent) diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of An identified missense variant did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of Hepatocyte nuclear factor-6 are not associated with type II diabetes or with changes in insulin responses to glucose among the Caucasians examined'

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
for i in range(1):
    input_ids = tokenized_val_dataset[i]["input_ids"]
    labels = tokenized_val_dataset[i]["labels"]
    input_coref = tokenized_val_dataset[i]["input_coref"]
    output = tokenized_val_dataset[i]["output"]

    # Decode inputs and labels
    decoded_input = rebel_tokenizer.decode(input_ids, skip_special_tokens=True)
    decoded_label = rebel_tokenizer.decode(labels, skip_special_tokens=False)

    print(f"Example {i+1}:")
    print("Decoded Input:", decoded_input)
    print("Original Input:", input_coref)
    print("Decoded Label:", decoded_label)
    print("Original Label:", output)
    print("-" * 50)

Example 1:
Decoded Input: NF-kB functions as a molecular link between tumor cells and Th1/Tc1 T cells in the tumor microenvironment to exert radiation-mediated tumor suppression. Radiation modulates both tumor cells and immune cells in the tumor microenvironment to exert Radiation's anti-tumor activity; however, the molecular connection between tumor cells and immune cells that mediates radiation-exerted tumor suppression activity in the tumor microenvironment is largely unknown. We report here that radiation induces rapid activation of the p65/p50 and p50/p50 NF-kB complexes in human soft tissue sarcoma (STS) cells. Radiation-activated p65/p50 and p50/p50 bind to the TNFa promoter to activate the TNFa promoter's transcription in STS cells. Radiation-induced TNFa induces tumor cell death in an autocrine manner. A sublethal dose of Smac mimetic BV6 induces cIAP1 and cIAP2 degradation to increase tumor cell sensitivity to radiation-induced cell death in vitro and to enhance radiation-mediated suppression of STS xenografts in vivo. Inhibition of caspases, RIP1, or RIP3 blocks radiation/TNFa-induced cell death, whereas inhibition of RIP1 blocks TNFa-induced caspase activation, suggesting that caspases and RIP1 act sequentially to mediate the non-compensatory cell death pathways. Furthermore, we determined in a syngeneic sarcoma mouse model that radiation up-regulates IRF3, IFNb, and the T cell chemokines CCL2 and CCL5 in the tumor microenvironment, which are associated with activation and increased infiltration of Th1/Tc1 T cells in the tumor microenvironment. Moreover, tumor-infiltrating T cells are in tumor-infiltrating T cells's active form since both the perforin and FasL pathways are activated in irradiated tumor tissues. Consequently, combined Smac mimetic BV6 and radiation completely suppressed tumor growth in vivo. Therefore, radiation-induced NF-kB functions as a molecular link between tumor cells and immune cells in the tumor microenvironment for radiation-mediated tumor suppression.
Original Input: NF-kB functions as a molecular link between tumor cells and Th1/Tc1 T cells in the tumor microenvironment to exert radiation-mediated tumor suppression. Radiation modulates both tumor cells and immune cells in the tumor microenvironment to exert Radiation's anti-tumor activity; however, the molecular connection between tumor cells and immune cells that mediates radiation-exerted tumor suppression activity in the tumor microenvironment is largely unknown. We report here that radiation induces rapid activation of the p65/p50 and p50/p50 NF-kB complexes in human soft tissue sarcoma (STS) cells. Radiation-activated p65/p50 and p50/p50 bind to the TNFa promoter to activate the TNFa promoter's transcription in STS cells. Radiation-induced TNFa induces tumor cell death in an autocrine manner. A sublethal dose of Smac mimetic BV6 induces cIAP1 and cIAP2 degradation to increase tumor cell sensitivity to radiation-induced cell death in vitro and to enhance radiation-mediated suppression of STS xenografts in vivo. Inhibition of caspases, RIP1, or RIP3 blocks radiation/TNFa-induced cell death, whereas inhibition of RIP1 blocks TNFa-induced caspase activation, suggesting that caspases and RIP1 act sequentially to mediate the non-compensatory cell death pathways. Furthermore, we determined in a syngeneic sarcoma mouse model that radiation up-regulates IRF3, IFNb, and the T cell chemokines CCL2 and CCL5 in the tumor microenvironment, which are associated with activation and increased infiltration of Th1/Tc1 T cells in the tumor microenvironment. Moreover, tumor-infiltrating T cells are in tumor-infiltrating T cells's active form since both the perforin and FasL pathways are activated in irradiated tumor tissues. Consequently, combined Smac mimetic BV6 and radiation completely suppressed tumor growth in vivo. Therefore, radiation-induced NF-kB functions as a molecular link between tumor cells and immune cells in the tumor microenvironment for radiation-mediated tumor suppression.
Decoded Label: <s><triplet> RIP1 <subj> caspases <obj> Positive_Correlation <triplet> BV6 <subj> tumor <obj> Negative_Correlation <triplet> cIAP2 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> cIAP1 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> Smac <subj> cIAP2 <obj> Negative_Correlation <subj> cIAP1 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> tumor <subj> FasL <obj> Association <subj> perforin <obj> Association <triplet> TNFa <subj> RIP3 <obj> Positive_Correlation <subj> RIP1 <obj> Positive_Correlation <subj> caspases <obj> Positive_Correlation <subj> tumor <obj> Association <subj> sarcoma <obj> Association <triplet> NF-kB <subj> tumor <obj> Association <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind <triplet> p65 <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
Original Label: <triplet> RIP1 <subj> caspases <obj> Positive_Correlation <triplet> BV6 <subj> tumor <obj> Negative_Correlation <triplet> cIAP2 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> cIAP1 <subj> BV6 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> Smac <subj> cIAP2 <obj> Negative_Correlation <subj> cIAP1 <obj> Negative_Correlation <subj> tumor <obj> Association <triplet> tumor <subj> FasL <obj> Association <subj> perforin <obj> Association <triplet> TNFa <subj> RIP3 <obj> Positive_Correlation <subj> RIP1 <obj> Positive_Correlation <subj> caspases <obj> Positive_Correlation <subj> tumor <obj> Association <subj> sarcoma <obj> Association <triplet> NF-kB <subj> tumor <obj> Association <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind <triplet> p65 <subj> TNFa <obj> Positive_Correlation <subj> sarcoma <obj> Association <subj> NF-kB <obj> Bind
--------------------------------------------------

### TESTING

def compute_metrics_v1(eval_preds):
    """
    Compute metrics for triplet extraction.

    Args:
        eval_preds (tuple): A tuple (predictions, labels) where:
            predictions (list of str): The model's predicted outputs.
            labels (list of str): The ground truth outputs.

    Returns:
        dict: Precision, Recall, and F1-Score.
    """
    predictions, labels = eval_preds

    # Initialize counts
    tp = 0  # True positives
    fp = 0  # False positives
    fn = 0  # False negatives

    for pred, label in zip(predictions, labels):
        # Extract triplets from predictions and labels
        predicted_triplets = set(extract_triplets(pred))
        ground_truth_triplets = set(extract_triplets(label))

        # Calculate TP, FP, FN
        tp += len(predicted_triplets & ground_truth_triplets)
        fp += len(predicted_triplets - ground_truth_triplets)
        fn += len(ground_truth_triplets - predicted_triplets)

    # Compute Precision, Recall, and F1
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    return {
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

def compute_metrics_v2(eval_preds):
    """
    Compute Precision, Recall, and F1-Score for triplet extraction.
    """
    # Unpack predictions and labels
    predictions, labels = eval_preds

    # Decode predictions and labels into strings
    decoded_predictions = [
        rebel_tokenizer.decode(pred, skip_special_tokens=True) for pred in predictions
    ]
    decoded_labels = [
        rebel_tokenizer.decode(label, skip_special_tokens=True) for label in labels
    ]

    tp, fp, fn = 0, 0, 0

    for pred, label in zip(decoded_predictions, decoded_labels):
        # Extract triplets from predictions and labels
        predicted_triplets = set(extract_triplets(pred))
        ground_truth_triplets = set(extract_triplets(label))

        # Compute True Positives, False Positives, and False Negatives
        tp += len(predicted_triplets & ground_truth_triplets)
        fp += len(predicted_triplets - ground_truth_triplets)
        fn += len(ground_truth_triplets - predicted_triplets)

    # Calculate Precision, Recall, and F1
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    return {"precision": precision, "recall": recall, "f1": f1}

def compute_metrics_old(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average="weighted")
    return {"precision": precision, "recall": recall, "f1": f1}

##### Trying Triplex

In [ ]:
import json

In [ ]:
def triplextract(model, tokenizer, text):
    input_format = """By implicitly extracting entities and relationships between entities, return knowledge graph triplets from the text as the output.
                      For example: The CRISPR-Cas9 system, discovered by Jennifer Doudna and Emmanuelle Charpentier, has revolutionized gene editing techniques in molecular biology.
                                Sample RDF triples:
                                    <CRISPR-Cas9> <discovered_by> <Jennifer_Doudna>
                                    <CRISPR-Cas9> <discovered_by> <Emmanuelle_Charpentier>
                                    <CRISPR-Cas9> <revolutionized> <GeneEditingTechniques>


        **Text:**
        {text}
        """

    message = input_format.format(text = text)

    messages = [{'role': 'user', 'content': message}]
    input_ids = tokenizer.apply_chat_template(messages, add_generation_prompt = True, return_tensors="pt")
    output = tokenizer.decode(model.generate(input_ids=input_ids, max_length=2048)[0], skip_special_tokens=True)
    return output

In [ ]:
model = AutoModelForCausalLM.from_pretrained("sciphi/triplex", trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained("sciphi/triplex", trust_remote_code=True)

config.json:   0%|          | 0.00/3.48k [00:00<?, ?B/s]

configuration_phi3.py:   0%|          | 0.00/11.2k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-128k-instruct:
- configuration_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_phi3.py:   0%|          | 0.00/73.2k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-128k-instruct:
- modeling_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
WARNING:transformers_modules.microsoft.Phi-3-mini-128k-instruct.a90b62ae09941edff87a90ced39ba5807e6b2ade.modeling_phi3:`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
WARNING:transformers_modules.microsoft.Phi-3-mini-128k-instruct.a90b62ae09941edff87a90ced39ba5807e6b2ade.modeling_phi3:Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.

model.safetensors.index.json:   0%|          | 0.00/16.3k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
#entity_types = [ "LOCATION", "POSITION", "DATE", "CITY", "COUNTRY", "NUMBER" ]
#predicates = [ "POPULATION", "AREA" ]
text = """
San Francisco, officially the City and County of San Francisco, is a commercial, financial, and cultural center in Northern California.

With a population of 808,437 residents as of 2022, San Francisco is the fourth most populous city in the U.S. state of California behind Los Angeles, San Diego, and San Jose.
"""

prediction = triplextract(model, tokenizer, text)
print(prediction)

##### Trying with t5-small

In [ ]:
model_name = "t5-small"
t5_tokenizer = AutoTokenizer.from_pretrained(model_name)
t5_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
inputs = t5_tokenizer(text4, return_tensors="pt", max_length=512, truncation=True)

In [ ]:
outputs = t5_model.generate(**inputs)
extracted_text = t5_tokenizer.decode(outputs[0], skip_special_tokens=True)

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1375: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

In [ ]:
print(extracted_text)

negative

##### SciFive

In [ ]:
model_name = "razent/SciFive-base-Pubmed"

In [ ]:
scifive_tokenizer = AutoTokenizer.from_pretrained(model_name)
scifive_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

config.json:   0%|          | 0.00/581 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/892M [00:00<?, ?B/s]

In [ ]:
encoding = scifive_tokenizer.encode_plus(text4, pad_to_max_length=True, return_tensors="pt")
input_ids, attention_masks = encoding["input_ids"], encoding["attention_mask"]

In [ ]:
outputs = scifive_model.generate(
    input_ids=input_ids, attention_mask=attention_masks,
    max_length=256,
    early_stopping=True
)

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:638: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(

In [ ]:
for output in outputs:
    line = scifive_tokenizer.decode(output, skip_special_tokens=True, clean_up_tokenization_spaces=True)
    print(line)
    break

entity-entity triplet from the following sentence:-entity-relation-entity triplet from the following sentence:.:.....-relation-entity triplet from the following sentence:-relation-entity......----entity-entity-entity triplet-entity.. The following sentence The following sentence:-.

In [ ]:
extracted_text

'entity-entity triplet from the following sentence:-entity-'

##### Testing

Test String <br>
```
Cardiovascular disease (CVD) is caused by a multitude of complex and largely heritable conditions.
Identifying key genes and understanding their susceptibility to CVD in the human genome can assist in early diagnosis and personalized treatment of the relevant patients.
Heart failure (HF) is among those CVD phenotypes that has a high rate of mortality.
In this study, we investigated genes primarily associated with HF and other CVDs.
Achieving the goals of this study, we built a cohort of thirty-five consented patients, and sequenced their serum-based samples.
We have generated and processed whole genome sequence (WGS) data, and performed functional mutation, splice, variant distribution, and divergence analysis to understand the relationships between each mutation type and its impact.
Our variant and prevalence analysis foundFLNA, CST3, LGALS3, and HBA1 linked to many enrichment pathways.
Functional mutation analysis uncovered ACE,MME,LGALS3,NR3C2,PIK3C2A,CALD1,TEK, and TRPV1 to be notable and potentially significant genes.
We discovered intron, 5ʹ Flank, 3ʹ UTR, and 3ʹ Flank mutations to be the most common among HF and other CVD genes.
Missense mutations were less common among HF and other CVD genes but had more of a functional impact.
We reported HBA1,FADD,NPPC,ADRB2,ADBR1,MYH6, and PLN to be consequential based on our divergence analysis.
Subject terms: Cardiovascular diseases, Genomics.
```

In [ ]:
test_str = """
Cardiovascular disease (CVD) is caused by a multitude of complex and largely heritable conditions.
Identifying key genes and understanding their susceptibility to CVD in the human genome can assist in early diagnosis and personalized treatment of the relevant patients.
Heart failure (HF) is among those CVD phenotypes that has a high rate of mortality.
In this study, we investigated genes primarily associated with HF and other CVDs.
Achieving the goals of this study, we built a cohort of thirty-five consented patients, and sequenced their serum-based samples.
We have generated and processed whole genome sequence (WGS) data, and performed functional mutation, splice, variant distribution, and divergence analysis to understand the relationships between each mutation type and its impact.
Our variant and prevalence analysis foundFLNA, CST3, LGALS3, and HBA1 linked to many enrichment pathways.
Functional mutation analysis uncovered ACE,MME,LGALS3,NR3C2,PIK3C2A,CALD1,TEK, and TRPV1 to be notable and potentially significant genes.
We discovered intron, 5ʹ Flank, 3ʹ UTR, and 3ʹ Flank mutations to be the most common among HF and other CVD genes.
Missense mutations were less common among HF and other CVD genes but had more of a functional impact.
We reported HBA1,FADD,NPPC,ADRB2,ADBR1,MYH6, and PLN to be consequential based on our divergence analysis.
Subject terms: Cardiovascular diseases, Genomics.
"""

In [ ]:
keywords = kw_model.extract_keywords(test_str)

In [ ]:
scibert_keywords = kw_scibert.extract_keywords(test_str)

In [ ]:
print("DistilBERT Keywords:", keywords)

DistilBERT Keywords: [('phenotypes', 0.6427), ('nr3c2', 0.6292), ('lgals3', 0.6125), ('trpv1', 0.6048), ('consequential', 0.5993)]

In [ ]:
print("SciBERT Keywords:", scibert_keywords)

SciBERT Keywords: [('pik3c2a', 0.595), ('genes', 0.5892), ('cald1', 0.589), ('genomics', 0.5826), ('mutations', 0.5811)]

In [ ]:
kw_model_base = KeyBERT()

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
kw_model_base.extract_keywords(test_str,keyphrase_ngram_range=(1, 2), stop_words='english')

[('cvd genes', 0.5007),
 ('significant genes', 0.4826),
 ('key genes', 0.4692),
 ('genes missense', 0.4479),
 ('human genome', 0.4431)]

In [ ]:
keywords = kw_model.extract_keywords(test_abstracts[0])

In [ ]:
scibert_keywords = kw_scibert.extract_keywords(test_abstracts[0])

In [ ]:
print("DistilBERT Keywords:", keywords)

DistilBERT Keywords: [('andhba1linked', 0.6743), ('andtrpv1to', 0.6679), ('phenotypes', 0.6479), ('nr3c2', 0.6381), ('lgals3', 0.6264)]

In [ ]:
print("SciBERT Keywords:", scibert_keywords)

SciBERT Keywords: [('andhba1linked', 0.6307), ('reportedhba1', 0.6233), ('pik3c2a', 0.6121), ('cald1', 0.6106), ('genes', 0.6074)]

In [ ]:
test_abstracts[1]

'  Heart failure (HF) is a complex trait, influenced by environmental and genetic factors, that affects over 30 million individuals worldwide. Historically, the genetics of HF have been studied in Mendelian forms of disease, where rare genetic variants have been linked to familial cardiomyopathies. More recently, genome-wide association studies (GWAS) have successfully identified common genetic variants associated with risk of HF. However, the relative importance of genetic variants across the allele-frequency spectrum remains incompletely characterized. Here, we report the results of common- and rare-variant association studies of all-cause heart failure, applying recently developed methods to quantify the heritability of HF attributable to different classes of genetic variation. We combine GWAS data across multiple populations including 207,346 individuals with HF and 2,151,210 without, identifying 176 risk loci at genome-wide significance (p < 5×10−8). Signals at newly identified common-variant loci include coding variants in Mendelian cardiomyopathy genes (MYBPC3,BAG3), as well as regulators of lipoprotein (LPL) and glucose metabolism (GIPR,GLP1R), and are enriched in cardiac, muscle, nerve, and vascular tissues, as well as myocyte and adipocyte cell types. Gene burden studies across three biobanks (PMBB, UKB, AOU) including 27,208 individuals with HF and 349,126 without uncover exome-wide significant (p < 3.15×10−6) associations for HF and rare predicted loss-of-function (pLoF) variants inTTN,MYBPC3,FLNC, and BAG3.Total burden heritability of rare coding variants (2.2%, 95% CI 0.99–3.5%) is highly concentrated in a small set of Mendelian cardiomyopathy genes, and is lower than heritability attributable to common variants (4.3%, 95% CI 3.9–4.7%) which is more diffusely spread throughout the genome. Finally, we demonstrate that common-variant background, in the form of a polygenic risk score (PRS), significantly modifies the risk of HF among carriers of pathogenic truncating variants in the Mendelian cardiomyopathy gene TTN. These findings suggest a significant polygenic component to HF exists that is not captured by current clinical genetic testing.'

##### Experimental - BioRED model finetuning

In [ ]:
def group_triplets_by_head(triplets):
    """
    Groups triplets by head entity for consolidated output.

    Args:
        triplets (list): List of triplets in the format ['<triplet> Head <subj> Tail <obj> Relation'].

    Returns:
        str: A single consolidated string of grouped triplets.
    """
    grouped_triplets = {}

    for triplet in triplets:
        # Extract Head, Tail, Relation from the triplet
        parts = triplet.replace("<triplet>", "").split("<subj>")
        if len(parts) == 2:
            head = parts[0].strip()
            tail_relation = parts[1].split("<obj>")
            if len(tail_relation) == 2:
                tail = tail_relation[0].strip()
                relation = tail_relation[1].strip()

                # Group by Head entity
                if head not in grouped_triplets:
                    grouped_triplets[head] = []
                grouped_triplets[head].append((tail, relation))

    # Format consolidated output
    formatted_output = []
    for head, relations in grouped_triplets.items():
        relation_strings = " <subj> ".join([f"{tail} <obj> {relation}" for tail, relation in relations])
        formatted_output.append(f"<triplet> {head} <subj> {relation_strings}")

    return " ".join(formatted_output)

In [ ]:
# Example triplets
triplets = [
    "<triplet> HNF-6 <subj> Type II diabetes <obj> Association",
    "<triplet> glucose <subj> insulin <obj> Positive_Correlation",
    "<triplet> glucose <subj> Type II diabetes <obj> Association"
]

In [ ]:
# Grouped output
grouped_output = group_triplets_by_head(triplets)
print(grouped_output)

<triplet> HNF-6 <subj> Type II diabetes <obj> Association <triplet> glucose <subj> insulin <obj> Positive_Correlation <subj> Type II diabetes <obj> Association

In [ ]:
def transform_biored_to_rebel_format(dataset):
    rebel_data = []

    for entry in dataset:
        # Concatenate title and abstract
        title = entry['passages'][0]['text'][0]  # Title
        abstract = entry['passages'][1]['text'][0]  # Abstract
        input_text = f"{title} {abstract}"

        # Map entity IDs to entity text
        entity_map = {entity['concept_id']: entity['text'][0] for entity in entry['entities']}

        # Generate triplets
        triplets = []
        for relation in entry['relations']:
            concept_1 = relation['concept_1']
            concept_2 = relation['concept_2']
            rel_type = relation['type']

            # Ensure both entities exist
            if concept_1 in entity_map and concept_2 in entity_map:
                triplet = f"<triplet> {entity_map[concept_1]} <subj> {entity_map[concept_2]} <obj> {rel_type}"
                triplets.append(triplet)

        # Only include rows with valid triplets
        if triplets:
            rebel_data.append({"input": input_text, "output": triplets})

    return rebel_data

In [ ]:
index = 0

In [ ]:
for entry in biored_train_df:
  print(f'Processing Entry: {entry}\n')
  title = entry['passages'][0]['text'][0]  # Title
  abstract = entry['passages'][1]['text'][0]  # Abstract

  print(f'Title: {title}\nAbstract: {abstract}\n')

  if index == 0:
    break

Processing Entry: {'pmid': '10491763', 'passages': [{'type': 'title', 'text': ['Hepatocyte nuclear factor-6: associations between genetic variability and type II diabetes and between genetic variability and estimates of insulin secretion.'], 'offsets': [[0, 158]]}, {'type': 'abstract', 'text': ['The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.'], 'offsets': [[159, 1797]]}], 'entities': [{'text': ['Hepatocyte nuclear factor-6'], 'offsets': [[0, 27]], 'concept_id': '3175', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['type II diabetes'], 'offsets': [[74, 90]], 'concept_id': 'D003924', 'semantic_type_id': 'DiseaseOrPhenotypicFeature'}, {'text': ['insulin'], 'offsets': [[140, 147]], 'concept_id': '3630', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['hepatocyte nuclear factor (HNF)-6'], 'offsets': [[184, 217]], 'concept_id': '3175', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['maturity-onset diabetes'], 'offsets': [[292, 315]], 'concept_id': 'D003924', 'semantic_type_id': 'DiseaseOrPhenotypicFeature'}, {'text': ['HNF-6'], 'offsets': [[389, 394]], 'concept_id': '3175', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['Type II (non-insulin-dependent) diabetes mellitus'], 'offsets': [[430, 479]], 'concept_id': 'D003924', 'semantic_type_id': 'DiseaseOrPhenotypicFeature'}, {'text': ['insulin'], 'offsets': [[497, 504]], 'concept_id': '3630', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['glucose'], 'offsets': [[518, 525]], 'concept_id': 'D005947', 'semantic_type_id': 'ChemicalEntity'}, {'text': ['HNF-6'], 'offsets': [[620, 625]], 'concept_id': '3175', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['MODY'], 'offsets': [[676, 680]], 'concept_id': '3172,3651,6927', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['MODY1'], 'offsets': [[715, 720]], 'concept_id': '3172', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['MODY3'], 'offsets': [[722, 727]], 'concept_id': '6927', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['MODY4'], 'offsets': [[732, 737]], 'concept_id': '3651', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['patients'], 'offsets': [[754, 762]], 'concept_id': '9606', 'semantic_type_id': 'OrganismTaxon'}, {'text': ['Type II diabetes'], 'offsets': [[779, 795]], 'concept_id': 'D003924', 'semantic_type_id': 'DiseaseOrPhenotypicFeature'}, {'text': ['Pro75 Ala'], 'offsets': [[1070, 1079]], 'concept_id': 'rs74805019', 'semantic_type_id': 'SequenceVariant'}, {'text': ['Pro75Ala'], 'offsets': [[1143, 1151]], 'concept_id': 'rs74805019', 'semantic_type_id': 'SequenceVariant'}, {'text': ['patients'], 'offsets': [[1216, 1224]], 'concept_id': '9606', 'semantic_type_id': 'OrganismTaxon'}, {'text': ['Type II diabetes mellitus'], 'offsets': [[1230, 1255]], 'concept_id': 'D003924', 'semantic_type_id': 'DiseaseOrPhenotypicFeature'}, {'text': ['glucose'], 'offsets': [[1304, 1311]], 'concept_id': 'D005947', 'semantic_type_id': 'ChemicalEntity'}, {'text': ['glucose'], 'offsets': [[1379, 1386]], 'concept_id': 'D005947', 'semantic_type_id': 'ChemicalEntity'}, {'text': ['glucose'], 'offsets': [[1413, 1420]], 'concept_id': 'D005947', 'semantic_type_id': 'ChemicalEntity'}, {'text': ['Type II diabetic'], 'offsets': [[1443, 1459]], 'concept_id': 'D003924', 'semantic_type_id': 'DiseaseOrPhenotypicFeature'}, {'text': ['patients'], 'offsets': [[1460, 1468]], 'concept_id': '9606', 'semantic_type_id': 'OrganismTaxon'}, {'text': ['glucose'], 'offsets': [[1573, 1580]], 'concept_id': 'D005947', 'semantic_type_id': 'ChemicalEntity'}, {'text': ['insulin'], 'offsets': [[1595, 1602]], 'concept_id': '3630', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['C-peptide'], 'offsets': [[1606, 1615]], 'concept_id': '3630', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['HNF-6'], 'offsets': [[1667, 1672]], 'concept_id': '3175', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['Type II diabetes'], 'offsets': [[1702, 1718]], 'concept_id': 'D003924', 'semantic_type_id': 'DiseaseOrPhenotypicFeature'}, {'text': ['insulin'], 'offsets': [[1738, 1745]], 'concept_id': '3630', 'semantic_type_id': 'GeneOrGeneProduct'}, {'text': ['glucose'], 'offsets': [[1759, 1766]], 'concept_id': 'D005947', 'semantic_type_id': 'ChemicalEntity'}], 'relations': [{'novel': 'No', 'type': 'Association', 'concept_1': '3175', 'concept_2': 'D003924'}, {'novel': 'No', 'type': 'Positive_Correlation', 'concept_1': 'D005947', 'concept_2': '3630'}, {'novel': 'No', 'type': 'Association', 'concept_1': 'D005947', 'concept_2': 'D003924'}]}

Title: Hepatocyte nuclear factor-6: associations between genetic variability and type II diabetes and between genetic variability and estimates of insulin secretion.
Abstract: The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.

In [ ]:
# Transform dataset
rebel_formatted_data = transform_biored_to_rebel_format(biored_train_df)

In [ ]:
rebel_formatted_df = pd.DataFrame(rebel_formatted_data)

In [ ]:
rebel_formatted_df.to_csv('rebel_formatted_data.csv', index=False)

In [ ]:
df = pd.read_csv('/content/rebel_formatted_data.csv')

In [ ]:
df['output_1'] = "".join(df['output'])

#### Including coreference resolution module and performing inference again

###### Trying with AllenNLP - ABORT MISSION - DID NOT WORK

In [ ]:
import allennlp

In [ ]:
from allennlp.data.tokenizers import PretrainedTransformerTokenizer
from allennlp.models.archival import load_archive

/content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/fairscale/experimental/nn/offload.py:19: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  return torch.cuda.amp.custom_fwd(orig_func)  # type: ignore
/content/gdrive/MyDrive/CS_546_Project_Dependencies/lib/python3.10/site-packages/fairscale/experimental/nn/offload.py:30: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  return torch.cuda.amp.custom_bwd(orig_func)  # type: ignore

In [ ]:
from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging

In [ ]:
from allennlp_models.pretrained import load_predictor

##### Approach 2 - Using load_predictor

In [ ]:
predictor = load_predictor("coref-scibert")
#"structured-prediction-srl-bert"

In [ ]:
result = predictor.predict(document=text5_a)

In [ ]:
resolved_text = result["document"]  # Resolved tokens as a list

In [ ]:
resolved_text_str = " ".join(resolved_text)

##### Approach 3 - Using Load archive

In [ ]:
archive = load_archive("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2021.03.10.tar.gz")

AttributeError: add_special_tokens conflicts with the method add_special_tokens in BertTokenizer

In [ ]:
print(archive.config)

###### Approach 1 - Using Predictor from allennlp.predictors.predictor

In [ ]:
model_url = 'https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2021.03.10.tar.gz'
# coref-spanbert-large-2020.02.27.tar.gz

In [ ]:
predictor = Predictor.from_path(model_url)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

Output()

config.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

AttributeError: add_special_tokens conflicts with the method add_special_tokens in BertTokenizer

In [ ]:
model_url = 'https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz'
predictor = Predictor.from_path(model_url)

Output()

AttributeError: add_special_tokens conflicts with the method add_special_tokens in BertTokenizer

In [ ]:
prediction = predictor.predict(document=text5_a)

##### Trying HuggingFace models

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("allenai/longformer-base-4096")

In [ ]:
model = AutoModel.from_pretrained("allenai/longformer-base-4096")

pytorch_model.bin:   0%|          | 0.00/597M [00:00<?, ?B/s]

In [ ]:
inputs = tokenizer(text5_a, return_tensors="pt", truncation=True, max_length=4096)

In [ ]:
outputs = model(**inputs)

Input ids are automatically padded to be a multiple of `config.attention_window`: 512

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("biu-nlp/f-coref")
model = AutoModelForTokenClassification.from_pretrained("biu-nlp/f-coref")

tokenizer_config.json:   0%|          | 0.00/393 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/819 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/362M [00:00<?, ?B/s]

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at biu-nlp/f-coref and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
inputs = tokenizer(text5_a, return_tensors="pt")

In [ ]:
with torch.no_grad():
    outputs = model(**inputs)

In [ ]:
inputs["input_ids"].squeeze()

tensor([    0,  5583,   211,  6998,  2133,     8,  8830,   459,  7275, 33475,
          906,  2967,     5,  4307,  1729,  4454,    12, 36061,   466,   467,
            4,   264,   423,   351,    10, 12821,  9421,     4,     2])

In [ ]:
tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"].squeeze())
logits = outputs.logits  # The logits for each token
probabilities = torch.softmax(logits, dim=-1).squeeze()

In [ ]:
predicted_labels = torch.argmax(probabilities, dim=-1).tolist()

In [ ]:
def extract_coref_clusters(tokens, predicted_labels):
    clusters = {}
    token_map = []
    for idx, (token, label) in enumerate(zip(tokens, predicted_labels)):
        if label > 0:  # 0 typically means "no cluster"
            if label not in clusters:
                clusters[label] = []
            # Handle special tokens (e.g., subword tokens starting with ##)
            if token.startswith("##"):
                token = token[2:]
                token_map[-1] += token  # Append subword to previous token
            else:
                clusters[label].append((token, idx))
                token_map.append(token)
        else:
            token_map.append(token)
    return clusters, token_map

In [ ]:
coref_clusters = extract_coref_clusters(tokens, predicted_labels)

In [ ]:
coref_clusters

({1: [('<s>', 0),
   ('ĠJennifer', 1),
   ('ĠD', 2),
   ('oud', 3),
   ('na', 4),
   ('Ġand', 5),
   ('ĠEmmanuel', 6),
   ('le', 7),
   ('ĠChar', 8),
   ('pent', 9),
   ('ier', 10),
   ('Ġdiscovered', 11),
   ('Ġthe', 12),
   ('ĠCR', 13),
   ('IS', 14),
   ('-', 16),
   ('Cas', 17),
   ('9', 18),
   ('.', 20),
   ('ĠShe', 21),
   ('Ġlater', 22),
   ('Ġwon', 23),
   ('Ġa', 24),
   ('ĠNobel', 25),
   ('ĠPrize', 26),
   ('.', 27),
   ('</s>', 28)]},
 ['<s>',
  'ĠJennifer',
  'ĠD',
  'oud',
  'na',
  'Ġand',
  'ĠEmmanuel',
  'le',
  'ĠChar',
  'pent',
  'ier',
  'Ġdiscovered',
  'Ġthe',
  'ĠCR',
  'IS',
  'PR',
  '-',
  'Cas',
  '9',
  'Ġsystem',
  '.',
  'ĠShe',
  'Ġlater',
  'Ġwon',
  'Ġa',
  'ĠNobel',
  'ĠPrize',
  '.',
  '</s>'])

In [ ]:
def resolve_coreferences(original_text, token_map, clusters):
    resolved_text = original_text
    for cluster_id, mentions in clusters.items():
        if len(mentions) > 1:  # Only process clusters with more than one mention
            antecedent = mentions[0][0]  # First mention is the antecedent
            for mention, idx in mentions[1:]:
                # Replace subsequent mentions in the text with the antecedent
                if mention in resolved_text:
                    resolved_text = resolved_text.replace(mention, antecedent)
    return resolved_text

In [ ]:
resolved_text = resolve_coreferences(text5_a, tokens, coref_clusters)

AttributeError: 'tuple' object has no attribute 'items'

In [ ]:
resolved_text

'Jennifer D<s><s> and Emmanuel<s> Char<s><s> discovered the CR<s>PR<s><s><s> system<s> She later won a Nobel Prize<s>'

##### Finetuning REBEL on BioRED dataset

In [ ]:
biored_df = load_dataset("bigbio/biored",trust_remote_code=True)

README.md:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

biored.py:   0%|          | 0.00/13.9k [00:00<?, ?B/s]

bigbiohub.py:   0%|          | 0.00/19.3k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/2.19M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

In [ ]:
biored_train_df = biored_df['train']

In [ ]:
biored_train_df

Dataset({
    features: ['pmid', 'passages', 'entities', 'relations'],
    num_rows: 400
})

In [ ]:
sample_data = biored_train_df[:5]

In [ ]:
#sample_data['passages'][0]
sample_data

{'pmid': ['10491763', '10661407', '10788334', '11009181', '11054569'],
 'passages': [[{'type': 'title',
    'text': ['Hepatocyte nuclear factor-6: associations between genetic variability and type II diabetes and between genetic variability and estimates of insulin secretion.'],
    'offsets': [[0, 158]]},
   {'type': 'abstract',
    'text': ['The transcription factor hepatocyte nuclear factor (HNF)-6 is an upstream regulator of several genes involved in the pathogenesis of maturity-onset diabetes of the young. We therefore tested the hypothesis that variability in the HNF-6 gene is associated with subsets of Type II (non-insulin-dependent) diabetes mellitus and estimates of insulin secretion in glucose tolerant subjects.   We cloned the coding region as well as the intron-exon boundaries of the HNF-6 gene. We then examined them on genomic DNA in six MODY probands without mutations in the MODY1, MODY3 and MODY4 genes and in 54 patients with late-onset Type II diabetes by combined single strand conformational polymorphism-heteroduplex analysis followed by direct sequencing of identified variants. An identified missense variant was examined in association studies and genotype-phenotype studies.   We identified two silent and one missense (Pro75 Ala) variant. In an association study the allelic frequency of the Pro75Ala polymorphism was 3.2% (95% confidence interval, 1.9-4.5) in 330 patients with Type II diabetes mellitus compared with 4.2% (2.4-6.0) in 238 age-matched glucose tolerant control subjects. Moreover, in studies of 238 middle-aged glucose tolerant subjects, of 226 glucose tolerant offspring of Type II diabetic patients and of 367 young healthy subjects, the carriers of the polymorphism did not differ from non-carriers in glucose induced serum insulin or C-peptide responses.   Mutations in the coding region of the HNF-6 gene are not associated with Type II diabetes or with changes in insulin responses to glucose among the Caucasians examined.'],
    'offsets': [[159, 1797]]}],
  [{'type': 'title',
    'text': ['Langerin, a novel C-type lectin specific to Langerhans cells, is an endocytic receptor that induces the formation of Birbeck granules.'],
    'offsets': [[0, 134]]},
   {'type': 'abstract',
    'text': ['We have identified a type II Ca2+-dependent lectin displaying mannose-binding specificity, exclusively expressed by Langerhans cells (LC), and named Langerin. LC are uniquely characterized by Birbeck granules (BG), which are organelles consisting of superimposed and zippered membranes. Here, we have shown that Langerin is constitutively associated with BG and that antibody to Langerin is internalized into these structures. Remarkably, transfection of Langerin cDNA into fibroblasts created a compact network of membrane structures with typical features of BG. Langerin is thus a potent inducer of membrane superimposition and zippering leading to BG formation. Our data suggest that induction of BG is a consequence of the antigen-capture function of Langerin, allowing routing into these organelles and providing access to a nonclassical antigen-processing pathway.'],
    'offsets': [[135, 1005]]}],
  [{'type': 'title',
    'text': ['Founder mutations in the BRCA1 gene in Polish families with breast-ovarian cancer.'],
    'offsets': [[0, 82]]},
   {'type': 'abstract',
    'text': ['We have undertaken a hospital-based study, to identify possible BRCA1 and BRCA2 founder mutations in the Polish population. The study group consisted of 66 Polish families with cancer who have at least three related females affected with breast or ovarian cancer and who had cancer diagnosed, in at least one of the three affected females, at age < 50 years. A total of 26 families had both breast and ovarian cancers, 4 families had ovarian cancers only, and 36 families had breast cancers only. Genomic DNA was prepared from the peripheral blood leukocytes of at least one affected woman from each family. The entire coding region of BRCA1 and BRCA2 was screened for the presence of germline mutations, by use of SSCP followed by direct sequencing of observed variants. Mutations were found in 35 (53%) of the 66 families studied. All but one of the mutations were detected within the BRCA1 gene. BRCA1 abnormalities were identified in all four families with ovarian cancer only, in 67% of 27 families with both breast and ovarian cancer, and in 34% of 35 families with breast cancer only. The single family with a BRCA2 mutation had the breast-ovarian cancer syndrome. Seven distinct mutations were identified; five of these occurred in two or more families. In total, recurrent mutations were found in 33 (94%) of the 35 families with detected mutations. Three BRCA1 abnormalities - 5382insC, C61G, and 4153delA - accounted for 51%, 20%, and 11% of the identified mutations, respectively..'],
    'offsets': [[83, 1576]]}],
  [{'type': 'title',
    'text': ["Apomorphine: an underutilized therapy for Parkinson's disease."],
    'offsets': [[0, 62]]},
   {'type': 'abstract',
    'text': ["Apomorphine was the first dopaminergic drug ever used to treat symptoms of Parkinson's disease. While powerful antiparkinsonian effects had been observed as early as 1951, the potential of treating fluctuating Parkinson's disease by subcutaneous administration of apomorphine has only recently become the subject of systematic study. A number of small scale clinical trials have unequivocally shown that intermittent subcutaneous apomorphine injections produce antiparkinsonian benefit close if not identical to that seen with levodopa and that apomorphine rescue injections can reliably revert off-periods even in patients with complex on-off motor swings. Continuous subcutaneous apomorphine infusions can reduce daily off-time by more than 50% in this group of patients, which appears to be a stronger effect than that generally seen with add-on therapy with oral dopamine agonists or COMT inhibitors. Extended follow-up studies of up to 8 years have demonstrated long-term persistence of apomorphine efficacy. In addition, there is convincing clinical evidence that monotherapy with continuous subcutaneous apomorphine infusions is associated with marked reductions of preexisting levodopa-induced dyskinesias. The main side effects of subcutaneous apomorphine treatment are related to cutaneous tolerability problems, whereas sedation and psychiatric complications play a lesser role. Given the marked degree of efficacy of subcutaneous apomorphine treatment in fluctuating Parkinson's disease, this approach seems to deserve more widespread clinical use."],
    'offsets': [[63, 1623]]}],
  [{'type': 'title',
    'text': ['Rab6c, a new member of the rab gene family, is involved in drug resistance in MCF7/AdrR cells.'],
    'offsets': [[0, 94]]},
   {'type': 'abstract',
    'text': ["A new Rab6 homolog cDNA, Rab6c, was discovered by a hypermethylated DNA fragment probe that was isolated from a human multidrug resistant (MDR) breast cancer cell line, MCF7/AdrR, by the methylation sensitive-representational difference analysis (MS-RDA) technique. Rab6c was found to be under-expressed in MCF7/AdrR and MES-SA/Dx5 (a human MDR uterine sarcoma cell line) compared with their non-MDR parental cell lines. MCF7/AdrR cells expressing the exogenous Rab6c exhibited less resistance to several anti-cancer drugs, such as doxorubicin (DOX), taxol, vinblastine, and vincristine, than the control cells containing the empty vector. Flow cytometry experiments confirmed that the transfectants' diminished resistance to DOX was caused by increased drug accumulation induced by the exogenous Rab6c. These results indicate that Rab6c is involved in drug resistance in MCF7/AdrR cells."],
    'offsets': [[95, 983]]}]],
 'entities': [[{'text': ['Hepatocyte nuclear factor-6'],
    'offsets': [[0, 27]],
    'concept_id': '3175',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['type II diabetes'],
    'offsets': [[74, 90]],
    'concept_id': 'D003924',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['insulin'],
    'offsets': [[140, 147]],
    'concept_id': '3630',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['hepatocyte nuclear factor (HNF)-6'],
    'offsets': [[184, 217]],
    'concept_id': '3175',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['maturity-onset diabetes'],
    'offsets': [[292, 315]],
    'concept_id': 'D003924',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['HNF-6'],
    'offsets': [[389, 394]],
    'concept_id': '3175',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['Type II (non-insulin-dependent) diabetes mellitus'],
    'offsets': [[430, 479]],
    'concept_id': 'D003924',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['insulin'],
    'offsets': [[497, 504]],
    'concept_id': '3630',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['glucose'],
    'offsets': [[518, 525]],
    'concept_id': 'D005947',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['HNF-6'],
    'offsets': [[620, 625]],
    'concept_id': '3175',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['MODY'],
    'offsets': [[676, 680]],
    'concept_id': '3172,3651,6927',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['MODY1'],
    'offsets': [[715, 720]],
    'concept_id': '3172',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['MODY3'],
    'offsets': [[722, 727]],
    'concept_id': '6927',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['MODY4'],
    'offsets': [[732, 737]],
    'concept_id': '3651',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['patients'],
    'offsets': [[754, 762]],
    'concept_id': '9606',
    'semantic_type_id': 'OrganismTaxon'},
   {'text': ['Type II diabetes'],
    'offsets': [[779, 795]],
    'concept_id': 'D003924',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['Pro75 Ala'],
    'offsets': [[1070, 1079]],
    'concept_id': 'rs74805019',
    'semantic_type_id': 'SequenceVariant'},
   {'text': ['Pro75Ala'],
    'offsets': [[1143, 1151]],
    'concept_id': 'rs74805019',
    'semantic_type_id': 'SequenceVariant'},
   {'text': ['patients'],
    'offsets': [[1216, 1224]],
    'concept_id': '9606',
    'semantic_type_id': 'OrganismTaxon'},
   {'text': ['Type II diabetes mellitus'],
    'offsets': [[1230, 1255]],
    'concept_id': 'D003924',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['glucose'],
    'offsets': [[1304, 1311]],
    'concept_id': 'D005947',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['glucose'],
    'offsets': [[1379, 1386]],
    'concept_id': 'D005947',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['glucose'],
    'offsets': [[1413, 1420]],
    'concept_id': 'D005947',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['Type II diabetic'],
    'offsets': [[1443, 1459]],
    'concept_id': 'D003924',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['patients'],
    'offsets': [[1460, 1468]],
    'concept_id': '9606',
    'semantic_type_id': 'OrganismTaxon'},
   {'text': ['glucose'],
    'offsets': [[1573, 1580]],
    'concept_id': 'D005947',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['insulin'],
    'offsets': [[1595, 1602]],
    'concept_id': '3630',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['C-peptide'],
    'offsets': [[1606, 1615]],
    'concept_id': '3630',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['HNF-6'],
    'offsets': [[1667, 1672]],
    'concept_id': '3175',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['Type II diabetes'],
    'offsets': [[1702, 1718]],
    'concept_id': 'D003924',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['insulin'],
    'offsets': [[1738, 1745]],
    'concept_id': '3630',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['glucose'],
    'offsets': [[1759, 1766]],
    'concept_id': 'D005947',
    'semantic_type_id': 'ChemicalEntity'}],
  [{'text': ['Langerin'],
    'offsets': [[0, 8]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['C-type lectin'],
    'offsets': [[18, 31]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['type II Ca2+-dependent lectin'],
    'offsets': [[156, 185]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['mannose'],
    'offsets': [[197, 204]],
    'concept_id': 'D008358',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['Langerin'],
    'offsets': [[284, 292]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['Langerin'],
    'offsets': [[447, 455]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['Langerin'],
    'offsets': [[514, 522]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['Langerin'],
    'offsets': [[590, 598]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['Langerin'],
    'offsets': [[699, 707]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['Langerin'],
    'offsets': [[890, 898]],
    'concept_id': '50489',
    'semantic_type_id': 'GeneOrGeneProduct'}],
  [{'text': ['BRCA1'],
    'offsets': [[25, 30]],
    'concept_id': '672',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['breast-ovarian cancer'],
    'offsets': [[60, 81]],
    'concept_id': 'D061325',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['BRCA1'],
    'offsets': [[147, 152]],
    'concept_id': '672',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['BRCA2'],
    'offsets': [[157, 162]],
    'concept_id': '675',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['cancer'],
    'offsets': [[260, 266]],
    'concept_id': 'D009369',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['breast or ovarian cancer'],
    'offsets': [[321, 345]],
    'concept_id': 'D001943,D010051',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['cancer'],
    'offsets': [[358, 364]],
    'concept_id': 'D009369',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['breast and ovarian cancers'],
    'offsets': [[474, 500]],
    'concept_id': 'D001943,D010051',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['ovarian cancers'],
    'offsets': [[517, 532]],
    'concept_id': 'D010051',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['breast cancers'],
    'offsets': [[559, 573]],
    'concept_id': 'D001943',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['woman'],
    'offsets': [[667, 672]],
    'concept_id': '9606',
    'semantic_type_id': 'OrganismTaxon'},
   {'text': ['BRCA1'],
    'offsets': [[719, 724]],
    'concept_id': '672',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['BRCA2'],
    'offsets': [[729, 734]],
    'concept_id': '675',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['BRCA1'],
    'offsets': [[970, 975]],
    'concept_id': '672',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['BRCA1 abnormalities'],
    'offsets': [[982, 1001]],
    'concept_id': 'OMIM:604370',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['ovarian cancer'],
    'offsets': [[1044, 1058]],
    'concept_id': 'D010051',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['breast and ovarian cancer'],
    'offsets': [[1097, 1122]],
    'concept_id': 'D001943,D010051',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['breast cancer'],
    'offsets': [[1155, 1168]],
    'concept_id': 'D001943',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['BRCA2'],
    'offsets': [[1200, 1205]],
    'concept_id': '675',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['breast-ovarian cancer syndrome'],
    'offsets': [[1223, 1253]],
    'concept_id': 'D061325',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['BRCA1 abnormalities'],
    'offsets': [[1448, 1467]],
    'concept_id': 'OMIM:604370',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['5382insC'],
    'offsets': [[1470, 1478]],
    'concept_id': 'c|INS|5382|C',
    'semantic_type_id': 'SequenceVariant'},
   {'text': ['C61G'],
    'offsets': [[1480, 1484]],
    'concept_id': 'rs28897672',
    'semantic_type_id': 'SequenceVariant'},
   {'text': ['4153delA'],
    'offsets': [[1490, 1498]],
    'concept_id': 'c|DEL|4153|A',
    'semantic_type_id': 'SequenceVariant'}],
  [{'text': ['Apomorphine'],
    'offsets': [[0, 11]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ["Parkinson's disease"],
    'offsets': [[42, 61]],
    'concept_id': 'D010300',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['Apomorphine'],
    'offsets': [[63, 74]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['dopaminergic drug'],
    'offsets': [[89, 106]],
    'concept_id': 'D004298',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ["Parkinson's disease"],
    'offsets': [[138, 157]],
    'concept_id': 'D010300',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ["Parkinson's disease"],
    'offsets': [[273, 292]],
    'concept_id': 'D010300',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['apomorphine'],
    'offsets': [[327, 338]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['apomorphine'],
    'offsets': [[493, 504]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['levodopa'],
    'offsets': [[590, 598]],
    'concept_id': 'D007980',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['apomorphine'],
    'offsets': [[608, 619]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['patients'],
    'offsets': [[678, 686]],
    'concept_id': '9606',
    'semantic_type_id': 'OrganismTaxon'},
   {'text': ['apomorphine'],
    'offsets': [[745, 756]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['patients'],
    'offsets': [[827, 835]],
    'concept_id': '9606',
    'semantic_type_id': 'OrganismTaxon'},
   {'text': ['dopamine agonists'],
    'offsets': [[930, 947]],
    'concept_id': 'D018491',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['COMT inhibitors'],
    'offsets': [[951, 966]],
    'concept_id': 'D065098',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['apomorphine'],
    'offsets': [[1055, 1066]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['apomorphine'],
    'offsets': [[1174, 1185]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['levodopa'],
    'offsets': [[1248, 1256]],
    'concept_id': 'D007980',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['dyskinesias'],
    'offsets': [[1265, 1276]],
    'concept_id': 'D004409',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['apomorphine'],
    'offsets': [[1316, 1327]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ['psychiatric complications'],
    'offsets': [[1407, 1432]],
    'concept_id': 'D001523',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'},
   {'text': ['apomorphine'],
    'offsets': [[1505, 1516]],
    'concept_id': 'D001058',
    'semantic_type_id': 'ChemicalEntity'},
   {'text': ["Parkinson's disease"],
    'offsets': [[1542, 1561]],
    'concept_id': 'D010300',
    'semantic_type_id': 'DiseaseOrPhenotypicFeature'}],
  [{'text': ['Rab6c'],
    'offsets': [[0, 5]],
    'concept_id': '84084',
    'semantic_type_id': 'GeneOrGeneProduct'},
   {'text': ['rab'],

In [ ]:
# Transform dataset
rebel_formatted_data_updated = transform_biored_to_rebel_format_updated(biored_train_df)

In [ ]:
rebel_formatted_df = pd.DataFrame(rebel_formatted_data_updated)

In [ ]:
rebel_formatted_df.to_csv('rebel_formatted_data_updated.csv', index=False)